import {PuzzleRow} from '../puzzleTypes.ts';

export const AGE_14_TO_17: PuzzleRow[] = [
    ["English", "Which literary device is used in \"Time is a thief\"?", "metaphor", "simile", "irony", "oxymoron"],
    ["English", "\"Deafening silence\" is an example of which device?", "oxymoron", "simile", "pun", "hyperbole"],
    ["English", "Who wrote the novel \"1984\"?", "George Orwell", "Aldous Huxley", "H. G. Wells", "Ray Bradbury"],
    ["English", "Who wrote \"Pride and Prejudice\"?", "Jane Austen", "Charlotte Brontë", "George Eliot", "Emily Brontë"],
    ["English", "In which Shakespeare play is the main character a prince of Denmark?", "Hamlet", "Macbeth", "Othello", "King Lear"],
    ["English", "What do we call a speech in which a character speaks their thoughts aloud, alone on stage?", "a soliloquy", "a prologue", "an epilogue", "a dialogue"],
    ["English", "Which of these is a subordinating conjunction?", "although", "and", "but", "or"],
    ["English", "What is dramatic irony?", "when the audience knows more than the characters", "when someone says the opposite of what they mean", "when something unexpected happens", "when a character lies"],
    ["English", "Who wrote \"To Kill a Mockingbird\"?", "Harper Lee", "Mark Twain", "J. D. Salinger", "F. Scott Fitzgerald"],
    ["English", "Which is correct? \"There are ___ apples in the bowl than yesterday.\"", "fewer", "less", "lesser", "littler"],
    ["English", "How many syllables are in a line of iambic pentameter?", "10", "8", "12", "14"],
    ["English", "What is the repetition of vowel sounds in nearby words called?", "assonance", "consonance", "alliteration", "rhyme"],
    ["English", "Who wrote \"Lord of the Flies\"?", "William Golding", "George Orwell", "John Steinbeck", "Roald Dahl"],
    ["English", "What is a \"foil\" in literature?", "a character who contrasts with another to highlight their traits", "a type of rhyme", "the final chapter", "a narrator"],
    ["English", "Who wrote \"Great Expectations\"?", "Charles Dickens", "Thomas Hardy", "Oscar Wilde", "Robert Louis Stevenson"],
    ["English", "In \"Swimming is fun\", which word is a gerund?", "Swimming", "is", "fun", "none of them"],
    ["English", "What does \"ubiquitous\" mean?", "found everywhere", "very rare", "extremely loud", "ancient"],
    ["English", "What does \"benevolent\" mean?", "kind and well-meaning", "cruel", "lazy", "confused"],
    ["English", "What is a \"bildungsroman\"?", "a novel about growing up", "a war poem", "a type of play", "a news article"],
    ["English", "What is pathetic fallacy?", "weather or nature that reflects the mood of a scene", "a mistake in logic", "a very sad ending", "a character who is a fool"],
    ["English", "Which sentence uses \"whom\" correctly?", "To whom did you speak?", "Whom is going to the shop?", "Whom went home?", "Whom are you?"],
    ["English", "Who wrote \"The Great Gatsby\"?", "F. Scott Fitzgerald", "Ernest Hemingway", "John Steinbeck", "William Faulkner"],
    ["English", "Which of these is a Shakespeare comedy?", "A Midsummer Night's Dream", "Macbeth", "Hamlet", "Othello"],
    ["English", "What is the climax of a story?", "the point of highest tension", "the opening scene", "the final summary", "the title"],
    ["English", "Who wrote \"Frankenstein\"?", "Mary Shelley", "Jane Austen", "Bram Stoker", "Emily Brontë"],
    ["English", "Who wrote 'Jane Eyre'?", "Charlotte Brontë", "Emily Brontë", "Jane Austen", "George Eliot"],
    ["English", "Who wrote 'Wuthering Heights'?", "Emily Brontë", "Charlotte Brontë", "Anne Brontë", "Elizabeth Gaskell"],
    ["English", "Who wrote 'Animal Farm'?", "George Orwell", "Aldous Huxley", "William Golding", "H.G. Wells"],
    ["English", "Who wrote 'Brave New World'?", "Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"],
    ["English", "Who wrote 'Of Mice and Men'?", "John Steinbeck", "Ernest Hemingway", "F. Scott Fitzgerald", "Mark Twain"],
    ["English", "Who wrote 'The Catcher in the Rye'?", "J.D. Salinger", "John Steinbeck", "Harper Lee", "Jack Kerouac"],
    ["English", "Who wrote 'Romeo and Juliet'?", "William Shakespeare", "Christopher Marlowe", "Ben Jonson", "John Milton"],
    ["English", "Who wrote 'Paradise Lost'?", "John Milton", "John Donne", "Alexander Pope", "William Blake"],
    ["English", "Who wrote 'The Canterbury Tales'?", "Geoffrey Chaucer", "William Langland", "John Milton", "Edmund Spenser"],
    ["English", "Who wrote the poem 'The Tyger'?", "William Blake", "William Wordsworth", "John Keats", "Lord Byron"],
    ["English", "Who wrote the poem 'Daffodils' (I wandered lonely as a cloud)?", "William Wordsworth", "Samuel Taylor Coleridge", "John Keats", "Percy Shelley"],
    ["English", "Who wrote 'The Rime of the Ancient Mariner'?", "Samuel Taylor Coleridge", "William Wordsworth", "Lord Byron", "Alfred Tennyson"],
    ["English", "Who wrote the poem 'Ozymandias'?", "Percy Bysshe Shelley", "John Keats", "Lord Byron", "William Blake"],
    ["English", "Who wrote 'Ode to a Nightingale'?", "John Keats", "Percy Bysshe Shelley", "William Wordsworth", "Lord Byron"],
    ["English", "Who wrote 'Dulce et Decorum Est'?", "Wilfred Owen", "Siegfried Sassoon", "Rupert Brooke", "Ted Hughes"],
    ["English", "Who wrote 'The Waste Land'?", "T.S. Eliot", "W.B. Yeats", "Ezra Pound", "W.H. Auden"],
    ["English", "Who wrote the poem 'Still I Rise'?", "Maya Angelou", "Toni Morrison", "Alice Walker", "Langston Hughes"],
    ["English", "Who wrote the novel 'Things Fall Apart'?", "Chinua Achebe", "Wole Soyinka", "Ngũgĩ wa Thiong'o", "Chimamanda Ngozi Adichie"],
    ["English", "Who wrote 'Beloved'?", "Toni Morrison", "Alice Walker", "Maya Angelou", "Zora Neale Hurston"],
    ["English", "Who wrote 'Macbeth'?", "William Shakespeare", "Christopher Marlowe", "John Webster", "Ben Jonson"],
    ["English", "Who wrote 'An Inspector Calls'?", "J.B. Priestley", "Arthur Miller", "Harold Pinter", "Alan Bennett"],
    ["English", "Who wrote 'The Crucible'?", "Arthur Miller", "Tennessee Williams", "J.B. Priestley", "Eugene O'Neill"],
    ["English", "Who wrote 'A Streetcar Named Desire'?", "Tennessee Williams", "Arthur Miller", "Edward Albee", "Eugene O'Neill"],
    ["English", "Who wrote 'Waiting for Godot'?", "Samuel Beckett", "Harold Pinter", "Tom Stoppard", "Oscar Wilde"],
    ["English", "Who wrote 'The Importance of Being Earnest'?", "Oscar Wilde", "George Bernard Shaw", "Noël Coward", "Harold Pinter"],
    ["English", "Who wrote 'Pygmalion'?", "George Bernard Shaw", "Oscar Wilde", "J.M. Barrie", "Noël Coward"],
    ["English", "Who wrote 'Heart of Darkness'?", "Joseph Conrad", "Rudyard Kipling", "E.M. Forster", "Graham Greene"],
    ["English", "Who wrote 'A Passage to India'?", "E.M. Forster", "Rudyard Kipling", "Joseph Conrad", "Graham Greene"],
    ["English", "Who wrote 'Middlemarch'?", "George Eliot", "Charlotte Brontë", "Jane Austen", "Elizabeth Gaskell"],
    ["English", "What is the real name of the Victorian novelist George Eliot?", "Mary Ann Evans", "Charlotte Brontë", "Mary Shelley", "Elizabeth Gaskell"],
    ["English", "Who wrote 'Tess of the d'Urbervilles'?", "Thomas Hardy", "Charles Dickens", "George Eliot", "D.H. Lawrence"],
    ["English", "Who wrote 'The Picture of Dorian Gray'?", "Oscar Wilde", "Bram Stoker", "Robert Louis Stevenson", "Thomas Hardy"],
    ["English", "Who wrote 'Dracula'?", "Bram Stoker", "Mary Shelley", "Robert Louis Stevenson", "Arthur Conan Doyle"],
    ["English", "Who wrote 'Strange Case of Dr Jekyll and Mr Hyde'?", "Robert Louis Stevenson", "Bram Stoker", "Oscar Wilde", "Arthur Conan Doyle"],
    ["English", "Who wrote 'The Hound of the Baskervilles'?", "Arthur Conan Doyle", "Agatha Christie", "Wilkie Collins", "Charles Dickens"],
    ["English", "Who wrote 'And Then There Were None'?", "Agatha Christie", "Dorothy L. Sayers", "Arthur Conan Doyle", "Ruth Rendell"],
    ["English", "Who wrote 'The Handmaid's Tale'?", "Margaret Atwood", "Ursula K. Le Guin", "Toni Morrison", "Sylvia Plath"],
    ["English", "Who wrote 'The Bell Jar'?", "Sylvia Plath", "Virginia Woolf", "Anne Sexton", "Margaret Atwood"],
    ["English", "Who wrote 'Mrs Dalloway'?", "Virginia Woolf", "Jane Austen", "George Eliot", "Daphne du Maurier"],
    ["English", "Who wrote 'Rebecca'?", "Daphne du Maurier", "Virginia Woolf", "Agatha Christie", "Jean Rhys"],
    ["English", "Who wrote 'Never Let Me Go'?", "Kazuo Ishiguro", "Ian McEwan", "Julian Barnes", "Salman Rushdie"],
    ["English", "Who wrote 'Midnight's Children'?", "Salman Rushdie", "Arundhati Roy", "Vikram Seth", "Kazuo Ishiguro"],
    ["English", "Who wrote 'The God of Small Things'?", "Arundhati Roy", "Salman Rushdie", "Jhumpa Lahiri", "Anita Desai"],
    ["English", "Who wrote 'The Kite Runner'?", "Khaled Hosseini", "Salman Rushdie", "Orhan Pamuk", "Mohsin Hamid"],
    ["English", "Who wrote 'One Hundred Years of Solitude'?", "Gabriel García Márquez", "Jorge Luis Borges", "Isabel Allende", "Pablo Neruda"],
    ["English", "Who wrote 'The Old Man and the Sea'?", "Ernest Hemingway", "John Steinbeck", "William Faulkner", "Mark Twain"],
    ["English", "Who wrote 'Moby-Dick'?", "Herman Melville", "Nathaniel Hawthorne", "Mark Twain", "Edgar Allan Poe"],
    ["English", "Who wrote 'The Adventures of Huckleberry Finn'?", "Mark Twain", "Herman Melville", "Nathaniel Hawthorne", "Jack London"],
    ["English", "What is a sonnet's usual number of lines?", "14", "12", "16", "10"],
    ["English", "What name is given to a poem of four lines?", "a quatrain", "a couplet", "a sestet", "an octave"],
    ["English", "What name is given to two rhyming lines of verse?", "a couplet", "a quatrain", "a tercet", "a stanza only"],
    ["English", "What is blank verse?", "unrhymed iambic pentameter", "rhymed couplets", "free verse with no pattern", "a poem of five lines"],
    ["English", "What is free verse?", "poetry without a regular rhyme or metre", "poetry with strict rhyme", "poetry in iambic pentameter", "a type of sonnet"],
    ["English", "What is enjambment?", "a sentence running over a line break without punctuation", "a pause in the middle of a line", "repeating a word at the start of lines", "a rhyme in the middle of a line"],
    ["English", "What is caesura?", "a pause or break within a line of poetry", "the repeated ending of lines", "a line of ten syllables", "a poem of 14 lines"],
    ["English", "What is an oxymoron?", "two contradictory terms placed together", "a long sentence", "a repeated word", "an exaggerated claim"],
    ["English", "What is an allusion?", "an indirect reference to another work or event", "a long description", "a direct comparison", "a rhyme"],
    ["English", "What is irony?", "expressing the opposite of what is meant", "a direct statement", "a type of rhyme", "a long poem"],
    ["English", "What is a euphemism?", "a mild word used instead of a harsh one", "an exaggeration", "a type of comparison", "a rhyming pair"],
    ["English", "What is a motif in literature?", "a recurring element or idea", "the last line of a poem", "a type of character", "the opening of a play"],
    ["English", "What does 'omniscient narrator' mean?", "a narrator who knows everything about all characters", "a narrator who is a character in the story", "a narrator who tells only the hero's thoughts", "a narrator with no knowledge"],
    ["English", "What is an unreliable narrator?", "a narrator whose account cannot be fully trusted", "a narrator who knows everything", "a narrator who tells the truth", "a narrator who is absent"],
    ["English", "What is a tragic flaw (hamartia)?", "a character trait that leads to a hero's downfall", "a mistake by the author", "a rhyme scheme", "a plot twist"],
    ["English", "What is the 'denouement' of a story?", "the final resolution of the plot", "the beginning of the plot", "the climax", "the setting"],
    ["English", "What is a 'red herring' in a story?", "a misleading clue", "an important clue", "a type of character", "a type of ending"],
    ["English", "What is foreshadowing?", "hints about what will happen later", "a flashback to the past", "the story's setting", "a character's thoughts"],
    ["English", "What is a 'flashback' in literature?", "a scene set earlier than the main story", "a scene set in the future", "a rhyming scene", "a scene with no characters"],
    ["English", "What does the term 'tone' mean in writing?", "the writer's attitude to the subject", "the length of the text", "the rhyme scheme", "the title of the text"],
    ["English", "What does 'ambiguous' mean?", "open to more than one meaning", "very clear", "very long", "very short"],
    ["English", "What does 'ephemeral' mean?", "lasting a very short time", "lasting forever", "very large", "very small"],
    ["English", "What does 'pragmatic' mean?", "dealing with things sensibly and realistically", "unrealistic", "very emotional", "very quiet"],
    ["English", "What does 'meticulous' mean?", "showing great attention to detail", "careless", "lazy", "noisy"],
    ["English", "What does 'ostentatious' mean?", "showy, designed to impress", "quiet and modest", "hidden", "ancient"],
    ["English", "What does 'candid' mean?", "honest and open", "secretive", "rude only", "friendly only"],
    ["English", "What does 'loquacious' mean?", "talkative", "silent", "angry", "clumsy"],
    ["Science", "Which equation represents Newton's second law of motion?", "F = ma", "E = mc²", "V = IR", "P = mv"],
    ["Science", "What is the atomic number of carbon?", "6", "12", "8", "14"],
    ["Science", "What does DNA stand for?", "deoxyribonucleic acid", "dinitrogen acid", "dioxyribose nucleic acid", "deoxyribose nitric acid"],
    ["Science", "What is the approximate speed of light in a vacuum?", "300,000 km per second", "3,000 km per second", "30,000 km per second", "3,000,000 km per second"],
    ["Science", "What is the SI unit of energy?", "the joule", "the watt", "the newton", "the pascal"],
    ["Science", "Which sub-atomic particle has no electric charge?", "the neutron", "the proton", "the electron", "the positron"],
    ["Science", "Which equation is Ohm's law?", "V = IR", "F = ma", "E = mc²", "P = IV"],
    ["Science", "Which organelle is the site of protein synthesis in a cell?", "the ribosome", "the mitochondrion", "the lysosome", "the Golgi apparatus"],
    ["Science", "Which of these is a noble gas?", "helium", "oxygen", "hydrogen", "nitrogen"],
    ["Science", "About what is the pH of the acid in the human stomach?", "2", "7", "9", "12"],
    ["Science", "What type of bond is formed when atoms share electrons?", "a covalent bond", "an ionic bond", "a metallic bond", "a hydrogen bond"],
    ["Science", "Which of these gases is a major greenhouse gas?", "carbon dioxide", "argon", "neon", "helium"],
    ["Science", "Which type of cell division produces two identical cells for growth?", "mitosis", "meiosis", "osmosis", "diffusion"],
    ["Science", "What is the chemical formula of methane?", "CH4", "CO2", "C2H6", "CH3OH"],
    ["Science", "Who proposed the theory of evolution by natural selection?", "Charles Darwin", "Gregor Mendel", "Louis Pasteur", "Isaac Newton"],
    ["Science", "What does the \"half-life\" of a radioactive substance mean?", "the time for half the atoms to decay", "half the time it exists", "the time to double in size", "half its mass at birth"],
    ["Science", "Which blood group is known as the universal donor for red blood cells?", "O negative", "AB positive", "A positive", "B negative"],
    ["Science", "What is the acceleration due to gravity on Earth, approximately?", "9.8 m/s²", "1.6 m/s²", "3.7 m/s²", "24.8 m/s²"],
    ["Science", "What is Avogadro's number, approximately?", "6.02 × 10²³", "6.02 × 10¹²", "3.00 × 10⁸", "9.81 × 10⁻³"],
    ["Science", "Which enzyme in saliva begins the digestion of starch?", "amylase", "pepsin", "lipase", "trypsin"],
    ["Science", "What type of wave is a sound wave?", "longitudinal", "transverse", "electromagnetic", "standing only"],
    ["Science", "Which element has the chemical symbol Fe?", "iron", "fluorine", "lead", "tin"],
    ["Science", "Which part of the brain is mainly responsible for balance and coordination?", "the cerebellum", "the cerebrum", "the medulla", "the hypothalamus"],
    ["Science", "Which gas makes up most of the Sun?", "hydrogen", "helium", "oxygen", "carbon"],
    ["Science", "What is the process of splitting a heavy nucleus into smaller nuclei called?", "nuclear fission", "nuclear fusion", "combustion", "oxidation"],
    ["Science", "What is the atomic number of oxygen?", "8", "6", "16", "2"],
    ["Science", "What is the atomic number of hydrogen?", "1", "2", "0", "8"],
    ["Science", "What is the chemical symbol for tungsten?", "W", "T", "Tu", "Tn"],
    ["Science", "What is the chemical symbol for lead?", "Pb", "Pd", "Le", "L"],
    ["Science", "What is the chemical symbol for mercury?", "Hg", "Me", "Mc", "Mr"],
    ["Science", "What is the most abundant element in the Earth's crust?", "oxygen", "silicon", "iron", "aluminium"],
    ["Science", "Which group of the periodic table contains the alkali metals?", "Group 1", "Group 2", "Group 7", "Group 0"],
    ["Science", "Which group of the periodic table contains the halogens?", "Group 7", "Group 1", "Group 0", "Group 2"],
    ["Science", "What is the name of the horizontal rows of the periodic table?", "periods", "groups", "blocks", "families only"],
    ["Science", "What is the charge of a proton?", "positive", "negative", "neutral", "variable"],
    ["Science", "What is the mass number of an atom?", "the number of protons plus neutrons", "the number of protons only", "the number of electrons only", "the number of neutrons only"],
    ["Science", "What are isotopes?", "atoms of the same element with different numbers of neutrons", "atoms with different numbers of protons", "atoms with different numbers of electrons", "ions of the same element"],
    ["Science", "What type of bond forms between a metal and a non-metal?", "ionic", "covalent", "metallic only", "hydrogen only"],
    ["Science", "What happens to electrons in ionic bonding?", "they are transferred", "they are shared", "they are destroyed", "they stay in the nucleus"],
    ["Science", "What is the chemical formula for sulfuric acid?", "H2SO4", "HCl", "HNO3", "H2CO3"],
    ["Science", "What is the chemical formula for hydrochloric acid?", "HCl", "H2SO4", "HNO3", "NaOH"],
    ["Science", "What is the chemical formula for sodium hydroxide?", "NaOH", "NaCl", "Na2O", "HOH"],
    ["Science", "What is the chemical formula of ammonia?", "NH3", "NH4", "N2H", "NO2"],
    ["Science", "What is the chemical formula of glucose?", "C6H12O6", "C12H22O11", "CH4", "C2H5OH"],
    ["Science", "What is the word equation for photosynthesis?", "carbon dioxide + water → glucose + oxygen", "glucose + oxygen → carbon dioxide + water", "glucose → carbon dioxide + water", "oxygen + water → glucose + carbon dioxide"],
    ["Science", "What is the word equation for aerobic respiration?", "glucose + oxygen → carbon dioxide + water", "carbon dioxide + water → glucose + oxygen", "glucose → lactic acid", "glucose + carbon dioxide → oxygen"],
    ["Science", "Which process in muscles produces lactic acid when oxygen is low?", "anaerobic respiration", "aerobic respiration", "photosynthesis", "digestion"],
    ["Science", "What is the name for a reaction that releases heat to the surroundings?", "exothermic", "endothermic", "reversible", "neutral"],
    ["Science", "What is the name for a reaction that takes in heat from the surroundings?", "endothermic", "exothermic", "combustion", "neutralisation"],
    ["Science", "What is a catalyst?", "a substance that speeds up a reaction without being used up", "a substance that slows a reaction", "a substance that is the main product", "a type of acid"],
    ["Science", "What is an enzyme?", "a biological catalyst", "a type of carbohydrate", "a type of vitamin", "a type of cell"],
    ["Science", "What does the Haber process make?", "ammonia", "sulfuric acid", "ethanol", "chlorine"],
    ["Science", "What is the name of the process of splitting a compound using electricity?", "electrolysis", "distillation", "electrification", "filtration"],
    ["Science", "Which metal is the most reactive of these?", "potassium", "iron", "copper", "gold"],
    ["Science", "Which metal is the least reactive of these?", "gold", "zinc", "sodium", "magnesium"],
    ["Science", "What is produced when a metal reacts with oxygen?", "a metal oxide", "a metal hydroxide", "a salt only", "hydrogen only"],
    ["Science", "What is the name of the hydrocarbons with only single bonds between carbon atoms?", "alkanes", "alkenes", "alkynes", "alcohols"],
    ["Science", "What is the name of the process of separating crude oil into fractions?", "fractional distillation", "filtration", "chromatography", "cracking"],
    ["Science", "What is the SI unit of pressure?", "the pascal", "the newton", "the joule", "the watt"],
    ["Science", "What is the SI unit of charge?", "the coulomb", "the ampere", "the volt", "the farad"],
    ["Science", "What is the equation linking charge, current and time?", "Q = It", "Q = IR", "Q = V/I", "Q = mc"],
    ["Science", "What is the equation for electrical power?", "P = IV", "P = V/I", "P = I/R", "P = mgh"],
    ["Science", "What is the equation for kinetic energy?", "½mv²", "mgh", "mv", "Fd"],
    ["Science", "What is the equation for gravitational potential energy?", "mgh", "½mv²", "Fd", "mc²"],
    ["Science", "What is Hooke's law?", "force is proportional to extension of a spring", "force equals mass times acceleration", "pressure equals force divided by area", "energy is conserved"],
    ["Science", "What does Newton's first law of motion state?", "an object stays at rest or moves at constant velocity unless a force acts on it", "force equals mass times acceleration", "every action has an equal and opposite reaction", "energy cannot be created"],
    ["Science", "What does Newton's third law state?", "every action has an equal and opposite reaction", "force equals mass times acceleration", "objects stay in motion", "energy is conserved"],
    ["Science", "What is momentum?", "mass multiplied by velocity", "mass multiplied by acceleration", "force multiplied by time only", "energy divided by time"],
    ["Science", "What is the difference between speed and velocity?", "velocity has direction as well as size", "speed has direction", "they are the same", "velocity is always faster"],
    ["Science", "Which type of electromagnetic wave has the highest frequency?", "gamma rays", "radio waves", "microwaves", "visible light"],
    ["Science", "Which type of electromagnetic wave has the longest wavelength?", "radio waves", "gamma rays", "X-rays", "ultraviolet"],
    ["Science", "Which electromagnetic waves are used to cook food in a microwave oven?", "microwaves", "radio waves", "infrared", "X-rays"],
    ["Science", "Which electromagnetic waves are used in medical imaging of bones?", "X-rays", "radio waves", "microwaves", "infrared"],
    ["Science", "Which type of radiation can cause sunburn?", "ultraviolet", "infrared", "radio", "microwave"],
    ["Science", "What is the name for the bending of waves around obstacles?", "diffraction", "reflection", "refraction", "absorption"],
    ["Science", "What is the name of the effect where the pitch of a siren changes as it passes you?", "the Doppler effect", "the greenhouse effect", "the photoelectric effect", "the Coriolis effect"],
    ["Science", "What is the name for the type of nuclear reaction that powers the Sun?", "nuclear fusion", "nuclear fission", "radioactive decay", "combustion"],
    ["Science", "Which type of radiation is stopped by a sheet of paper?", "alpha", "beta", "gamma", "X-ray"],
    ["Science", "Which type of radiation is the most penetrating?", "gamma", "alpha", "beta", "visible light"],
    ["Science", "What is the Big Bang theory?", "the theory that the universe began from a very hot dense state", "the theory that stars explode every day", "the theory that Earth is at the centre", "the theory that the Sun formed first"],
    ["Science", "What force holds the nucleus of an atom together?", "the strong nuclear force", "gravity", "friction", "electrostatic repulsion only"],
    ["Science", "What is the red shift of light from distant galaxies evidence for?", "the expansion of the universe", "the shrinking of the universe", "the Earth's rotation", "the Sun's heat"],
    ["Science", "What is a light-year a unit of?", "distance", "time", "speed", "brightness"],
    ["Science", "What is the base pair that adenine always pairs with in DNA?", "thymine", "cytosine", "guanine", "uracil"],
    ["Science", "What are the four bases of DNA?", "adenine, thymine, cytosine and guanine", "adenine, uracil, cytosine and guanine", "alanine, thymine, glycine and cytosine", "adenine, thymine, serine and guanine"],
    ["Science", "What is the shape of a DNA molecule?", "a double helix", "a single strand", "a ring", "a sphere"],
    ["Science", "Who is credited with discovering the structure of DNA in 1953 (with Crick)?", "James Watson", "Gregor Mendel", "Charles Darwin", "Louis Pasteur"],
    ["Science", "Who is known as the father of genetics, for his work with pea plants?", "Gregor Mendel", "Charles Darwin", "James Watson", "Francis Crick"],
    ["Science", "What is a gene?", "a section of DNA that codes for a protein", "a type of cell", "a type of organ", "a part of a chromosome with no function"],
    ["Science", "How many chromosomes are in a normal human body cell?", "46", "23", "44", "48"],
    ["Science", "What is the term for different forms of the same gene?", "alleles", "chromosomes", "mutations", "enzymes"],
    ["Science", "What is an organism with two identical alleles for a gene called?", "homozygous", "heterozygous", "recessive", "mutant"],
    ["Science", "What is meiosis?", "cell division that produces gametes", "cell division that produces identical cells", "a type of respiration", "a type of digestion"],
    ["Science", "What is the name for a cell that can develop into many different cell types?", "a stem cell", "a red blood cell", "a nerve cell", "a gamete"],
    ["Science", "Which hormone is produced by the pancreas to lower blood glucose?", "insulin", "adrenaline", "thyroxine", "oestrogen"],
    ["Science", "What is homeostasis?", "maintaining a stable internal environment", "growth of an organism", "reproduction", "digestion of food"],
    ["Science", "Which part of the brain controls breathing and heart rate?", "the medulla", "the cerebrum", "the cerebellum", "the hypothalamus only"],
    ["Science", "What is the role of antibodies?", "to help destroy pathogens", "to carry oxygen", "to digest food", "to clot blood"],
    ["Science", "What are antibiotics effective against?", "bacteria", "viruses", "fungi only", "all diseases"],
    ["Science", "What is the name of the process by which a species' traits change over generations through survival of the fittest?", "natural selection", "mutation only", "cloning", "inheritance only"],
    ["Maths", "Solve x² - 5x + 6 = 0.", "x = 2 or x = 3", "x = -2 or x = -3", "x = 1 or x = 6", "x = 2 or x = -3"],
    ["Maths", "Solve x² - 9 = 0.", "x = 3 or x = -3", "x = 3 only", "x = 9 or x = -9", "x = 0"],
    ["Maths", "Solve x² + 2x - 8 = 0.", "x = 2 or x = -4", "x = -2 or x = 4", "x = 2 or x = 4", "x = 8 or x = -1"],
    ["Maths", "Expand (x + 3)(x + 2).", "x² + 5x + 6", "x² + 6x + 5", "x² + 5x + 5", "x² + x + 6"],
    ["Maths", "Expand (x - 4)(x + 4).", "x² - 16", "x² + 16", "x² - 8x - 16", "x² - 4x + 16"],
    ["Maths", "Factorise x² + 7x + 12.", "(x + 3)(x + 4)", "(x + 2)(x + 6)", "(x + 1)(x + 12)", "(x - 3)(x - 4)"],
    ["Maths", "What is 5⁰?", "1", "0", "5", "undefined"],
    ["Maths", "What is 2³ × 2⁴?", "2⁷", "2¹²", "4⁷", "2¹"],
    ["Maths", "What is 9^(1/2)?", "3", "4.5", "81", "18"],
    ["Maths", "What is 10⁻²?", "0.01", "-100", "0.1", "-0.01"],
    ["Maths", "A right-angled triangle has shorter sides 6 cm and 8 cm. How long is the hypotenuse?", "10 cm", "14 cm", "12 cm", "9 cm"],
    ["Maths", "A right-angled triangle has hypotenuse 13 cm and one side 5 cm. How long is the other side?", "12 cm", "8 cm", "11 cm", "10 cm"],
    ["Maths", "A ladder 5 m long leans against a wall with its foot 3 m from the wall. How high up the wall does it reach?", "4 m", "2 m", "3 m", "5.8 m"],
    ["Maths", "A fair six-sided dice is rolled. What is the probability of rolling a number greater than 4?", "1/3", "1/6", "1/2", "2/3"],
    ["Maths", "Two fair coins are tossed. What is the probability of getting two heads?", "1/4", "1/2", "1/3", "3/4"],
    ["Maths", "What is sin 30°?", "1/2", "√3/2", "1", "√2/2"],
    ["Maths", "What is cos 60°?", "1/2", "√3/2", "0", "1"],
    ["Maths", "What is the gradient of the line y = 3x - 5?", "3", "-5", "5", "0.3333333333333333"],
    ["Maths", "What is the gradient of the line passing through (1, 2) and (3, 8)?", "3", "2", "6", "4"],
    ["Maths", "Write 45,000 in standard form.", "4.5 × 10⁴", "4.5 × 10³", "45 × 10⁴", "4.5 × 10⁵"],
    ["Maths", "Solve the simultaneous equations x + y = 10 and x - y = 4.", "x = 7, y = 3", "x = 6, y = 4", "x = 8, y = 2", "x = 5, y = 5"],
    ["Maths", "Solve the simultaneous equations 2x + y = 11 and x - y = 1.", "x = 4, y = 3", "x = 3, y = 5", "x = 5, y = 1", "x = 4, y = 4"],
    ["Maths", "What is log₁₀ 1000?", "3", "2", "10", "100"],
    ["Maths", "What is the sum of the interior angles of a hexagon?", "720°", "540°", "360°", "900°"],
    ["Maths", "A sum of £1,000 earns 10% compound interest per year. How much is it worth after 2 years?", "£1,210", "£1,200", "£1,100", "£1,220"],
    ["Maths", "Solve x² - 9x + 20 = 0", "x = 4 or x = 5", "x = 5 or x = 5", "x = 3 or x = 7", "x = -4 or x = -5"],
    ["Maths", "Factorise x² + 12x + 32", "(x + 4)(x + 8)", "x(x + 44)", "(x + 4)(x + 9)", "(x - 4)(x - 8)"],
    ["Maths", "Expand and simplify (x + 3)(x + 7)", "x² + 10x + 21", "x² + 11x + 21", "x² + 31x", "x² + 21x + 10"],
    ["Maths", "Factorise x² - 4", "(x + 2)(x - 2)", "x(x - 4)", "(x + 2)(x + 2)", "(x - 2)(x - 2)"],
    ["Maths", "A right-angled triangle has shorter sides of 30 cm and 40 cm. How long is the hypotenuse?", "50 cm", "47 cm", "46 cm", "48 cm"],
    ["Maths", "In a right-angled triangle the opposite side is 5, the adjacent side is 12 and the hypotenuse is 13. What is tan of the angle?", "5/12", "5/13", "12/13", "12/5"],
    ["Maths", "What is the value of 4^(1/2)?", "2", "16", "8", "1/2"],
    ["Maths", "Write 9,100,000 in standard form.", "9.1 × 10⁶", "9.1 × 10⁷", "9.1 × 10⁵", "91 × 10⁶"],
    ["Maths", "A bag holds 9 red counters and 6 blue counters. One is picked at random. What is the probability it is red?", "3/5", "9/6", "1/15", "2/5"],
    ["Maths", "What is the gradient of the line y = 5x - 9?", "5", "10", "4", "3"],
    ["Maths", "What is the midpoint of (0, -2) and (6, -2)?", "(3, -2)", "(6, -4)", "(4, -2)", "(-2, 3)"],
    ["Maths", "What is the nth term of the sequence 15, 24, 33, 42, ...?", "9n + 6", "n + 9", "10n + 6", "9n + 7"],
    ["Maths", "A value changes from 60 to 90. What is the percentage increase?", "50%", "60%", "30%", "55%"],
    ["Maths", "Solve x + y = 4 and x - y = -2", "x = 1, y = 3", "x = 2, y = 2", "x = 3, y = 1", "x = 1, y = 4"],
    ["Maths", "What is the area of a circle with radius 12 cm, in terms of π?", "144π cm²", "288π cm²", "12π cm²", "24π cm²"],
    ["Maths", "Simplify √72", "6√2", "12", "7√2", "6√3"],
    ["Maths", "What is log₂64?", "6", "11", "12", "5"],
    ["Maths", "What is the size of each exterior angle of a regular polygon with 10 sides?", "36°", "32°", "41°", "31°"],
    ["Maths", "Differentiate 9x⁴ with respect to x.", "36x³", "27x³", "9x³", "36x⁴"],
    ["Maths", "Make b the subject of a = b + c.", "b = a - c", "b = ac", "b = c - a", "b = a + c"],
    ["Maths", "How many real roots does x² + 2x + 5 = 0 have? (Use the discriminant.)", "no real roots", "two distinct real roots", "one repeated real root", "three real roots"],
    ["Maths", "What is the median of 26, 12, 6, 32, 13, 33?", "19.5", "26", "18.5", "20.5"],
    ["Maths", "£600 is invested at 10% compound interest per year. How much is it worth after 2 years?", "£726", "£776", "£720", "£676"],
    ["Maths", "Angles in the same segment of a circle are what?", "equal", "supplementary", "right angles", "double the central angle"],
    ["Maths", "Solve x² - 7x + 10 = 0", "x = 2 or x = 5", "x = 3 or x = 5", "x = 1 or x = 7", "x = 2 or x = 6"],
    ["Maths", "Factorise x² + 17x + 72", "(x + 8)(x + 9)", "(x + 9)(x + 9)", "x(x + 89)", "(x + 8)(x + 10)"],
    ["Maths", "Expand and simplify (x + 4)(x + 6)", "x² + 10x + 24", "x² + 24x + 10", "x² + 10x + 25", "x² + 11x + 24"],
    ["Maths", "Factorise x² - 49", "(x + 7)(x - 7)", "(x - 7)(x - 7)", "(x + 7)(x + 7)", "x(x - 49)"],
    ["Maths", "A right-angled triangle has a hypotenuse of 10 cm and one shorter side of 6 cm. How long is the other shorter side?", "8 cm", "5 cm", "10 cm", "6 cm"],
    ["Maths", "What is the exact value of sin 60°?", "√3/2", "√2/2", "1/2", "1"],
    ["Maths", "Simplify y⁹ × y⁸", "y¹⁷", "y¹⁸", "y⁷²", "y¹"],
    ["Maths", "Write 280 in standard form.", "2.8 × 10²", "2.8 × 10³", "28 × 10²", "2.8 × 10¹"],
    ["Maths", "A bag holds 9 red counters and 5 blue counters. One is picked at random. What is the probability it is red?", "9/14", "1/14", "5/14", "9/5"],
    ["Maths", "Where does the line y = -6x - 1 cross the y-axis (the y-intercept)?", "-1", "-3", "-6", "0"],
    ["Maths", "What is the midpoint of (8, -4) and (-6, 10)?", "(1, 3)", "(3, 1)", "(2, 6)", "(2, 3)"],
    ["Maths", "What is the nth term of the sequence 6, 15, 24, 33, ...?", "9n - 3", "10n - 3", "9n + 3", "9n - 2"],
    ["Maths", "A value changes from 400 to 500. What is the percentage increase?", "25%", "100%", "30%", "35%"],
    ["Maths", "Solve x + y = 11 and x - y = -7", "x = 2, y = 9", "x = 2, y = 10", "x = 9, y = 2", "x = 3, y = 8"],
    ["Maths", "What is the circumference of a circle with radius 12 cm, in terms of π?", "24π cm", "48π cm", "144π cm", "12π cm"],
    ["Maths", "Simplify √5 × √6", "√30", "30", "11", "√11"],
    ["Maths", "What is log₇49?", "2", "7", "0", "4"],
    ["Maths", "What is the size of each exterior angle of a regular polygon with 6 sides?", "60°", "58°", "55°", "120°"],
    ["Maths", "Differentiate 2x⁴ with respect to x.", "8x³", "2x³", "6x³", "8x⁴"],
    ["Maths", "Make r the subject of A = πr².", "r = √(A/π)", "r = √A × π", "r = A/(2π)", "r = A/π"],
    ["Maths", "How many real roots does 2x² + 3x + 1 = 0 have? (Use the discriminant.)", "two distinct real roots", "no real roots", "three real roots", "one repeated real root"],
    ["Maths", "What is the median of 25, 31, 16, 32, 3, 7?", "20.5", "16", "25", "19.5"],
    ["Maths", "£2,000 is invested at 5% compound interest per year. How much is it worth after 2 years?", "£2,205", "£2,255", "£2,200", "£2,155"],
    ["Maths", "Opposite angles of a cyclic quadrilateral add up to what?", "180°", "270°", "90°", "360°"],
    ["Maths", "Solve x² - 13x + 42 = 0", "x = 6 or x = 7", "x = 6 or x = 8", "x = 5 or x = 9", "x = 7 or x = 7"],
    ["Maths", "Factorise x² + 4x + 3", "(x + 1)(x + 3)", "(x + 2)(x + 3)", "(x - 1)(x - 3)", "(x + 1)(x + 4)"],
    ["Maths", "Expand and simplify (x + 4)(x + 9)", "x² + 13x + 36", "x² + 49x", "x² + 36x + 13", "x² + 14x + 36"],
    ["Maths", "Factorise x² - 121", "(x + 11)(x - 11)", "x(x - 121)", "(x + 11)(x + 11)", "(x - 11)(x - 11)"],
    ["Maths", "A right-angled triangle has a hypotenuse of 5 cm and one shorter side of 3 cm. How long is the other shorter side?", "4 cm", "2 cm", "6 cm", "7 cm"],
    ["Maths", "What is the exact value of sin 180°?", "0", "1", "1/2", "-1"],
    ["Maths", "Simplify 5⁹ ÷ 5³", "5⁶", "5⁷", "5¹²", "5²⁷"],
    ["Maths", "Write 9.4 × 10³ as an ordinary number.", "9,400", "94,000", "940", "941"],
    ["Maths", "A bag holds 3 red counters and 9 blue counters. One is picked at random. What is the probability it is red?", "1/4", "3/4", "1/12", "4/13"],
    ["Maths", "Where does the line y = 5x + 12 cross the y-axis (the y-intercept)?", "12", "22", "13", "24"],
    ["Maths", "What is the midpoint of (-8, 4) and (4, 10)?", "(-2, 7)", "(-2, 8)", "(7, -2)", "(-1, 7)"],
    ["Maths", "What is the nth term of the sequence 7, 15, 23, 31, ...?", "8n - 1", "9n - 1", "8n", "n + 8"],
    ["Maths", "After a 50% discount a jacket costs £60. What was the original price?", "£120", "£110", "£130", "£90"],
    ["Maths", "Solve x + y = 9 and x - y = 3", "x = 6, y = 3", "x = 6, y = 4", "x = 3, y = 6", "x = 7, y = 2"],
    ["Maths", "What is the circumference of a circle with radius 3 cm, in terms of π?", "6π cm", "9π cm", "3π cm", "12π cm"],
    ["Maths", "Simplify √3 × √5", "√15", "15", "√8", "8"],
    ["Maths", "What is log₃81?", "4", "14", "8", "6"],
    ["Maths", "What is the size of each interior angle of a regular polygon with 10 sides?", "144°", "145°", "134°", "149°"],
    ["Maths", "Differentiate 9x² with respect to x.", "18x", "18x²", "9x", "11x"],
    ["Maths", "Make x the subject of y = 2x - 7.", "x = (y + 7)/2", "x = y/2 + 7/2 - 7", "x = (y - 7)/2", "x = 2(y + 7)"],
    ["Maths", "How many real roots does x² + 4x + 4 = 0 have? (Use the discriminant.)", "one repeated real root", "no real roots", "three real roots", "two distinct real roots"],
    ["Maths", "What is the median of 25, 11, 37, 32, 28, 19?", "26.5", "25.5", "28", "27.5"],
    ["Maths", "£5,000 is invested at 4% compound interest per year. How much is it worth after 2 years?", "£5,408", "£5,400", "£5,458", "£5,358"],
    ["Maths", "A tangent to a circle meets the radius at what angle?", "90°", "180°", "60°", "45°"],
    ["Maths", "Solve x² - 7x + 12 = 0", "x = 3 or x = 4", "x = 2 or x = 6", "x = -3 or x = -4", "x = 4 or x = 4"],
    ["Maths", "Factorise x² + 6x + 5", "(x + 1)(x + 5)", "(x - 1)(x - 5)", "(x + 1)(x + 6)", "(x + 2)(x + 5)"],
    ["Maths", "Expand and simplify (x + 8)(x + 1)", "x² + 9x + 8", "x² + 8x + 9", "x² + 9x + 9", "x² + 10x + 8"],
    ["Geography", "Which line of latitude lies at about 23.5° North?", "the Tropic of Cancer", "the Tropic of Capricorn", "the Equator", "the Arctic Circle"],
    ["Geography", "What is the largest desert in the world?", "the Antarctic Desert", "the Sahara", "the Arabian Desert", "the Gobi"],
    ["Geography", "What type of tectonic plate boundary is it where plates move apart?", "divergent", "convergent", "transform", "subduction"],
    ["Geography", "What is the capital city of Kazakhstan?", "Astana", "Almaty", "Tashkent", "Bishkek"],
    ["Geography", "Which river flows through the city of Baghdad?", "the Tigris", "the Euphrates", "the Nile", "the Jordan"],
    ["Geography", "What do we call the average weather of a place over about 30 years?", "climate", "weather", "a season", "a forecast"],
    ["Geography", "The \"Ring of Fire\", an area of many volcanoes, surrounds which ocean?", "the Pacific Ocean", "the Atlantic Ocean", "the Indian Ocean", "the Arctic Ocean"],
    ["Geography", "Which is the largest island in the world (not counting continents)?", "Greenland", "Borneo", "Madagascar", "New Guinea"],
    ["Geography", "Which mountain range forms the traditional boundary between Europe and Asia?", "the Ural Mountains", "the Alps", "the Andes", "the Pyrenees"],
    ["Geography", "What is the capital city of New Zealand?", "Wellington", "Auckland", "Christchurch", "Hamilton"],
    ["Geography", "Which rivers form a huge delta in Bangladesh?", "the Ganges and Brahmaputra", "the Indus and Jhelum", "the Mekong and Salween", "the Yangtze and Yellow"],
    ["Geography", "Which is the longest river in Asia?", "the Yangtze", "the Ganges", "the Mekong", "the Indus"],
    ["Geography", "A monsoon is a seasonal change in what?", "wind direction", "tides", "volcanic activity", "plate movement"],
    ["Geography", "Which is the deepest lake in the world?", "Lake Baikal", "Lake Superior", "Lake Victoria", "Lake Tanganyika"],
    ["Geography", "Ulaanbaatar is the capital city of which country?", "Mongolia", "Kazakhstan", "Nepal", "Bhutan"],
    ["Geography", "What does the term \"urbanisation\" describe?", "the growth in the share of people living in towns and cities", "the growth of forests", "the spread of deserts", "the decline of rivers"],
    ["Geography", "Which is the smallest country in the world by area?", "Vatican City", "Monaco", "San Marino", "Malta"],
    ["Geography", "Which canal links the Mediterranean Sea with the Red Sea?", "the Suez Canal", "the Panama Canal", "the Kiel Canal", "the Corinth Canal"],
    ["Geography", "Which warm ocean current helps to keep north-west Europe mild?", "the Gulf Stream (North Atlantic Drift)", "the Humboldt Current", "the Canary Current", "the Labrador Current"],
    ["Geography", "What is the highest mountain in North America?", "Denali", "Mount Whitney", "Mount Logan", "Mount Rainier"],
    ["Geography", "In which country is the city of Cape Town?", "South Africa", "Namibia", "Kenya", "Nigeria"],
    ["Geography", "What is the starting point of a river called?", "its source", "its mouth", "a tributary", "a meander"],
    ["Geography", "Fjords are most closely associated with which country?", "Norway", "Egypt", "Brazil", "India"],
    ["Geography", "Which strait separates Asia from North America?", "the Bering Strait", "the Strait of Gibraltar", "the Strait of Malacca", "the Strait of Hormuz"],
    ["Geography", "The Sahel is a semi-arid region on which side of the Sahara?", "the southern side", "the northern side", "the eastern side", "the western edge only"],
    ["Geography", "What is the capital city of Egypt's southern neighbour, Sudan?", "Khartoum", "Juba", "Cairo", "Addis Ababa"],
    ["Geography", "What is the capital city of Pakistan?", "Islamabad", "Karachi", "Lahore", "Rawalpindi"],
    ["Geography", "What is the capital city of Afghanistan?", "Kabul", "Kandahar", "Herat", "Tehran"],
    ["Geography", "What is the capital city of Myanmar?", "Naypyidaw", "Yangon", "Mandalay", "Bangkok"],
    ["Geography", "What is the capital city of Nepal?", "Kathmandu", "Pokhara", "Thimphu", "Dhaka"],
    ["Geography", "What is the capital city of Ghana?", "Accra", "Kumasi", "Lagos", "Abuja"],
    ["Geography", "What is the capital city of Tanzania?", "Dodoma", "Dar es Salaam", "Arusha", "Nairobi"],
    ["Geography", "What is the capital city of the Canadian province of Quebec?", "Quebec City", "Montreal", "Ottawa", "Toronto"],
    ["Geography", "What is the capital city of Switzerland?", "Bern", "Zurich", "Geneva", "Basel"],
    ["Geography", "What is the capital city of Belgium?", "Brussels", "Antwerp", "Bruges", "Ghent"],
    ["Geography", "What is the capital city of Hungary?", "Budapest", "Debrecen", "Vienna", "Bucharest"],
    ["Geography", "What is the capital city of Romania?", "Bucharest", "Budapest", "Sofia", "Belgrade"],
    ["Geography", "What is the capital city of Croatia?", "Zagreb", "Split", "Dubrovnik", "Ljubljana"],
    ["Geography", "What is the capital city of Georgia (the country)?", "Tbilisi", "Baku", "Yerevan", "Kutaisi"],
    ["Geography", "What is the capital city of Uzbekistan?", "Tashkent", "Samarkand", "Bishkek", "Almaty"],
    ["Geography", "What is the capital city of Bolivia (seat of government)?", "La Paz", "Santa Cruz", "Lima", "Quito"],
    ["Geography", "What is the capital city of Venezuela?", "Caracas", "Maracaibo", "Bogotá", "Quito"],
    ["Geography", "What is the capital city of the Philippines?", "Manila", "Cebu", "Davao", "Jakarta"],
    ["Geography", "What is the capital city of Malaysia?", "Kuala Lumpur", "Penang", "Singapore", "Jakarta"],
    ["Geography", "Which river is the longest in Australia?", "the Murray", "the Darling", "the Yarra", "the Swan"],
    ["Geography", "Which river flows through the city of Prague?", "the Vltava", "the Danube", "the Elbe", "the Oder"],
    ["Geography", "Which river forms much of the border between Germany and Poland?", "the Oder", "the Rhine", "the Elbe", "the Danube"],
    ["Geography", "Which river runs through Kolkata?", "the Hooghly", "the Indus", "the Narmada", "the Godavari"],
    ["Geography", "Which is Pakistan's main river, flowing from the Himalayas to the Arabian Sea?", "the Indus", "the Ganges", "the Brahmaputra", "the Mekong"],
    ["Geography", "Which river flows through Cambodia and Vietnam into the South China Sea?", "the Mekong", "the Irrawaddy", "the Yangtze", "the Salween"],
    ["Geography", "Which river flows through Myanmar from north to south?", "the Irrawaddy", "the Mekong", "the Ganges", "the Yellow River"],
    ["Geography", "Which river is known as China's 'Mother River' and often floods?", "the Yellow River", "the Yangtze", "the Mekong", "the Pearl River"],
    ["Geography", "Which river flows through Switzerland, Germany and the Netherlands?", "the Rhine", "the Rhône", "the Loire", "the Seine"],
    ["Geography", "Which river flows through the Democratic Republic of the Congo and is Africa's deepest?", "the Congo", "the Niger", "the Zambezi", "the Limpopo"],
    ["Geography", "Which waterfall on the Zambezi River is on the border of Zambia and Zimbabwe?", "Victoria Falls", "Niagara Falls", "Iguazu Falls", "Angel Falls"],
    ["Geography", "Which strait separates Europe from Asia in Istanbul?", "the Bosphorus", "the Dardanelles", "the Strait of Hormuz", "the Bering Strait"],
    ["Geography", "Which strait lies between Iran and Oman and carries much of the world's oil?", "the Strait of Hormuz", "the Strait of Malacca", "the Bosphorus", "the Strait of Gibraltar"],
    ["Geography", "Which strait lies between Malaysia and Indonesia and is one of the busiest shipping lanes?", "the Strait of Malacca", "the Strait of Hormuz", "the Bering Strait", "the Strait of Dover"],
    ["Geography", "Which canal links the Atlantic and Pacific Oceans?", "the Panama Canal", "the Suez Canal", "the Kiel Canal", "the Corinth Canal"],
    ["Geography", "Which is the largest desert in Asia?", "the Gobi Desert", "the Arabian Desert", "the Thar Desert", "the Kara-Kum"],
    ["Geography", "Which is the driest non-polar desert in the world, in Chile?", "the Atacama Desert", "the Sahara", "the Namib", "the Kalahari"],
    ["Geography", "Which desert covers much of Namibia's coast?", "the Namib Desert", "the Kalahari Desert", "the Sahara", "the Gobi"],
    ["Geography", "Which is the largest country in South America by area?", "Brazil", "Argentina", "Peru", "Colombia"],
    ["Geography", "Which is the largest country in Africa by area (since 2011)?", "Algeria", "Sudan", "Libya", "Democratic Republic of the Congo"],
    ["Geography", "Which is the largest country in the world by area?", "Russia", "Canada", "China", "the USA"],
    ["Geography", "Which country has the most time zones, including its overseas territories?", "France", "Russia", "the USA", "China"],
    ["Geography", "Which two countries make up the island of Hispaniola?", "Haiti and the Dominican Republic", "Cuba and Jamaica", "Puerto Rico and Cuba", "Haiti and Cuba"],
    ["Geography", "Which sea is bordered by Turkey, Russia, Ukraine and Bulgaria?", "the Black Sea", "the Caspian Sea", "the Red Sea", "the Aegean Sea"],
    ["Geography", "Which sea is shrinking dramatically between Kazakhstan and Uzbekistan?", "the Aral Sea", "the Dead Sea", "the Black Sea", "the Caspian Sea"],
    ["Geography", "Which sea lies between Saudi Arabia and Africa?", "the Red Sea", "the Black Sea", "the Arabian Sea", "the Caspian Sea"],
    ["Geography", "Which gulf lies between Saudi Arabia and Iran?", "the Persian (Arabian) Gulf", "the Gulf of Aden", "the Gulf of Mexico", "the Gulf of Oman"],
    ["Geography", "What is the name of the world's largest coral reef system?", "the Great Barrier Reef", "the Belize Barrier Reef", "the Red Sea Coral Reef", "the Andros Reef"],
    ["Geography", "What is the name for a ring-shaped coral island?", "an atoll", "a fjord", "a delta", "a peninsula"],
    ["Geography", "What is a fjord?", "a long narrow sea inlet carved by a glacier", "a type of sand dune", "a flat river plain", "a river delta"],
    ["Geography", "What is a peninsula?", "land almost surrounded by water", "land completely surrounded by water", "a river island", "a lagoon"],
    ["Geography", "What is the name for the boundary where two tectonic plates move past each other?", "a transform boundary", "a convergent boundary", "a divergent boundary", "a hotspot"],
    ["Geography", "What forms at a convergent boundary where an oceanic plate meets a continental plate?", "a subduction zone", "a rift valley", "a mid-ocean ridge", "a desert"],
    ["Geography", "Which fault runs along California and is a transform boundary?", "the San Andreas Fault", "the Great Rift Valley", "the Mid-Atlantic Ridge", "the Alpine Fault"],
    ["Geography", "What is the East African Rift Valley an example of?", "a divergent plate boundary", "a convergent plate boundary", "a transform plate boundary", "a hotspot only"],
    ["Geography", "What is the Mid-Atlantic Ridge?", "a chain of underwater mountains at a divergent boundary", "a mountain range in Europe", "a coastal cliff", "a river delta"],
    ["Geography", "What type of volcano has gently sloping sides and runny lava, such as in Hawaii?", "a shield volcano", "a composite volcano", "a dormant crater", "a cinder cone only"],
    ["Geography", "Which type of rock is formed from cooled magma underground?", "intrusive igneous", "sedimentary", "metamorphic", "organic"],
    ["Geography", "What is the rock cycle?", "the continuous process by which rocks change from one type to another", "the path of a river", "the movement of the Moon", "the water cycle"],
    ["Geography", "Which type of rock is marble?", "metamorphic", "igneous", "sedimentary", "organic"],
    ["Geography", "Which type of rock is limestone?", "sedimentary", "igneous", "metamorphic", "volcanic"],
    ["Geography", "What causes the seasons on Earth?", "the tilt of the Earth's axis", "the Earth's distance from the Sun", "the Moon's position", "the Sun's brightness changing"],
    ["Geography", "What is the Coriolis effect?", "the deflection of winds due to the Earth's rotation", "the cooling of oceans", "the heating of land", "the rising of warm air"],
    ["Geography", "What is El Niño?", "a periodic warming of the Pacific Ocean affecting weather worldwide", "a type of earthquake", "a type of desert", "a cold winter"],
    ["Geography", "What is the Inter-Tropical Convergence Zone?", "a belt of low pressure near the Equator where trade winds meet", "a type of ocean current", "a mountain range", "a polar region"],
    ["Geography", "What is the term for the layer of the atmosphere closest to the Earth, where weather occurs?", "the troposphere", "the stratosphere", "the mesosphere", "the thermosphere"],
    ["Geography", "In which layer of the atmosphere is the ozone layer?", "the stratosphere", "the troposphere", "the mesosphere", "the exosphere"],
    ["Geography", "Which greenhouse gas is released in large amounts from cattle and rice fields?", "methane", "oxygen", "nitrogen", "argon"],
    ["Geography", "What is the term for people moving from the countryside to cities?", "rural-to-urban migration", "emigration only", "counter-urbanisation", "suburbanisation"],
    ["Geography", "What is the name for a very large city with a population of over 10 million?", "a megacity", "a hamlet", "a conurbation only", "a township"],
    ["Geography", "What does GDP stand for?", "Gross Domestic Product", "General Development Plan", "Global Demographic Percentage", "Gross Domestic Prosperity"],
    ["Geography", "What is the Human Development Index (HDI) a measure of?", "life expectancy, education and income", "only a country's wealth", "only a country's population", "rainfall"],
    ["Geography", "What is the capital city of Azerbaijan?", "Baku", "Tbilisi", "Yerevan", "Tehran"],
    ["Geography", "What is the capital city of Cambodia?", "Phnom Penh", "Siem Reap", "Vientiane", "Hanoi"],
    ["Geography", "What is the capital city of Senegal?", "Dakar", "Bamako", "Accra", "Abidjan"],
    ["Geography", "What is the capital city of Ecuador?", "Quito", "Guayaquil", "Lima", "Bogotá"],
    ["History", "The First World War began after the assassination of whom?", "Archduke Franz Ferdinand", "Kaiser Wilhelm II", "Tsar Nicholas II", "Winston Churchill"],
    ["History", "Which treaty officially ended the First World War with Germany?", "the Treaty of Versailles", "the Treaty of Paris", "the Treaty of Vienna", "the Treaty of Rome"],
    ["History", "In which year was the Russian Revolution that brought the Bolsheviks to power?", "1917", "1905", "1939", "1953"],
    ["History", "Who was the first emperor of a unified China?", "Qin Shi Huang", "Kublai Khan", "Sun Yat-sen", "Mao Zedong"],
    ["History", "Whose improvements to the steam engine helped drive the Industrial Revolution?", "James Watt", "Isaac Newton", "Michael Faraday", "Alexander Fleming"],
    ["History", "Which leader of Germany started the Second World War in 1939?", "Adolf Hitler", "Otto von Bismarck", "Kaiser Wilhelm II", "Erich Honecker"],
    ["History", "Where did the D-Day landings of 1944 take place?", "Normandy", "Dunkirk", "Calais", "Berlin"],
    ["History", "In which year was the Cuban Missile Crisis?", "1962", "1945", "1973", "1989"],
    ["History", "Who gave the \"I Have a Dream\" speech in 1963?", "Martin Luther King Jr.", "Malcolm X", "Rosa Parks", "Barack Obama"],
    ["History", "The League of Nations was set up after which event?", "the First World War", "the Second World War", "the Cold War", "the French Revolution"],
    ["History", "What was the capital city of the Ottoman Empire?", "Constantinople (Istanbul)", "Cairo", "Baghdad", "Athens"],
    ["History", "The Meiji Restoration of 1868 took place in which country?", "Japan", "China", "Korea", "Thailand"],
    ["History", "At which battle was Napoleon finally defeated in 1815?", "Waterloo", "Trafalgar", "Austerlitz", "Borodino"],
    ["History", "In which year was the Berlin Wall built?", "1961", "1945", "1989", "1953"],
    ["History", "Which event began the Second World War in Europe in September 1939?", "Germany invading Poland", "the bombing of Pearl Harbor", "the fall of Paris", "the Battle of Britain"],
    ["History", "The Great Depression began with the stock market crash in which year?", "1929", "1914", "1945", "1957"],
    ["History", "In which year were the first multiracial elections held in South Africa, ending apartheid rule?", "1994", "1976", "1961", "2004"],
    ["History", "Which dynasty built most of the Great Wall of China that survives today?", "the Ming dynasty", "the Han dynasty", "the Tang dynasty", "the Qing dynasty"],
    ["History", "Which British Prime Minister was nicknamed the \"Iron Lady\"?", "Margaret Thatcher", "Theresa May", "Winston Churchill", "Clement Attlee"],
    ["History", "Which king of France was executed in 1793?", "Louis XVI", "Louis XIV", "Napoleon III", "Charles X"],
    ["History", "Which Portuguese explorer reached India by sea in 1498?", "Vasco da Gama", "Ferdinand Magellan", "Christopher Columbus", "Bartolomeu Dias"],
    ["History", "In which year did the Soviet Union dissolve?", "1991", "1985", "1979", "2001"],
    ["History", "At which battle in 1805 was Admiral Nelson killed?", "Trafalgar", "Waterloo", "Jutland", "Hastings"],
    ["History", "In which years was the Spanish Civil War fought?", "1936 to 1939", "1914 to 1918", "1939 to 1945", "1950 to 1953"],
    ["History", "Which period of European history is known for a revival of art and learning, beginning in the 14th century?", "the Renaissance", "the Reformation", "the Enlightenment", "the Dark Ages"],
    ["History", "Which treaty of 1648 ended the Thirty Years' War?", "the Peace of Westphalia", "the Treaty of Versailles", "the Treaty of Utrecht", "the Treaty of Vienna"],
    ["History", "Which Congress of 1814 to 1815 redrew the map of Europe after Napoleon?", "the Congress of Vienna", "the Congress of Berlin", "the Congress of Paris", "the Congress of Verona"],
    ["History", "Who unified Germany as its first Chancellor in 1871?", "Otto von Bismarck", "Kaiser Wilhelm II", "Adolf Hitler", "Frederick the Great"],
    ["History", "Who was the first Prime Minister of the United Kingdom?", "Robert Walpole", "William Pitt the Younger", "Benjamin Disraeli", "Winston Churchill"],
    ["History", "Which Prime Minister's government passed the Great Reform Act of 1832?", "Earl Grey", "Robert Peel", "Benjamin Disraeli", "William Gladstone"],
    ["History", "Which movement in the 1830s and 40s campaigned for votes for working men in Britain?", "the Chartists", "the Luddites", "the Levellers", "the Suffragettes"],
    ["History", "Which British Prime Minister is associated with the repeal of the Corn Laws in 1846?", "Robert Peel", "William Gladstone", "Lord Palmerston", "Benjamin Disraeli"],
    ["History", "Which year did the Irish Potato Famine begin?", "1845", "1798", "1916", "1801"],
    ["History", "What was the Opium War between Britain and China fought over?", "trade in opium and access to Chinese markets", "control of the Suez Canal", "a dispute over Tibet", "control of Hong Kong's oil"],
    ["History", "What was the 1857 Indian Rebellion also known as?", "the Sepoy Mutiny", "the Boxer Rebellion", "the Salt March", "the Quit India Movement"],
    ["History", "Who was Emperor of Japan during the Meiji Restoration of 1868?", "Emperor Meiji", "Emperor Showa", "Emperor Taisho", "Emperor Hirohito"],
    ["History", "What was the Scramble for Africa?", "European powers rapidly colonising Africa in the late 1800s", "a series of African independence wars", "the discovery of gold in South Africa", "an African trade alliance"],
    ["History", "Which conference of 1884 to 1885 set rules for European colonisation of Africa?", "the Berlin Conference", "the Paris Conference", "the Yalta Conference", "the Versailles Conference"],
    ["History", "Who was the leader of the Zulu Kingdom who defeated the British at Isandlwana in 1879?", "Cetshwayo", "Shaka", "Dingane", "Mandela"],
    ["History", "Which battle in 1898 saw Kitchener defeat the Mahdist forces in Sudan?", "Omdurman", "Rorke's Drift", "Isandlwana", "Mafeking"],
    ["History", "What was the Boer War fought between?", "Britain and the Boer republics in South Africa", "France and Germany", "Britain and the Zulu", "Britain and Egypt"],
    ["History", "What was the Boxer Rebellion (1899 to 1901)?", "an uprising in China against foreign influence", "a war in Japan", "a rebellion in India", "a revolt in Korea"],
    ["History", "Which alliance in 1882 joined Germany, Austria-Hungary and Italy?", "the Triple Alliance", "the Triple Entente", "the Axis", "the Warsaw Pact"],
    ["History", "Which battle in 1914 halted the German advance on Paris?", "the Battle of the Marne", "the Battle of the Somme", "the Battle of Verdun", "the Battle of Jutland"],
    ["History", "Which battle in 1916 was the longest of the First World War, between France and Germany?", "Verdun", "the Somme", "Passchendaele", "Gallipoli"],
    ["History", "What was the Gallipoli campaign of 1915 an attempt to do?", "open a sea route to Russia via the Dardanelles", "capture Paris", "invade Germany", "capture Vienna"],
    ["History", "Which US president took America into the First World War in 1917?", "Woodrow Wilson", "Theodore Roosevelt", "Franklin D. Roosevelt", "Herbert Hoover"],
    ["History", "Which telegram in 1917 offered Mexico an alliance with Germany against the US?", "the Zimmermann Telegram", "the Ems Telegram", "the Balfour Declaration", "the Zinoviev Letter"],
    ["History", "What was the Balfour Declaration of 1917?", "a British statement supporting a Jewish homeland in Palestine", "a peace treaty with Germany", "a declaration of war on Turkey", "a plan for Irish independence"],
    ["History", "Which uprising in Dublin in 1916 was against British rule?", "the Easter Rising", "the Peasants' Revolt", "the Chartist rising", "the Jacobite rising"],
    ["History", "What was the General Strike of 1926 in Britain a response to?", "coal miners' pay and conditions", "food rationing", "a world war", "a royal abdication"],
    ["History", "Which dictator led Italy from 1922 to 1943?", "Benito Mussolini", "Francisco Franco", "Adolf Hitler", "Joseph Stalin"],
    ["History", "Which leader ruled Spain after the Civil War from 1939 until 1975?", "Francisco Franco", "Benito Mussolini", "Antonio Salazar", "Miguel Primo de Rivera"],
    ["History", "What was the New Deal?", "Roosevelt's programme to tackle the Great Depression", "a trade agreement after the First World War", "a Cold War alliance", "a plan to rebuild Europe after 1945"],
    ["History", "What was the Marshall Plan?", "US aid to rebuild Western Europe after 1945", "a plan to invade Normandy", "a nuclear treaty", "an alliance with the USSR"],
    ["History", "What was the Berlin Airlift (1948 to 1949)?", "supplying West Berlin by air during a Soviet blockade", "a bombing campaign on Berlin", "an evacuation of children", "a spy operation"],
    ["History", "Which organisation was the Western military alliance formed in 1949?", "NATO", "the Warsaw Pact", "the EU", "SEATO only"],
    ["History", "Which military alliance was the Soviet counterpart to NATO?", "the Warsaw Pact", "the Axis", "the Triple Entente", "the League of Nations"],
    ["History", "Which war divided Korea along the 38th parallel in 1950 to 1953?", "the Korean War", "the Vietnam War", "the Gulf War", "the Suez Crisis"],
    ["History", "What was the Suez Crisis of 1956 about?", "Egypt's nationalisation of the Suez Canal", "a war over Cyprus", "a blockade of Berlin", "a conflict in Hungary"],
    ["History", "Which Egyptian leader nationalised the Suez Canal in 1956?", "Gamal Abdel Nasser", "Anwar Sadat", "Hosni Mubarak", "King Farouk"],
    ["History", "Who became the first Prime Minister of independent India in 1947?", "Jawaharlal Nehru", "Mahatma Gandhi", "Sardar Patel", "Indira Gandhi"],
    ["History", "Which Ghanaian leader led his country to independence in 1957?", "Kwame Nkrumah", "Jomo Kenyatta", "Julius Nyerere", "Nelson Mandela"],
    ["History", "Which Kenyan leader became the first president of independent Kenya in 1964?", "Jomo Kenyatta", "Julius Nyerere", "Kwame Nkrumah", "Daniel arap Moi"],
    ["History", "Which US president's assassination took place in Dallas in 1963?", "John F. Kennedy", "Lyndon B. Johnson", "Abraham Lincoln", "Richard Nixon"],
    ["History", "What was the Watergate scandal?", "a political scandal that led to President Nixon's resignation", "a bank collapse", "a spy ring in Moscow", "a naval battle"],
    ["History", "In which year did Richard Nixon resign as US President?", "1974", "1968", "1980", "1963"],
    ["History", "Which Iranian revolution of 1979 overthrew the Shah?", "the Iranian Revolution", "the Green Revolution", "the Velvet Revolution", "the Orange Revolution"],
    ["History", "Which leader of the Soviet Union introduced glasnost and perestroika?", "Mikhail Gorbachev", "Leonid Brezhnev", "Boris Yeltsin", "Nikita Khrushchev"],
    ["History", "Which Chinese protest in 1989 was crushed by the army in a famous square?", "the Tiananmen Square protests", "the Boxer Rebellion", "the Long March", "the Cultural Revolution"],
    ["History", "What was the Cultural Revolution (1966 to 1976) in China?", "Mao's campaign to enforce communist ideology", "a trade reform", "a war with Japan", "a scientific programme"],
    ["History", "What was the Great Leap Forward?", "Mao's plan to rapidly industrialise China", "a Japanese invasion", "a space programme", "a trade treaty"],
    ["History", "What was the Long March (1934 to 1935)?", "the retreat of Chinese Communist forces", "a march in Washington", "a Soviet army advance", "a Napoleonic campaign"],
    ["History", "Which genocide took place in Rwanda in 1994?", "the killing of Tutsi by Hutu extremists", "the killing of Armenians", "the killing of Herero", "the killing of Bosnians"],
    ["History", "Which genocide of Armenians occurred during the First World War?", "the Armenian Genocide", "the Rwandan Genocide", "the Holodomor", "the Srebrenica massacre"],
    ["History", "What was the Yalta Conference of 1945?", "a meeting of Churchill, Roosevelt and Stalin", "a peace treaty with Japan", "a meeting of NATO", "a trial of Nazi leaders"],
    ["History", "What were the Nuremberg Trials?", "trials of Nazi leaders after the Second World War", "trials of witches", "trials of First World War generals", "trials of Soviet leaders"],
    ["History", "What was the Kindertransport?", "a rescue effort for Jewish children before the Second World War", "a Soviet train network", "a school scheme", "a food ration plan"],
    ["History", "What was the Manhattan Project?", "the US programme to build the atomic bomb", "a Cold War spy operation", "a plan to build skyscrapers", "a space programme"],
    ["History", "Who led the Manhattan Project's scientific work at Los Alamos?", "J. Robert Oppenheimer", "Albert Einstein", "Enrico Fermi", "Niels Bohr"],
    ["History", "Which Allied leader was US President when the atomic bombs were dropped in 1945?", "Harry S. Truman", "Franklin D. Roosevelt", "Dwight Eisenhower", "Herbert Hoover"],
    ["History", "What was the Cuban Missile Crisis about?", "Soviet nuclear missiles in Cuba", "a naval blockade of Berlin", "a coup in Chile", "a war in Panama"],
    ["History", "Who was the leader of Cuba from 1959 to 2008?", "Fidel Castro", "Che Guevara", "Fulgencio Batista", "Raúl Castro only"],
    ["History", "Which organisation was formed in 1957 by the Treaty of Rome?", "the European Economic Community", "NATO", "the United Nations", "the Commonwealth"],
    ["History", "In which year did the UK join the European Economic Community?", "1973", "1957", "1992", "1945"],
    ["History", "In which year did the UK vote to leave the European Union in a referendum?", "2016", "2008", "2012", "2020"],
    ["History", "What was the Good Friday Agreement of 1998?", "a peace deal for Northern Ireland", "a trade deal with the EU", "a treaty with Scotland", "a ceasefire in the Falklands"],
    ["History", "In which year did the Falklands War take place?", "1982", "1973", "1991", "1969"],
    ["History", "Which UK Prime Minister led Britain to victory in the Falklands War?", "Margaret Thatcher", "James Callaghan", "John Major", "Tony Blair"],
    ["History", "In which year did the 9/11 attacks take place in the USA?", "2001", "1999", "2003", "1995"],
    ["History", "Which Roman Emperor ruled from AD 117 to 138 and built a wall in Britain?", "Hadrian", "Trajan", "Augustus", "Nero"],
    ["History", "What was the Edict of Nantes (1598)?", "a decree granting rights to French Protestants", "a peace treaty with Spain", "a law banning slavery", "a tax law"],
    ["History", "Which dynasty ruled Russia from 1613 until 1917?", "the Romanov dynasty", "the Habsburg dynasty", "the Tudor dynasty", "the Bourbon dynasty"],
    ["History", "Which Russian tsar founded St Petersburg in 1703?", "Peter the Great", "Ivan the Terrible", "Nicholas II", "Alexander II"],
    ["History", "Which Mughal emperor was a great patron of art, and built the Taj Mahal?", "Shah Jahan", "Akbar", "Aurangzeb", "Babur"],
    ["History", "Which empire's capital was Tenochtitlan?", "the Aztec Empire", "the Inca Empire", "the Maya civilisation", "the Olmec civilisation"],
    ["History", "Which pharaoh is famous for the temples at Abu Simbel and a reign of about 66 years?", "Ramesses II", "Tutankhamun", "Khufu", "Akhenaten"],
    ["History", "Which Carthaginian general was defeated at the Battle of Zama in 202 BC?", "Hannibal", "Hasdrubal", "Spartacus", "Xerxes"],
    ["History", "Which Persian king was defeated at the Battle of Salamis in 480 BC?", "Xerxes", "Darius I", "Cyrus the Great", "Alexander the Great"],
    ["History", "Which Mongol leader founded the Yuan dynasty in China?", "Kublai Khan", "Genghis Khan", "Timur", "Ogedei Khan"],
];
