import {PuzzleRow} from '../puzzleTypes.ts';

export const AGE_11_TO_13: PuzzleRow[] = [
    ["English", "Which of these is a metaphor?", "\"The classroom was a zoo.\"", "\"She ran like the wind.\"", "\"Buzz!\" went the bee.", "\"Peter Piper picked peppers.\""],
    ["English", "Which phrase uses alliteration?", "\"Sally sells seashells\"", "\"as cold as ice\"", "\"the sun smiled\"", "\"Crash!\""],
    ["English", "Which sentence uses personification?", "\"The wind whispered through the trees.\"", "\"The wind was cold.\"", "\"The wind is a thief.\"", "\"Whoosh!\""],
    ["English", "Which of these words is a preposition?", "under", "quickly", "happy", "and"],
    ["English", "What is the past participle of \"write\"?", "written", "wrote", "writed", "writing"],
    ["English", "What do we call the main character, or hero, of a story?", "the protagonist", "the antagonist", "the narrator", "the editor"],
    ["English", "What is an antagonist?", "a character who opposes the hero", "the main hero", "the person telling the story", "the author"],
    ["English", "Which word is the best synonym for \"enormous\"?", "gigantic", "tiny", "average", "gentle"],
    ["English", "Which sentence is correct?", "It's raining outside.", "Its raining outside.", "Its' raining outside.", "It's' raining outside."],
    ["English", "Which sentence is in the passive voice?", "The window was broken by the ball.", "The ball broke the window.", "Break the window.", "Did the ball break the window?"],
    ["English", "What is a semicolon mainly used for?", "to join two closely related main clauses", "to end a question", "to show a missing letter", "to start a quotation"],
    ["English", "Which word sounds the same as \"knight\"?", "night", "knit", "kite", "nigh"],
    ["English", "Which genre would a story about wizards and dragons belong to?", "fantasy", "biography", "news report", "recipe"],
    ["English", "Which word is spelled correctly?", "definitely", "definately", "definitly", "defanitely"],
    ["English", "What is an acronym?", "a word made from the first letters of other words", "a word that sounds like what it means", "a word with the opposite meaning", "a very long word"],
    ["English", "What is the root word of \"unhappiness\"?", "happy", "un", "ness", "unhappy"],
    ["English", "What is a thesaurus used for?", "finding synonyms and antonyms", "finding maps", "finding recipes", "finding dates"],
    ["English", "What is hyperbole?", "deliberate exaggeration", "a comparison using \"like\"", "a repeated sound", "a rhyme"],
    ["English", "What does the idiom \"it's raining cats and dogs\" mean?", "it is raining very heavily", "animals are falling", "the rain has stopped", "pets are outside"],
    ["English", "What does the idiom \"break a leg\" mean?", "good luck", "hurt yourself", "run away", "stop"],
    ["English", "In \"The ancient castle looked mysterious\", which word is a noun?", "castle", "ancient", "looked", "mysterious"],
    ["English", "Which phrase correctly shows bones belonging to several dogs?", "the dogs' bones", "the dog's bones", "the dogs bones", "the dogs's bones"],
    ["English", "Which of these is a complex sentence?", "Although it was raining, we played outside.", "We played outside.", "It rained.", "Rain!"],
    ["English", "A story told using \"I\" and \"we\" is written in which person?", "first person", "second person", "third person", "fourth person"],
    ["English", "Which poem form has 14 lines?", "a sonnet", "a haiku", "a limerick", "a couplet"],
    ["English", "Which word is an adverb in the sentence 'She quietly closed the door'?", "quietly", "closed", "door", "she"],
    ["English", "Which word is a pronoun in the sentence 'They found their keys'?", "They", "found", "keys", "their keys"],
    ["English", "What is the plural of 'analysis'?", "analyses", "analysises", "analysis's", "analysi"],
    ["English", "What is the plural of 'criterion'?", "criteria", "criterions", "criterias", "criterii"],
    ["English", "What is the plural of 'cactus' (the most common formal form)?", "cacti", "cactuses only", "cactus's", "cactii"],
    ["English", "What is the plural of 'phenomenon'?", "phenomena", "phenomenons", "phenomenas", "phenomenae"],
    ["English", "What is the plural of 'knife'?", "knives", "knifes", "knifs", "knivess"],
    ["English", "What is the plural of 'potato'?", "potatoes", "potatos", "potatoe", "potatties"],
    ["English", "Which word is the correct past participle of 'break'?", "broken", "broke", "breaked", "brokened"],
    ["English", "Which word is the correct past participle of 'choose'?", "chosen", "chose", "choosed", "chosed"],
    ["English", "Which word is the correct past participle of 'drive'?", "driven", "drove", "drived", "drave"],
    ["English", "Which sentence uses the correct form of 'lie'?", "He lay down on the sofa yesterday.", "He laid down on the sofa yesterday.", "He lied down on the sofa yesterday.", "He lain down on the sofa yesterday."],
    ["English", "Which word is a conjunction in 'I was tired, so I went to bed'?", "so", "tired", "bed", "went"],
    ["English", "What is the function of a relative clause?", "to give extra information about a noun", "to ask a question", "to end a sentence", "to give a command"],
    ["English", "Which sentence contains a relative clause?", "The girl who won the race smiled.", "The girl smiled widely.", "The race was long.", "She won and smiled."],
    ["English", "What does a prefix do?", "changes a word's meaning at the start", "changes a word's meaning at the end", "joins two sentences", "adds a full stop"],
    ["English", "Which prefix means 'not' in the word 'impossible'?", "im-", "pos-", "-ible", "sib-"],
    ["English", "What does the suffix '-less' mean, as in 'hopeless'?", "without", "full of", "again", "before"],
    ["English", "What does the prefix 'pre-' mean, as in 'prehistoric'?", "before", "after", "not", "again"],
    ["English", "What does the prefix 're-' mean, as in 'rewrite'?", "again", "before", "not", "against"],
    ["English", "What does the prefix 'anti-' mean, as in 'anticlockwise'?", "against", "before", "again", "with"],
    ["English", "What does the prefix 'sub-' mean, as in 'submarine'?", "under", "over", "across", "between"],
    ["English", "Which word is an example of onomatopoeia?", "crash", "happy", "tall", "table"],
    ["English", "Which phrase is an example of a simile?", "as brave as a lion", "the lion of the class", "brave lion", "lion's bravery"],
    ["English", "Which of these is an example of personification?", "The sun smiled down on us.", "The sun is hot.", "The sun is like a ball of fire.", "The sun is far away."],
    ["English", "Which of these is an example of a metaphor?", "Life is a rollercoaster.", "Life is like a rollercoaster.", "Life is exciting.", "Life moves quickly."],
    ["English", "What does the idiom 'a piece of cake' mean?", "something very easy", "something delicious", "something small", "something sweet to eat"],
    ["English", "What does the idiom 'under the weather' mean?", "feeling unwell", "standing in the rain", "being very cold", "being outside"],
    ["English", "What does the idiom 'let the cat out of the bag' mean?", "reveal a secret", "free a pet", "lose something", "make a mistake"],
    ["English", "What does the idiom 'once in a blue moon' mean?", "very rarely", "every night", "often", "at the weekend"],
    ["English", "What does the idiom 'spill the beans' mean?", "give away a secret", "drop some food", "cook a meal", "make a mess"],
    ["English", "What does the idiom 'bite the bullet' mean?", "face something unpleasant bravely", "eat quickly", "shoot a gun", "lose a tooth"],
    ["English", "What does the proverb 'Don't count your chickens before they hatch' mean?", "don't rely on something before it happens", "don't keep chickens", "chickens are valuable", "count carefully"],
    ["English", "What does the proverb 'A stitch in time saves nine' mean?", "fixing a problem early prevents bigger ones", "sewing is useful", "nine stitches are best", "hurry up and stitch"],
    ["English", "Which word is closest in meaning to 'reluctant'?", "unwilling", "eager", "delighted", "thrilled"],
    ["English", "Which word is closest in meaning to 'abundant'?", "plentiful", "scarce", "tiny", "empty"],
    ["English", "Which word is closest in meaning to 'fragile'?", "delicate", "sturdy", "heavy", "strong"],
    ["English", "Which word is closest in meaning to 'hesitate'?", "pause", "rush", "leap", "hurry"],
    ["English", "Which word is closest in meaning to 'ancient'?", "very old", "brand new", "fashionable", "small"],
    ["English", "Which word is the opposite of 'transparent'?", "opaque", "clear", "thin", "bright"],
    ["English", "Which word is the opposite of 'expand'?", "contract", "grow", "stretch", "increase"],
    ["English", "Which word is the opposite of 'optimist'?", "pessimist", "realist", "idealist", "dreamer"],
    ["English", "Which word is the opposite of 'permanent'?", "temporary", "lasting", "fixed", "eternal"],
    ["English", "Which word is spelled correctly?", "occurrence", "occurence", "ocurrence", "occurrance"],
    ["English", "Which word is spelled correctly?", "accommodation", "accomodation", "acommodation", "accommodasion"],
    ["English", "Which word is spelled correctly?", "embarrass", "embarass", "embarras", "embarrase"],
    ["English", "Which word is spelled correctly?", "conscience", "consience", "conscence", "consciense"],
    ["English", "Which word is spelled correctly?", "guarantee", "garantee", "guarentee", "gaurantee"],
    ["English", "Which word is spelled correctly?", "privilege", "priviledge", "privelege", "privilage"],
    ["English", "Which word is spelled correctly?", "rhythm", "rythm", "rhythem", "rhytm"],
    ["English", "Which word is spelled correctly?", "unnecessary", "unecessary", "unnecesary", "unneccessary"],
    ["English", "Which word is spelled correctly?", "maintenance", "maintainance", "maintenence", "maintanence"],
    ["English", "Which word is spelled correctly?", "parliament", "parlament", "parliment", "parlimant"],
    ["English", "Which sentence uses 'their', 'there' and 'they're' correctly?", "They're going to put their bags over there.", "Their going to put they're bags over there.", "There going to put their bags over they're.", "They're going to put there bags over their."],
    ["English", "Which sentence uses 'affect' and 'effect' correctly?", "The weather will affect the effect of the party.", "The weather will effect the affect of the party.", "The weather will affect the affect of the party.", "The weather will effect the effect of the party."],
    ["English", "Which sentence uses 'who's' correctly?", "Who's coming to the party?", "Who's bag is this?", "Who's the owner of that bag's?", "Whos' coming to the party?"],
    ["English", "Which sentence uses 'its' correctly?", "The cat licked its paw.", "The cat licked it's paw.", "The cat licked its' paw.", "The cat licked its's paw."],
    ["English", "Which is the correct use of a colon?", "You will need: paper, scissors and glue.", "You will: need paper, scissors and glue.", "You will need paper: scissors, and glue.", "You: will need paper, scissors and glue."],
    ["English", "What is the main job of a hyphen in 'well-known author'?", "to join words together", "to end a sentence", "to show possession", "to show a question"],
    ["English", "What do we call the voice used in 'The cake was eaten by the children'?", "passive", "active", "future", "imperative"],
    ["English", "Which sentence is in the active voice?", "The children ate the cake.", "The cake was eaten by the children.", "The cake was eaten.", "The cake had been eaten by them."],
    ["English", "Which word is a modal verb?", "could", "jumped", "quickly", "blue"],
    ["English", "Which sentence is in the future tense?", "I will visit my gran tomorrow.", "I visited my gran yesterday.", "I visit my gran every week.", "I am visiting my gran now."],
    ["English", "Which sentence is a command (imperative)?", "Close the door.", "The door is closed.", "Is the door closed?", "Did you close the door?"],
    ["English", "Which sentence is a question?", "Where did you put the keys?", "Put the keys on the table.", "The keys are on the table.", "What lovely keys these are."],
    ["English", "What is the name for the central idea or message of a text?", "theme", "plot", "setting", "tone"],
    ["English", "What is the setting of a story?", "where and when it takes place", "who the author is", "how it ends", "the main character's name"],
    ["English", "What do we call the series of events in a story?", "the plot", "the theme", "the setting", "the genre"],
    ["English", "What is a narrator?", "the voice telling the story", "the person who prints a book", "the main hero", "the illustrator"],
    ["English", "A play is written mainly in which form?", "dialogue", "paragraphs of description only", "a list", "a diary"],
    ["English", "What are stage directions in a play script?", "instructions for actors and the stage", "the actors' names", "the audience's comments", "the title page"],
    ["English", "Which of these is a famous Shakespeare tragedy?", "Macbeth", "Twelfth Night", "As You Like It", "The Tempest"],
    ["English", "Which of these is a famous Shakespeare comedy?", "A Midsummer Night's Dream", "Hamlet", "Othello", "King Lear"],
    ["English", "Who wrote 'Oliver Twist'?", "Charles Dickens", "Jane Austen", "Mark Twain", "Thomas Hardy"],
    ["English", "Who wrote 'The Hobbit'?", "J.R.R. Tolkien", "C.S. Lewis", "Roald Dahl", "J.K. Rowling"],
    ["Science", "What is the chemical formula for water?", "H2O", "CO2", "O2", "NaCl"],
    ["Science", "Which gas makes up most of the air we breathe?", "nitrogen", "oxygen", "carbon dioxide", "hydrogen"],
    ["Science", "Which part of a cell is known as its \"powerhouse\"?", "the mitochondria", "the nucleus", "the ribosome", "the membrane"],
    ["Science", "What is the unit of force?", "the newton", "the joule", "the watt", "the volt"],
    ["Science", "What is the chemical symbol for gold?", "Au", "Ag", "Go", "Gd"],
    ["Science", "What is the pH of a neutral substance such as pure water?", "7", "0", "14", "1"],
    ["Science", "Which organs filter the blood to make urine?", "the kidneys", "the liver", "the lungs", "the heart"],
    ["Science", "What do we call a liquid turning into a gas?", "evaporation", "condensation", "freezing", "melting"],
    ["Science", "Which planet is best known for its rings?", "Saturn", "Mars", "Mercury", "Venus"],
    ["Science", "What is found at the centre of an atom?", "the nucleus", "an electron", "a cell", "a molecule"],
    ["Science", "Which gas do humans breathe out?", "carbon dioxide", "oxygen", "helium", "hydrogen"],
    ["Science", "What is the green pigment in plants called?", "chlorophyll", "haemoglobin", "melanin", "keratin"],
    ["Science", "Which particles have a negative charge?", "electrons", "protons", "neutrons", "nuclei"],
    ["Science", "Which of these is a pure element?", "oxygen", "water", "salt", "air"],
    ["Science", "What is the unit of electric current?", "the ampere (amp)", "the volt", "the ohm", "the watt"],
    ["Science", "Which blood cells carry oxygen around the body?", "red blood cells", "white blood cells", "platelets", "plasma"],
    ["Science", "Which type of rock is formed from cooled lava?", "igneous", "sedimentary", "metamorphic", "fossil"],
    ["Science", "Which is the closest star to Earth?", "the Sun", "Proxima Centauri", "Sirius", "Polaris"],
    ["Science", "What is the name for water loss from a plant's leaves?", "transpiration", "respiration", "digestion", "germination"],
    ["Science", "Which part of the eye changes size to control how much light enters?", "the iris", "the cornea", "the retina", "the optic nerve"],
    ["Science", "What is the chemical formula of table salt?", "NaCl", "KCl", "NaOH", "HCl"],
    ["Science", "What do we call the tendency of an object to resist a change in its motion?", "inertia", "gravity", "friction", "magnetism"],
    ["Science", "What is the pH of an acid?", "less than 7", "exactly 7", "more than 7", "exactly 14"],
    ["Science", "What is the hot liquid rock beneath the Earth's surface called?", "magma", "granite", "basalt", "limestone"],
    ["Science", "What type of energy does a moving object have?", "kinetic energy", "potential energy", "chemical energy", "nuclear energy"],
    ["Science", "What is the chemical symbol for sodium?", "Na", "So", "S", "Sd"],
    ["Science", "What is the chemical symbol for potassium?", "K", "P", "Po", "Pt"],
    ["Science", "What is the chemical symbol for iron?", "Fe", "Ir", "I", "In"],
    ["Science", "What is the chemical symbol for silver?", "Ag", "Si", "Sr", "S"],
    ["Science", "What is the chemical symbol for helium?", "He", "H", "Hl", "Hm"],
    ["Science", "What is the chemical symbol for carbon?", "C", "Ca", "Cb", "Co"],
    ["Science", "What is the chemical symbol for oxygen?", "O", "Ox", "Og", "Om"],
    ["Science", "How many protons does a carbon atom have?", "6", "12", "4", "8"],
    ["Science", "What is the chemical formula for carbon dioxide?", "CO2", "CO", "C2O", "O2C"],
    ["Science", "What is the chemical formula for hydrogen gas?", "H2", "H", "H2O", "HO"],
    ["Science", "What is the name for a substance made of two or more different elements chemically joined?", "a compound", "a mixture", "an atom", "a solution"],
    ["Science", "What do we call two or more substances mixed but not chemically joined?", "a mixture", "a compound", "an element", "an atom"],
    ["Science", "Which method would you use to separate salt from salty water?", "evaporation", "filtration", "magnetism", "sieving"],
    ["Science", "Which method would you use to separate sand from water?", "filtration", "evaporation", "magnetism", "distillation"],
    ["Science", "Which method separates iron filings from sand?", "using a magnet", "filtration", "evaporation", "chromatography"],
    ["Science", "What is the name of the method used to separate colours in an ink?", "chromatography", "distillation", "filtration", "evaporation"],
    ["Science", "What is the name of the process used to separate pure water from salt water by boiling and cooling?", "distillation", "filtration", "chromatography", "melting"],
    ["Science", "What is the pH of a strong alkali?", "about 13 or 14", "about 1", "about 7", "about 4"],
    ["Science", "Which of these is an acid?", "lemon juice", "soap", "bleach", "baking soda"],
    ["Science", "Which indicator turns red in acid?", "litmus", "water", "salt", "sugar"],
    ["Science", "What is produced when an acid reacts with an alkali?", "a salt and water", "only hydrogen", "only oxygen", "a metal"],
    ["Science", "Which gas is given off when an acid reacts with a metal like zinc?", "hydrogen", "oxygen", "carbon dioxide", "nitrogen"],
    ["Science", "Which gas turns limewater cloudy?", "carbon dioxide", "oxygen", "hydrogen", "nitrogen"],
    ["Science", "Which gas relights a glowing splint?", "oxygen", "hydrogen", "carbon dioxide", "helium"],
    ["Science", "What is rusting?", "iron reacting with oxygen and water", "iron melting", "iron burning in air", "iron being magnetised"],
    ["Science", "What is needed for fire?", "fuel, oxygen and heat", "water, light and sound", "wind, cold and fuel", "carbon dioxide only"],
    ["Science", "Which of these is a fossil fuel?", "coal", "wood", "wind", "sunlight"],
    ["Science", "Which of these is a renewable energy source?", "wind", "coal", "oil", "natural gas"],
    ["Science", "What is the main gas in the Earth's atmosphere?", "nitrogen", "oxygen", "carbon dioxide", "argon"],
    ["Science", "What percentage of the air is roughly oxygen?", "about 21%", "about 78%", "about 50%", "about 1%"],
    ["Science", "What is the unit of power?", "the watt", "the joule", "the newton", "the volt"],
    ["Science", "What is the unit of potential difference (voltage)?", "the volt", "the ampere", "the ohm", "the watt"],
    ["Science", "What is the unit of electrical resistance?", "the ohm", "the volt", "the watt", "the ampere"],
    ["Science", "Which type of circuit has only one path for the current?", "a series circuit", "a parallel circuit", "an open circuit only", "a short circuit only"],
    ["Science", "What happens to bulbs in a series circuit if one bulb breaks?", "they all go out", "only that bulb goes out", "they get brighter", "they stay the same"],
    ["Science", "What is the speed of sound in air, approximately?", "340 m/s", "3,000 m/s", "30 m/s", "300,000 km/s"],
    ["Science", "What is the speed of light, approximately?", "300,000 km/s", "340 m/s", "30,000 km/s", "3,000 km/s"],
    ["Science", "What is the unit of frequency?", "the hertz", "the decibel", "the newton", "the watt"],
    ["Science", "What unit is used to measure the loudness of sound?", "the decibel", "the hertz", "the newton", "the joule"],
    ["Science", "What is the bending of light as it passes from air into water called?", "refraction", "reflection", "absorption", "diffraction only"],
    ["Science", "What are the colours of the visible spectrum in order from red?", "red, orange, yellow, green, blue, indigo, violet", "red, blue, yellow, green, orange, indigo, violet", "violet, red, orange, yellow, green, blue, indigo", "green, blue, red, orange, yellow, violet, indigo"],
    ["Science", "What type of lens is thicker in the middle and brings light together?", "a convex lens", "a concave lens", "a flat lens", "a prism"],
    ["Science", "What is the formula for speed?", "distance divided by time", "time divided by distance", "distance times time", "mass times time"],
    ["Science", "What is the formula for density?", "mass divided by volume", "volume divided by mass", "mass times volume", "force divided by area"],
    ["Science", "What is the formula for pressure?", "force divided by area", "force times area", "area divided by force", "mass divided by area"],
    ["Science", "What is the name of the force that keeps planets in orbit around the Sun?", "gravity", "friction", "magnetism", "air resistance"],
    ["Science", "What is the difference between mass and weight?", "mass is the amount of matter, weight is the pull of gravity", "mass is the pull of gravity, weight is the amount of matter", "they are the same", "mass is measured in newtons"],
    ["Science", "What is the unit of mass in science?", "the kilogram", "the newton", "the litre", "the metre"],
    ["Science", "What is the term for energy stored in a stretched spring?", "elastic potential energy", "kinetic energy", "thermal energy", "sound energy"],
    ["Science", "What type of energy does a ball held high above the ground have?", "gravitational potential energy", "kinetic energy", "chemical energy", "sound energy"],
    ["Science", "What is the Law of Conservation of Energy?", "energy cannot be created or destroyed", "energy is always lost", "energy is always created", "energy turns into mass only"],
    ["Science", "What are the three methods of heat transfer?", "conduction, convection and radiation", "evaporation, condensation and boiling", "reflection, refraction and diffraction", "melting, freezing and boiling"],
    ["Science", "How does heat from the Sun reach the Earth?", "by radiation", "by conduction", "by convection", "by evaporation"],
    ["Science", "What are the basic units of life called?", "cells", "atoms", "organs", "molecules"],
    ["Science", "Which part of a cell controls its activities and contains DNA?", "the nucleus", "the cell wall", "the vacuole", "the ribosome"],
    ["Science", "Which part of a plant cell gives it a rigid shape?", "the cell wall", "the nucleus", "the cytoplasm", "the cell membrane only"],
    ["Science", "Where does photosynthesis take place in a plant cell?", "in chloroplasts", "in the nucleus", "in the cell wall", "in the vacuole"],
    ["Science", "What is the name of the jelly-like substance in a cell where reactions take place?", "cytoplasm", "the nucleus", "the membrane", "the vacuole"],
    ["Science", "Which of these is part of the circulatory system?", "the heart", "the lungs", "the stomach", "the brain"],
    ["Science", "Which blood vessels carry blood back to the heart?", "veins", "arteries", "capillaries", "tubes"],
    ["Science", "What is the job of white blood cells?", "to fight infection", "to carry oxygen", "to clot blood only", "to carry food"],
    ["Science", "What is the job of the small intestine?", "to absorb nutrients from food", "to pump blood", "to filter blood", "to store bile only"],
    ["Science", "Which organ produces bile?", "the liver", "the stomach", "the pancreas", "the kidney"],
    ["Science", "What is the process by which plants lose water through leaves?", "transpiration", "photosynthesis", "germination", "respiration"],
    ["Science", "What is the name for the process cells use to release energy from glucose?", "respiration", "photosynthesis", "digestion", "pollination"],
    ["Science", "What is the first stage of a seed growing into a plant?", "germination", "pollination", "fertilisation", "dispersal"],
    ["Science", "Which of these is a way that seeds are dispersed?", "by the wind", "by the sunlight only", "by the roots", "by the petals"],
    ["Science", "Which scientist is famous for the theory of evolution by natural selection?", "Charles Darwin", "Isaac Newton", "Albert Einstein", "Louis Pasteur"],
    ["Science", "Which scientist discovered penicillin?", "Alexander Fleming", "Marie Curie", "Louis Pasteur", "Edward Jenner"],
    ["Science", "Who developed the first vaccine, for smallpox?", "Edward Jenner", "Alexander Fleming", "Joseph Lister", "Marie Curie"],
    ["Science", "What is the name of the force that pushes up on objects in water?", "upthrust", "friction", "gravity", "tension"],
    ["Science", "What is the name for a group of living things that can breed together?", "a species", "a habitat", "an ecosystem", "a cell"],
    ["Science", "What is the study of living things called?", "biology", "chemistry", "physics", "geology"],
    ["Science", "What is the study of the Earth's rocks called?", "geology", "biology", "astronomy", "meteorology"],
    ["Science", "What is the study of stars and planets called?", "astronomy", "geology", "meteorology", "botany"],
    ["Maths", "What is 10% of 250?", "25", "50", "225", "19"],
    ["Maths", "What is 25% of 80?", "20", "40", "60", "22"],
    ["Maths", "What is 20% of 150?", "30", "60", "120", "20"],
    ["Maths", "What is 15% of 60?", "9", "18", "51", "14"],
    ["Maths", "What is -3 + 8?", "5", "7", "3", "-5"],
    ["Maths", "What is -7 + 4?", "-3", "-1", "-5", "3"],
    ["Maths", "What is 5 + -9?", "-4", "-2", "-6", "4"],
    ["Maths", "What is the area of a rectangle 12 cm by 7 cm?", "84 cm²", "38 cm²", "96 cm²", "77 cm²"],
    ["Maths", "What is the area of a rectangle 15 cm by 8 cm?", "120 cm²", "46 cm²", "135 cm²", "112 cm²"],
    ["Maths", "What is the area of a rectangle 9 cm by 13 cm?", "117 cm²", "44 cm²", "126 cm²", "104 cm²"],
    ["Maths", "Solve for x: 5x + 2 = 47", "9", "11", "10", "3"],
    ["Maths", "Solve for x: 2x + 8 = 24", "8", "16", "9", "4"],
    ["Maths", "Solve for x: 2x + 2 = 18", "8", "10", "9", "3"],
    ["Maths", "Solve for x: 6x + 13 = 37", "4", "17", "5", "1"],
    ["Maths", "What is the square root of 49?", "7", "8", "6", "14"],
    ["Maths", "What is the square root of 81?", "9", "10", "8", "18"],
    ["Maths", "What is the square root of 144?", "12", "13", "11", "24"],
    ["Maths", "What is the mean of 4, 8, 6, 10 and 12?", "8", "7", "9", "10"],
    ["Maths", "What is the mean of 3, 7, 9 and 5?", "6", "5", "7", "8"],
    ["Maths", "What is the median of 3, 9, 4, 7 and 12?", "7", "4", "9", "6"],
    ["Maths", "Two angles in a triangle are 50° and 60°. What is the third angle?", "70°", "80°", "60°", "90°"],
    ["Maths", "The angles on a straight line add up to what?", "180°", "90°", "360°", "270°"],
    ["Maths", "Which of these is a prime number?", "29", "27", "21", "33"],
    ["Maths", "Share £60 in the ratio 1 : 2. What is the larger share?", "£40", "£30", "£20", "£45"],
    ["Maths", "Simplify the ratio 12 : 18.", "2 : 3", "3 : 4", "4 : 5", "1 : 2"],
    ["Maths", "What is -5 + 5?", "0", "-1", "3", "1"],
    ["Maths", "What is 2 × 9?", "18", "13", "17", "23"],
    ["Maths", "What is 10% of 500?", "50", "55", "46", "49"],
    ["Maths", "What is 1/3 + 1/6?", "1/2", "2/9", "7/12", "5/12"],
    ["Maths", "Simplify the fraction 9/12.", "3/4", "3/5", "4/5", "4/4"],
    ["Maths", "Solve x + 13 = 17", "4", "2", "1", "9"],
    ["Maths", "Solve 3x + 6 = 42", "12", "24", "10", "13"],
    ["Maths", "If a = 2, what is the value of 3a + 4?", "10", "9", "15", "5"],
    ["Maths", "Simplify 4x + 6x", "10x", "10x²", "2x", "24x"],
    ["Maths", "Share £50 in the ratio 1:4. What is the larger share?", "£40", "£44", "£42", "£38"],
    ["Maths", "What is the area of a triangle with base 16 cm and height 6 cm?", "48 cm²", "53 cm²", "49 cm²", "96 cm²"],
    ["Maths", "Two angles of a triangle are 70° and 31°. What is the third angle?", "79°", "158°", "80°", "83°"],
    ["Maths", "What is the square root of 121?", "11", "21", "7", "12"],
    ["Maths", "Which of these is NOT a prime number?", "4", "29", "13", "19"],
    ["Maths", "What is the highest common factor (HCF) of 9 and 12?", "3", "5", "6", "4"],
    ["Maths", "What is the median of 26, 6, 23, 14, 18?", "18", "14", "17", "16"],
    ["Maths", "What is 5 + 6 × 8?", "53", "54", "43", "51"],
    ["Maths", "What is 3.4 × 8?", "27.2", "28.2", "272.0", "27.7"],
    ["Maths", "How many grams are there in 1.5 kilograms?", "1,500", "2,000", "150", "15,000"],
    ["Maths", "A train travels at 60 km/h for 3 hours. How far does it travel?", "180 km", "183 km", "179 km", "184 km"],
    ["Maths", "The nth term of a sequence is 6n + 3. What is the 7th term?", "45", "50", "41", "49"],
    ["Maths", "What is the volume of a cuboid measuring 6 cm by 8 cm by 7 cm?", "336 cm³", "341 cm³", "333 cm³", "337 cm³"],
    ["Maths", "What is the sum of the interior angles of a nonagon?", "1,260°", "1,256°", "1,270°", "1,258°"],
    ["Maths", "What is 1/5 as a decimal?", "0.2", "0.45", "0.4", "0.05"],
    ["Maths", "What is -5 - 9?", "-14", "-16", "-17", "-28"],
    ["Maths", "What is 3 × 6?", "18", "16", "23", "19"],
    ["Maths", "What is 5% of 120?", "6", "9", "12", "1"],
    ["Maths", "What is 1/6 + 1/4?", "5/12", "1/3", "2/10", "31/60"],
    ["Maths", "Simplify the fraction 20/30.", "2/3", "3/3", "3/4", "2/4"],
    ["Maths", "Solve x + 7 = 16", "9", "7", "19", "13"],
    ["Maths", "Solve 4x + 11 = 19", "2", "12", "0", "3"],
    ["Maths", "If a = 4, what is the value of 6a + 8?", "32", "36", "29", "30"],
    ["Maths", "Simplify 8x + 9x", "17x", "1x", "17x²", "72x"],
    ["Maths", "Share £100 in the ratio 2:3. What is the larger share?", "£60", "£64", "£50", "£70"],
    ["Maths", "What is the area of a triangle with base 4 cm and height 8 cm?", "16 cm²", "26 cm²", "21 cm²", "13 cm²"],
    ["Maths", "Two angles of a triangle are 72° and 62°. What is the third angle?", "46°", "36°", "49°", "50°"],
    ["Maths", "What is 20²?", "400", "396", "395", "402"],
    ["Maths", "What is the lowest common multiple (LCM) of 18 and 27?", "54", "486", "63", "45"],
    ["Maths", "What is the range of 28, 14, 7, 16, 17?", "21", "17", "26", "16"],
    ["Maths", "What is (7 + 7) × 7?", "98", "93", "101", "102"],
    ["Maths", "What is 4.2 × 3?", "12.6", "13.1", "13.6", "126.0"],
    ["Maths", "How many millilitres are there in 1.5 litres?", "1,500", "2,000", "150", "15,000"],
    ["Maths", "A train travels at 80 km/h for 5 hours. How far does it travel?", "400 km", "397 km", "390 km", "401 km"],
    ["Maths", "The nth term of a sequence is 2n + 8. What is the 7th term?", "22", "32", "24", "19"],
    ["Maths", "What is the volume of a cuboid measuring 5 cm by 5 cm by 5 cm?", "125 cm³", "135 cm³", "121 cm³", "128 cm³"],
    ["Maths", "What is the sum of the interior angles of a pentagon?", "540°", "550°", "541°", "545°"],
    ["Maths", "What is 9/10 as a percentage?", "90%", "95%", "85%", "180%"],
    ["Maths", "What is -4 - 7?", "-11", "-12", "-9", "-15"],
    ["Maths", "What is 9 × 5?", "45", "35", "43", "55"],
    ["Maths", "What is 30% of 60?", "18", "22", "15", "16"],
    ["Maths", "What is 1/2 + 1/4?", "3/4", "2/6", "2/3", "17/20"],
    ["Maths", "Simplify the fraction 14/21.", "2/3", "2/4", "3/4", "4/7"],
    ["Maths", "Solve 2x = 16", "8", "18", "9", "10"],
    ["Maths", "Solve 2x + 11 = 17", "3", "1", "6", "4"],
    ["Maths", "If a = 9, what is the value of 3a + 9?", "36", "34", "39", "26"],
    ["Maths", "Simplify 6x + 2x", "8x", "4x", "8x²", "12x"],
    ["Maths", "Share £35 in the ratio 4:1. What is the larger share?", "£28", "£32", "£29", "£27"],
    ["Maths", "What is the area of a triangle with base 14 cm and height 7 cm?", "49 cm²", "59 cm²", "98 cm²", "54 cm²"],
    ["Maths", "Two angles of a triangle are 74° and 39°. What is the third angle?", "67°", "57°", "65°", "68°"],
    ["Maths", "What is the square root of 225?", "15", "18", "14", "17"],
    ["Maths", "What is the highest common factor (HCF) of 18 and 27?", "9", "11", "10", "18"],
    ["Maths", "What is the median of 2, 22, 17, 29, 9?", "17", "21", "13", "27"],
    ["Maths", "What is 4 + 6 × 7?", "46", "36", "47", "42"],
    ["Maths", "What is 0.6 × 7?", "4.2", "3.2", "4.7", "5.2"],
    ["Maths", "How many centimetres are there in 3 metres?", "300", "30", "350", "3,000"],
    ["Maths", "A train travels at 30 km/h for 6 hours. How far does it travel?", "180 km", "177 km", "190 km", "184 km"],
    ["Maths", "The nth term of a sequence is 2n + 6. What is the 6th term?", "18", "28", "14", "13"],
    ["Maths", "What is the volume of a cuboid measuring 5 cm by 4 cm by 3 cm?", "60 cm³", "58 cm³", "59 cm³", "55 cm³"],
    ["Maths", "What is the sum of the interior angles of a hexagon?", "720°", "710°", "721°", "722°"],
    ["Maths", "What is 3/5 as a decimal?", "0.6", "0.45", "0.85", "1.2"],
    ["Maths", "What is 8 + (-5)?", "3", "1", "-7", "-1"],
    ["Maths", "What is (-6) × 6?", "-36", "-34", "-41", "-40"],
    ["Maths", "What is 25% of 60?", "15", "18", "12", "17"],
    ["Maths", "What is 1/2 + 1/3?", "5/6", "2/5", "11/12", "3/4"],
    ["Maths", "Simplify the fraction 10/25.", "2/5", "4/11", "3/6", "3/5"],
    ["Geography", "What is the capital city of Brazil?", "Brasília", "Rio de Janeiro", "São Paulo", "Buenos Aires"],
    ["Geography", "Which is the largest country in Africa by area?", "Algeria", "Nigeria", "Egypt", "South Africa"],
    ["Geography", "Which river flows through the city of Cairo?", "the Nile", "the Niger", "the Congo", "the Zambezi"],
    ["Geography", "Which two countries share the longest land border in the world?", "Canada and the USA", "Russia and China", "India and Pakistan", "Brazil and Peru"],
    ["Geography", "Which is the highest waterfall in the world?", "Angel Falls", "Niagara Falls", "Victoria Falls", "Iguazu Falls"],
    ["Geography", "In which country is Mount Kilimanjaro?", "Tanzania", "Kenya", "Uganda", "Ethiopia"],
    ["Geography", "Off the coast of which country is the Great Barrier Reef?", "Australia", "Brazil", "Indonesia", "Mexico"],
    ["Geography", "Which is the deepest ocean trench?", "the Mariana Trench", "the Puerto Rico Trench", "the Java Trench", "the Tonga Trench"],
    ["Geography", "Which strait separates Spain from Morocco?", "the Strait of Gibraltar", "the Bering Strait", "the Strait of Malacca", "the Strait of Hormuz"],
    ["Geography", "What is the line of 0° longitude called?", "the Prime Meridian", "the Equator", "the Tropic of Cancer", "the Arctic Circle"],
    ["Geography", "What is the capital city of Turkey?", "Ankara", "Istanbul", "Izmir", "Antalya"],
    ["Geography", "On which continent are the Himalayas?", "Asia", "Europe", "Africa", "South America"],
    ["Geography", "Which is the longest river in South America?", "the Amazon", "the Orinoco", "the Paraná", "the Magdalena"],
    ["Geography", "What is the capital city of Germany?", "Berlin", "Munich", "Hamburg", "Frankfurt"],
    ["Geography", "Which country is also a continent?", "Australia", "Greenland", "India", "Brazil"],
    ["Geography", "What is the capital city of Kenya?", "Nairobi", "Mombasa", "Kampala", "Dodoma"],
    ["Geography", "In which country is Mount Fuji?", "Japan", "China", "South Korea", "the Philippines"],
    ["Geography", "Which body of water is the saltiest and has the lowest land surface on Earth?", "the Dead Sea", "the Black Sea", "the Red Sea", "the Caspian Sea"],
    ["Geography", "What is the scientific study of the weather called?", "meteorology", "geology", "ecology", "cartography"],
    ["Geography", "What causes most earthquakes?", "movement of tectonic plates", "storms", "tides", "strong winds"],
    ["Geography", "Which of these countries is landlocked (has no coast)?", "Switzerland", "Italy", "Portugal", "Greece"],
    ["Geography", "What is the capital city of Argentina?", "Buenos Aires", "Santiago", "Lima", "Montevideo"],
    ["Geography", "What is the imaginary line at 0° latitude called?", "the Equator", "the Prime Meridian", "the Tropic of Capricorn", "the International Date Line"],
    ["Geography", "Which desert lies across southern Mongolia and northern China?", "the Gobi Desert", "the Sahara Desert", "the Kalahari Desert", "the Atacama Desert"],
    ["Geography", "The River Ganges flows mainly through which country?", "India", "China", "Egypt", "Brazil"],
    ["Geography", "Which city is the executive (administrative) capital of South Africa?", "Pretoria", "Johannesburg", "Durban", "Port Elizabeth"],
    ["Geography", "What is the capital city of Nigeria?", "Abuja", "Lagos", "Kano", "Ibadan"],
    ["Geography", "What is the capital city of Ethiopia?", "Addis Ababa", "Nairobi", "Khartoum", "Kampala"],
    ["Geography", "What is the capital city of Morocco?", "Rabat", "Casablanca", "Marrakesh", "Tangier"],
    ["Geography", "What is the capital city of Peru?", "Lima", "Cusco", "Quito", "Bogotá"],
    ["Geography", "What is the capital city of Chile?", "Santiago", "Valparaíso", "Lima", "Buenos Aires"],
    ["Geography", "What is the capital city of Colombia?", "Bogotá", "Medellín", "Quito", "Caracas"],
    ["Geography", "What is the capital city of Indonesia?", "Jakarta", "Bali", "Surabaya", "Manila"],
    ["Geography", "What is the capital city of Vietnam?", "Hanoi", "Ho Chi Minh City", "Bangkok", "Phnom Penh"],
    ["Geography", "What is the capital city of South Korea?", "Seoul", "Busan", "Pyongyang", "Tokyo"],
    ["Geography", "What is the capital city of Iran?", "Tehran", "Isfahan", "Baghdad", "Tabriz"],
    ["Geography", "What is the capital city of Iraq?", "Baghdad", "Basra", "Mosul", "Damascus"],
    ["Geography", "What is the capital city of Poland?", "Warsaw", "Kraków", "Gdańsk", "Prague"],
    ["Geography", "What is the capital city of Austria?", "Vienna", "Salzburg", "Graz", "Budapest"],
    ["Geography", "What is the capital city of Ukraine?", "Kyiv", "Kharkiv", "Odesa", "Minsk"],
    ["Geography", "What is the capital city of Bangladesh?", "Dhaka", "Chittagong", "Kolkata", "Karachi"],
    ["Geography", "What is the capital city of Finland?", "Helsinki", "Tampere", "Oslo", "Stockholm"],
    ["Geography", "What is the capital city of Denmark?", "Copenhagen", "Aarhus", "Oslo", "Stockholm"],
    ["Geography", "Which river is the longest in Europe?", "the Volga", "the Danube", "the Rhine", "the Thames"],
    ["Geography", "Which river flows through Vienna, Budapest and Belgrade?", "the Danube", "the Rhine", "the Seine", "the Elbe"],
    ["Geography", "Which river flows through Baghdad?", "the Tigris", "the Euphrates", "the Nile", "the Jordan"],
    ["Geography", "Which river forms much of the border between the USA and Mexico?", "the Rio Grande", "the Mississippi", "the Colorado", "the Yukon"],
    ["Geography", "Which river flows through Moscow?", "the Moskva", "the Volga", "the Neva", "the Dnieper"],
    ["Geography", "Which river flows through the city of Rome?", "the Tiber", "the Arno", "the Po", "the Rhône"],
    ["Geography", "Which river flows through the city of Berlin?", "the Spree", "the Rhine", "the Danube", "the Elbe"],
    ["Geography", "What is the name of the largest lake in Africa?", "Lake Victoria", "Lake Chad", "Lake Tanganyika", "Lake Malawi"],
    ["Geography", "Which is the largest lake in the world by area?", "the Caspian Sea", "Lake Superior", "Lake Victoria", "Lake Baikal"],
    ["Geography", "Which is the largest of the Great Lakes?", "Lake Superior", "Lake Erie", "Lake Ontario", "Lake Michigan"],
    ["Geography", "Which is the highest mountain in Africa?", "Mount Kilimanjaro", "Mount Kenya", "Mount Stanley", "Table Mountain"],
    ["Geography", "Which is the highest mountain in Europe (not counting the Caucasus)?", "Mont Blanc", "Matterhorn", "Ben Nevis", "Mount Etna"],
    ["Geography", "Which mountain range runs along the west coast of North America?", "the Rocky Mountains", "the Appalachians", "the Alps", "the Urals"],
    ["Geography", "Which is the highest mountain in the world above sea level?", "Mount Everest", "K2", "Kangchenjunga", "Mont Blanc"],
    ["Geography", "Which two countries does Mount Everest sit between?", "Nepal and China (Tibet)", "India and Pakistan", "Nepal and India only", "China and Mongolia"],
    ["Geography", "Which volcano destroyed Pompeii in AD 79?", "Vesuvius", "Etna", "Stromboli", "Krakatoa"],
    ["Geography", "Which is the largest active volcano in Europe?", "Mount Etna", "Mount Vesuvius", "Stromboli", "Mont Blanc"],
    ["Geography", "What is the name of the supercontinent that existed about 300 million years ago?", "Pangaea", "Gondwana only", "Atlantis", "Laurasia only"],
    ["Geography", "What are the layers of the Earth in order from the outside?", "crust, mantle, outer core, inner core", "core, mantle, crust, atmosphere", "mantle, crust, outer core, inner core", "crust, outer core, mantle, inner core"],
    ["Geography", "What is the Richter scale used to measure?", "the strength of earthquakes", "the temperature", "the speed of wind", "rainfall"],
    ["Geography", "What is the name for the point on the Earth's surface directly above where an earthquake starts?", "the epicentre", "the focus only", "the fault", "the crater"],
    ["Geography", "What is the Beaufort scale used to measure?", "wind speed", "earthquakes", "rainfall", "temperature"],
    ["Geography", "What is a tributary?", "a smaller river that joins a larger river", "the mouth of a river", "a type of lake", "the source of a river"],
    ["Geography", "What is an oxbow lake?", "a curved lake left when a river meander is cut off", "a lake in a volcano", "a lake made by a glacier only", "a man-made reservoir"],
    ["Geography", "What is a delta?", "a landform where a river splits before entering the sea", "a high waterfall", "a type of lake", "a mountain pass"],
    ["Geography", "What is erosion?", "the wearing away of rock and soil by wind, water or ice", "the building up of land", "the melting of ice", "the growth of plants"],
    ["Geography", "What is deposition?", "when material carried by water or wind is dropped", "when rocks are worn away", "when rain falls", "when plants grow"],
    ["Geography", "What is a meander?", "a bend in a river", "a type of waterfall", "a mountain peak", "a coastal cave"],
    ["Geography", "What is a stack on the coast?", "a tall column of rock left standing in the sea", "a type of beach", "a cliff made of sand", "a river mouth"],
    ["Geography", "Which of these is a coastal landform?", "a headland", "a delta", "a volcano", "a plateau"],
    ["Geography", "What is longshore drift?", "the movement of sand along a coast by waves", "a type of ocean current in the deep sea", "a river flood", "a cliff collapse"],
    ["Geography", "What is the name of the warm ocean current that flows from the Gulf of Mexico towards Europe?", "the Gulf Stream", "the Humboldt Current", "the Kuroshio", "the Labrador Current"],
    ["Geography", "What does 'latitude' measure?", "distance north or south of the Equator", "distance east or west of the Prime Meridian", "height above sea level", "distance from the coast"],
    ["Geography", "What does 'longitude' measure?", "distance east or west of the Prime Meridian", "distance north or south of the Equator", "height above sea level", "temperature"],
    ["Geography", "Which city does the Prime Meridian pass through in England?", "Greenwich, London", "Oxford", "Manchester", "York"],
    ["Geography", "What does a contour line on a map show?", "height of land above sea level", "the temperature", "the roads", "population"],
    ["Geography", "What does a scale on a map tell you?", "how distances on the map relate to real distances", "the weather", "the height of mountains", "the country's capital"],
    ["Geography", "On an Ordnance Survey map, which colour is used for contour lines?", "brown", "blue", "green", "red"],
    ["Geography", "What is a six-figure grid reference used for?", "to give a precise location on a map", "to show the height of a hill", "to measure the temperature", "to count the population"],
    ["Geography", "Which country has the largest population in Africa?", "Nigeria", "Egypt", "South Africa", "Kenya"],
    ["Geography", "Which is the most populated city in the UK?", "London", "Birmingham", "Manchester", "Glasgow"],
    ["Geography", "What does the term 'population density' mean?", "the number of people per square kilometre", "the total number of people in a country", "how old people are", "how many people move in"],
    ["Geography", "What does 'migration' mean?", "the movement of people from one place to another", "the growth of a city", "the building of a road", "the weather changing"],
    ["Geography", "What is a refugee?", "a person forced to leave their country for safety", "a tourist", "a farmer", "a person who lives in a city"],
    ["Geography", "What is a renewable resource?", "one that can be replaced naturally, such as wind", "one that will run out soon, such as coal", "one that is man-made only", "one that is found only underground"],
    ["Geography", "What is global warming?", "the gradual rise in the Earth's average temperature", "a sudden summer heatwave", "a cold winter", "the Sun getting closer"],
    ["Geography", "Which gas is mainly responsible for global warming?", "carbon dioxide", "oxygen", "nitrogen", "argon"],
    ["Geography", "What is deforestation?", "the clearing of forests", "planting new trees", "a type of farming", "the growth of forests"],
    ["Geography", "What is the name of the world's largest rainforest?", "the Amazon", "the Congo", "the Daintree", "the Sundarbans"],
    ["Geography", "Which biome is characterised by very cold temperatures and frozen soil called permafrost?", "tundra", "savanna", "desert", "tropical rainforest"],
    ["Geography", "Which biome is a hot grassland with scattered trees, such as in East Africa?", "savanna", "tundra", "taiga", "temperate forest"],
    ["Geography", "What is the name of the large coniferous forest belt across northern Russia and Canada?", "taiga", "savanna", "tundra", "steppe"],
    ["Geography", "What do we call the climate of lands near the Equator with high temperatures and heavy rain all year?", "tropical", "polar", "Mediterranean", "temperate"],
    ["Geography", "What is the name for the climate with hot dry summers and mild wet winters, such as in Greece?", "Mediterranean", "tropical", "polar", "continental"],
    ["Geography", "What is the capital city of Libya?", "Tripoli", "Benghazi", "Tunis", "Cairo"],
    ["Geography", "What is the capital city of Cuba?", "Havana", "Santiago de Cuba", "Kingston", "Santo Domingo"],
    ["Geography", "What is the capital city of Jamaica?", "Kingston", "Montego Bay", "Havana", "Port-au-Prince"],
    ["History", "In which year was the Magna Carta sealed?", "1215", "1066", "1415", "1688"],
    ["History", "Who was the first Emperor of Rome?", "Augustus", "Julius Caesar", "Nero", "Caligula"],
    ["History", "In which century did the Black Death reach Europe?", "the 14th century", "the 10th century", "the 18th century", "the 20th century"],
    ["History", "Who won the Battle of Hastings in 1066?", "William of Normandy", "King Harold", "Alfred the Great", "King Canute"],
    ["History", "Which empire was founded by Genghis Khan?", "the Mongol Empire", "the Ottoman Empire", "the Roman Empire", "the Persian Empire"],
    ["History", "In which year did the First World War begin?", "1914", "1918", "1939", "1905"],
    ["History", "In which country did the Industrial Revolution begin?", "Britain", "France", "the USA", "Japan"],
    ["History", "Who was the British Prime Minister for most of the Second World War?", "Winston Churchill", "Neville Chamberlain", "Margaret Thatcher", "Tony Blair"],
    ["History", "Who was the first human to travel into space?", "Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "Alan Shepard"],
    ["History", "In which country did the Renaissance begin?", "Italy", "England", "Spain", "Russia"],
    ["History", "In which year did the Berlin Wall come down?", "1989", "1961", "1945", "1991"],
    ["History", "Who was the main author of the American Declaration of Independence?", "Thomas Jefferson", "George Washington", "Benjamin Franklin", "Abraham Lincoln"],
    ["History", "Which two ancient Greek city-states were famous rivals?", "Athens and Sparta", "Rome and Carthage", "Cairo and Thebes", "Troy and Corinth"],
    ["History", "Which US President was assassinated in 1865?", "Abraham Lincoln", "George Washington", "Thomas Jefferson", "Theodore Roosevelt"],
    ["History", "In which year was the Spanish Armada defeated?", "1588", "1488", "1688", "1788"],
    ["History", "Who built the Taj Mahal in memory of his wife?", "Shah Jahan", "Akbar", "Babur", "Aurangzeb"],
    ["History", "Cleopatra was the last active ruler of which country?", "Egypt", "Greece", "Rome", "Persia"],
    ["History", "In which year did India gain independence from Britain?", "1947", "1919", "1950", "1930"],
    ["History", "Who introduced the printing press with movable type to Europe around 1440?", "Johannes Gutenberg", "William Caxton", "Leonardo da Vinci", "Isaac Newton"],
    ["History", "What was the Silk Road?", "a network of trade routes linking China with the West", "a road made of silk", "a famous railway", "a type of ship"],
    ["History", "Which US President issued the Emancipation Proclamation?", "Abraham Lincoln", "George Washington", "Franklin Roosevelt", "John Kennedy"],
    ["History", "In which year did the French Revolution begin?", "1789", "1689", "1889", "1815"],
    ["History", "The Cold War was mainly a rivalry between which two superpowers?", "the USA and the Soviet Union", "the UK and France", "China and Japan", "Germany and Italy"],
    ["History", "Nelson Mandela became president of which country?", "South Africa", "Kenya", "Nigeria", "Ghana"],
    ["History", "In which year did the Wright brothers make the first powered aeroplane flight?", "1903", "1783", "1927", "1945"],
    ["History", "Which Roman emperor made Christianity legal across the empire in AD 313?", "Constantine", "Nero", "Augustus", "Trajan"],
    ["History", "In which year did the Western Roman Empire fall?", "AD 476", "AD 79", "AD 1066", "AD 410 only"],
    ["History", "Which city was the capital of the Eastern Roman (Byzantine) Empire?", "Constantinople", "Rome", "Athens", "Alexandria"],
    ["History", "Who led the Carthaginian army across the Alps with elephants?", "Hannibal", "Spartacus", "Julius Caesar", "Alexander"],
    ["History", "Who led a famous slave revolt against Rome around 73 BC?", "Spartacus", "Hannibal", "Brutus", "Nero"],
    ["History", "Who was assassinated on the Ides of March in 44 BC?", "Julius Caesar", "Augustus", "Nero", "Caligula"],
    ["History", "What was the name of the Greek battle in 490 BC where Athenians beat the Persians?", "Marathon", "Thermopylae", "Salamis", "Troy"],
    ["History", "Which Greek city-state was famous for its strict military training?", "Sparta", "Athens", "Corinth", "Thebes"],
    ["History", "Which Greek city-state is known as the birthplace of democracy?", "Athens", "Sparta", "Thebes", "Delphi"],
    ["History", "Who was the first Emperor of Rome after the Republic?", "Augustus", "Julius Caesar", "Nero", "Constantine"],
    ["History", "Which Anglo-Saxon king united much of England and fought the Vikings in the 9th century?", "Alfred the Great", "Edward the Confessor", "Harold Godwinson", "Ethelred"],
    ["History", "Which king died at the Battle of Hastings in 1066?", "Harold Godwinson", "William of Normandy", "Edward the Confessor", "Harald Hardrada"],
    ["History", "What was the Peasants' Revolt of 1381 mainly a protest against?", "a poll tax", "a new religion", "a foreign invasion", "a famine only"],
    ["History", "Which battle in 1415 saw Henry V defeat a larger French army?", "Agincourt", "Crécy", "Hastings", "Bosworth"],
    ["History", "Which battle in 1485 ended the Wars of the Roses?", "Bosworth Field", "Hastings", "Agincourt", "Naseby"],
    ["History", "Which Tudor king won the Battle of Bosworth Field?", "Henry VII", "Henry VIII", "Edward IV", "Richard III"],
    ["History", "Which of Henry VIII's wives was the mother of Elizabeth I?", "Anne Boleyn", "Catherine of Aragon", "Jane Seymour", "Anne of Cleves"],
    ["History", "What was the Reformation?", "a religious movement that created Protestant churches", "a Roman building programme", "a war between England and Spain", "a scientific revolution"],
    ["History", "Who started the Protestant Reformation in Germany in 1517?", "Martin Luther", "John Calvin", "Henry VIII", "Erasmus"],
    ["History", "What was the Gunpowder Plot of 1605?", "a plan to blow up Parliament", "a plan to invade France", "a rebellion in Scotland", "a peasant uprising"],
    ["History", "Which King was executed in 1649?", "Charles I", "Charles II", "James I", "Henry VIII"],
    ["History", "What was the period without a monarch in England after 1649 called?", "the Commonwealth", "the Restoration", "the Renaissance", "the Reformation"],
    ["History", "Which disease swept through London in 1665?", "the Great Plague", "the Black Death only", "cholera", "smallpox only"],
    ["History", "Which Act joined England and Scotland in 1707?", "the Act of Union", "the Magna Carta", "the Bill of Rights", "the Reform Act"],
    ["History", "What was the Triangular Trade?", "a trade route linking Europe, Africa and the Americas", "a trade route between three English ports", "a Roman trade route", "a Viking trade route"],
    ["History", "Which British politician led the campaign to abolish the slave trade, passing the Act in 1807?", "William Wilberforce", "Winston Churchill", "Robert Peel", "William Pitt"],
    ["History", "Which Act made slavery illegal across most of the British Empire in 1833?", "the Slavery Abolition Act", "the Reform Act", "the Factory Act", "the Poor Law"],
    ["History", "Who was the leader of the Haitian Revolution against French rule?", "Toussaint Louverture", "Simón Bolívar", "George Washington", "Napoleon"],
    ["History", "Which year did the American Declaration of Independence get signed?", "1776", "1789", "1812", "1865"],
    ["History", "Who was the first President of the United States?", "George Washington", "Thomas Jefferson", "John Adams", "Abraham Lincoln"],
    ["History", "What was the name of the French prison stormed in 1789?", "the Bastille", "the Louvre", "Versailles", "the Tuileries"],
    ["History", "Who became Emperor of the French in 1804?", "Napoleon Bonaparte", "Louis XVI", "Robespierre", "Charles de Gaulle"],
    ["History", "At which battle in 1815 was Napoleon defeated by Wellington?", "Waterloo", "Trafalgar", "Austerlitz", "Borodino"],
    ["History", "Which admiral won the Battle of Trafalgar in 1805?", "Horatio Nelson", "Francis Drake", "Duke of Wellington", "Thomas Hardy"],
    ["History", "What invention by James Hargreaves in 1764 sped up the production of cotton thread?", "the spinning jenny", "the steam engine", "the telegraph", "the printing press"],
    ["History", "Which Victorian nurse founded modern nursing after the Crimean War?", "Florence Nightingale", "Mary Seacole", "Edith Cavell", "Elizabeth Fry"],
    ["History", "What was the Great Exhibition of 1851 held in?", "the Crystal Palace", "Buckingham Palace", "the British Museum", "the Tower of London"],
    ["History", "Which Victorian prince organised the Great Exhibition?", "Prince Albert", "Prince Edward", "Prince Charles", "Prince George"],
    ["History", "Which women's campaign group fought for the right to vote with the motto 'Deeds not words'?", "the suffragettes", "the Chartists", "the Luddites", "the Levellers"],
    ["History", "Who led the suffragette movement in the UK (the WSPU)?", "Emmeline Pankhurst", "Millicent Fawcett", "Florence Nightingale", "Queen Victoria"],
    ["History", "In which year did some women in the UK first get the right to vote?", "1918", "1832", "1948", "1969"],
    ["History", "Which Archduke's assassination in 1914 sparked the First World War?", "Archduke Franz Ferdinand", "Archduke Charles", "Kaiser Wilhelm", "Tsar Nicholas"],
    ["History", "In which city was Archduke Franz Ferdinand assassinated in 1914?", "Sarajevo", "Vienna", "Berlin", "Belgrade"],
    ["History", "Which battle in 1916 was among the bloodiest of the First World War, with a first day of heavy British losses?", "the Somme", "Gallipoli", "Waterloo", "Dunkirk"],
    ["History", "What was the name of the treaty that ended the First World War with Germany?", "the Treaty of Versailles", "the Treaty of Paris", "the Treaty of Rome", "the Treaty of Westminster"],
    ["History", "Which Russian leader led the Bolsheviks in 1917?", "Vladimir Lenin", "Joseph Stalin", "Leon Trotsky", "Tsar Nicholas II"],
    ["History", "What was the stock market crash of 1929 followed by?", "the Great Depression", "the Industrial Revolution", "a baby boom", "the Renaissance"],
    ["History", "Which leader of the Nazi party became Chancellor of Germany in 1933?", "Adolf Hitler", "Joseph Goebbels", "Hermann Göring", "Otto von Bismarck"],
    ["History", "What was the name of the Nazi persecution and murder of six million Jewish people?", "the Holocaust", "the Blitz", "the Gulag", "the Armistice"],
    ["History", "What was the name of the bombing campaign on British cities in 1940 to 1941?", "the Blitz", "Dunkirk", "D-Day", "the Somme"],
    ["History", "Which leader of the Soviet Union ruled from the 1920s until 1953?", "Joseph Stalin", "Vladimir Lenin", "Nikita Khrushchev", "Leonid Brezhnev"],
    ["History", "On which date did Allied troops land in Normandy in 1944?", "6th June", "11th November", "8th May", "1st September"],
    ["History", "What was VE Day, 8th May 1945?", "Victory in Europe Day", "Victory over Japan Day", "the start of D-Day", "the end of the Blitz"],
    ["History", "Which two Japanese cities were hit by atomic bombs in 1945?", "Hiroshima and Nagasaki", "Tokyo and Osaka", "Kyoto and Nara", "Kobe and Sapporo"],
    ["History", "What organisation was founded in 1945 to promote international peace?", "the United Nations", "the League of Nations", "NATO", "the European Union"],
    ["History", "What was the Windrush generation?", "people who came from the Caribbean to Britain after 1948", "soldiers who fought at Dunkirk", "settlers who sailed to America in 1620", "Roman soldiers in Britain"],
    ["History", "In which year did the National Health Service (NHS) begin in the UK?", "1948", "1918", "1966", "1984"],
    ["History", "Which country did the USA fight in the Vietnam War, from 1955 to 1975, alongside South Vietnam?", "North Vietnam", "China only", "Japan", "South Korea"],
    ["History", "Which wall divided a European city until 1989?", "the Berlin Wall", "Hadrian's Wall", "the Great Wall", "the Western Wall"],
    ["History", "Which country's launch of Sputnik in 1957 started the Space Race?", "the Soviet Union", "the USA", "the UK", "China"],
    ["History", "In which year did humans first land on the Moon?", "1969", "1957", "1981", "1961"],
    ["History", "Which astronaut was the second person to walk on the Moon?", "Buzz Aldrin", "Neil Armstrong", "Michael Collins", "Yuri Gagarin"],
    ["History", "Who was the first woman in space?", "Valentina Tereshkova", "Sally Ride", "Helen Sharman", "Mae Jemison"],
    ["History", "Who was the first British person in space (1991)?", "Helen Sharman", "Tim Peake", "Valentina Tereshkova", "Sally Ride"],
    ["History", "Which Indian city saw the Mughal emperor Shah Jahan build the Taj Mahal?", "Agra", "Delhi", "Mumbai", "Jaipur"],
    ["History", "In which year did India and Pakistan become independent?", "1947", "1857", "1965", "1971"],
    ["History", "Which Chinese leader founded the People's Republic of China in 1949?", "Mao Zedong", "Sun Yat-sen", "Deng Xiaoping", "Chiang Kai-shek"],
    ["History", "What was apartheid?", "a system of racial segregation in South Africa", "a type of government in India", "a war in Egypt", "a trade agreement"],
    ["History", "Who was the first democratically elected president of South Africa in 1994?", "Nelson Mandela", "Desmond Tutu", "F.W. de Klerk", "Thabo Mbeki"],
    ["History", "Which empire was ruled from Istanbul until 1922?", "the Ottoman Empire", "the Roman Empire", "the Persian Empire", "the Mughal Empire"],
    ["History", "Which city was the capital of the Inca Empire?", "Cusco", "Lima", "Machu Picchu", "Quito"],
    ["History", "Which Spanish conquistador conquered the Aztec Empire in 1521?", "Hernán Cortés", "Francisco Pizarro", "Christopher Columbus", "Ferdinand Magellan"],
    ["History", "What was the name of the ship on which Charles Darwin sailed to the Galápagos Islands?", "HMS Beagle", "the Mayflower", "the Golden Hind", "HMS Victory"],
    ["History", "Which pharaoh built the Great Pyramid of Giza?", "Khufu", "Tutankhamun", "Ramesses II", "Akhenaten"],
    ["History", "What was the name of Henry VIII's warship that sank in 1545 and was raised in 1982?", "the Mary Rose", "the Golden Hind", "HMS Victory", "the Cutty Sark"],
];
