import {PuzzleRow} from '../puzzleTypes.ts';

export const AGE_5_TO_7: PuzzleRow[] = [
    ["English", "Which word rhymes with \"cat\"?", "hat", "dog", "bed", "cup"],
    ["English", "What is the opposite of \"big\"?", "small", "tall", "wide", "loud"],
    ["English", "Which of these words begins with the letter B?", "ball", "cat", "dog", "fish"],
    ["English", "How many letters are there in the English alphabet?", "26", "24", "20", "30"],
    ["English", "What is the plural of \"dog\"?", "dogs", "doges", "dogies", "dogz"],
    ["English", "Which of these is a colour?", "green", "chair", "jump", "book"],
    ["English", "Which word means \"not wet\"?", "dry", "cold", "hot", "soft"],
    ["English", "Which sentence is written correctly?", "The cat sat on the mat.", "Cat the on sat mat.", "Sat cat mat the on.", "On the mat sat cat the."],
    ["English", "What goes at the end of a telling sentence?", "a full stop", "a question mark", "a star", "a tick"],
    ["English", "Which word rhymes with \"tree\"?", "bee", "car", "sun", "pen"],
    ["English", "Which of these letters is a vowel?", "e", "b", "k", "t"],
    ["English", "What is the opposite of \"hot\"?", "cold", "wet", "slow", "soft"],
    ["English", "Which animal's name begins with the letter S?", "snake", "rabbit", "frog", "lion"],
    ["English", "What is the opposite of \"up\"?", "down", "left", "red", "fast"],
    ["English", "Which of these is a \"doing\" word?", "run", "table", "blue", "happy"],
    ["English", "Which of these is a naming word (a noun)?", "dog", "jump", "quickly", "green"],
    ["English", "How many claps (syllables) are in the word \"banana\"?", "3", "1", "2", "4"],
    ["English", "Which word rhymes with \"sun\"?", "run", "sit", "pig", "tap"],
    ["English", "Which word is spelled correctly?", "friend", "freind", "frend", "frind"],
    ["English", "What is a baby cat called?", "a kitten", "a puppy", "a cub", "a calf"],
    ["English", "Which word means the same as \"happy\"?", "glad", "sad", "angry", "tired"],
    ["English", "Which word starts with the \"sh\" sound?", "ship", "cat", "dog", "mat"],
    ["English", "What is the first letter of the alphabet?", "A", "B", "Z", "M"],
    ["English", "Which of these is a describing word (an adjective)?", "tall", "run", "house", "and"],
    ["English", "Where would you go to borrow lots of books?", "a library", "a bakery", "a garage", "a farm"],
    ["English", "Which word rhymes with 'bee'?", "tree", "cat", "pin", "box"],
    ["English", "Which word rhymes with 'night'?", "light", "nut", "nose", "name"],
    ["English", "Which word rhymes with 'moon'?", "spoon", "mine", "mop", "men"],
    ["English", "Which word rhymes with 'bear'?", "chair", "bird", "book", "bone"],
    ["English", "Which word rhymes with 'cake'?", "lake", "kite", "cup", "coat"],
    ["English", "Which word rhymes with 'star'?", "car", "stir", "stop", "stew"],
    ["English", "Which word rhymes with 'ring'?", "sing", "rain", "rug", "road"],
    ["English", "Which word rhymes with 'boat'?", "goat", "bat", "bowl", "bone"],
    ["English", "Which word rhymes with 'play'?", "day", "pea", "pig", "pot"],
    ["English", "Which word rhymes with 'frog'?", "log", "fox", "fish", "free"],
    ["English", "What is the opposite of 'happy'?", "sad", "glad", "kind", "fast"],
    ["English", "What is the opposite of 'day'?", "night", "noon", "sun", "play"],
    ["English", "What is the opposite of 'open'?", "closed", "wide", "empty", "tall"],
    ["English", "What is the opposite of 'full'?", "empty", "large", "heavy", "round"],
    ["English", "What is the opposite of 'fast'?", "slow", "quick", "loud", "high"],
    ["English", "What is the opposite of 'in'?", "out", "on", "at", "up"],
    ["English", "What is the opposite of 'light' (not heavy)?", "heavy", "soft", "thin", "dark"],
    ["English", "What is the opposite of 'old'?", "new", "big", "tall", "long"],
    ["English", "What is the opposite of 'laugh'?", "cry", "jump", "sing", "shout"],
    ["English", "What is the opposite of 'start'?", "finish", "begin", "go", "run"],
    ["English", "Which word begins with the letter D?", "duck", "cow", "pig", "hen"],
    ["English", "Which word begins with the letter M?", "moon", "sun", "star", "cloud"],
    ["English", "Which word begins with the letter T?", "table", "chair", "door", "window"],
    ["English", "Which word begins with the letter F?", "fish", "bird", "cat", "dog"],
    ["English", "Which word begins with the letter P?", "pig", "hen", "cow", "goat"],
    ["English", "Which word ends with the letter T?", "hat", "dog", "pig", "cup"],
    ["English", "Which word ends with the letter G?", "pig", "hat", "cup", "bus"],
    ["English", "What is the last letter of the alphabet?", "Z", "A", "Y", "X"],
    ["English", "Which letter comes after C in the alphabet?", "D", "B", "E", "F"],
    ["English", "Which letter comes before M in the alphabet?", "L", "N", "K", "O"],
    ["English", "Which of these letters is a vowel?", "u", "d", "s", "m"],
    ["English", "Which of these is a vowel?", "o", "p", "r", "w"],
    ["English", "What is the plural of 'cat'?", "cats", "cates", "caties", "cat"],
    ["English", "What is the plural of 'box'?", "boxes", "boxs", "boxies", "boxen"],
    ["English", "What is the plural of 'baby'?", "babies", "babys", "babyes", "babis"],
    ["English", "What is the plural of 'foot'?", "feet", "foots", "feets", "footes"],
    ["English", "What is the plural of 'man'?", "men", "mans", "manes", "mann"],
    ["English", "What is the plural of 'fish'?", "fish", "fishes", "fishies", "fishs"],
    ["English", "What do we put at the start of a sentence?", "a capital letter", "a full stop", "a number", "a picture"],
    ["English", "What do we put at the end of a question?", "a question mark", "a full stop", "a comma", "a capital letter"],
    ["English", "Which word needs a capital letter?", "Monday", "table", "jump", "happy"],
    ["English", "Which word needs a capital letter?", "London", "river", "shop", "bread"],
    ["English", "Which of these is a describing word?", "red", "jump", "book", "sing"],
    ["English", "Which of these is a describing word?", "soft", "eat", "table", "swim"],
    ["English", "Which of these is a doing word?", "swim", "tree", "pink", "tall"],
    ["English", "Which of these is a doing word?", "jump", "sky", "green", "happy"],
    ["English", "Which of these is a naming word?", "apple", "slowly", "kind", "run"],
    ["English", "Which of these is a naming word?", "school", "quick", "walk", "blue"],
    ["English", "How many claps (syllables) are in the word 'elephant'?", "3", "1", "2", "4"],
    ["English", "How many claps (syllables) are in the word 'cat'?", "1", "2", "3", "4"],
    ["English", "How many claps (syllables) are in the word 'butterfly'?", "3", "2", "4", "1"],
    ["English", "How many claps (syllables) are in the word 'pencil'?", "2", "1", "3", "4"],
    ["English", "Which word is spelled correctly?", "house", "hous", "howse", "hause"],
    ["English", "Which word is spelled correctly?", "school", "scool", "skool", "schol"],
    ["English", "Which word is spelled correctly?", "said", "sed", "sayd", "siad"],
    ["English", "Which word is spelled correctly?", "water", "wotar", "watter", "woter"],
    ["English", "What is a baby dog called?", "a puppy", "a kitten", "a cub", "a calf"],
    ["English", "What is a baby cow called?", "a calf", "a lamb", "a foal", "a chick"],
    ["English", "What is a baby horse called?", "a foal", "a pup", "a lamb", "a cub"],
    ["English", "What is a baby hen called?", "a chick", "a duckling", "a cygnet", "a kid"],
    ["English", "Which word means the same as 'big'?", "large", "tiny", "thin", "soft"],
    ["English", "Which word means the same as 'little'?", "small", "huge", "loud", "long"],
    ["English", "Which word means the same as 'sad'?", "unhappy", "cheerful", "angry", "sleepy"],
    ["English", "Which word means the same as 'quick'?", "fast", "slow", "late", "dull"],
    ["English", "Which word means the same as 'start'?", "begin", "stop", "end", "wait"],
    ["English", "Which word means 'to look at something'?", "see", "hear", "taste", "touch"],
    ["English", "Which sentence tells us about a boy?", "He is kind.", "She is kind.", "It is kind.", "They is kind."],
    ["English", "Which word fits the gap? 'The bird ___ in the tree.'", "sings", "sing", "singing a", "sung a"],
    ["English", "Which word fits the gap? 'I have two ___.'", "hands", "hand", "handing", "handed"],
    ["English", "What do we call a book of words and their meanings?", "a dictionary", "a diary", "a menu", "a map"],
    ["English", "What do you do with a book?", "read it", "eat it", "drive it", "wear it"],
    ["English", "Which of these is a story you may read at bedtime?", "a fairy tale", "a shopping list", "a bus ticket", "a road sign"],
    ["English", "Which sentence is written correctly?", "The dog ran fast.", "the dog ran fast", "The dog Ran fast", "dog the ran fast."],
    ["English", "Which word is a colour?", "yellow", "table", "shout", "sleep"],
    ["English", "What do we call the words in a song that rhyme at the end of lines?", "a rhyme", "a number", "a map", "a shape"],
    ["Science", "What do plants need to grow?", "water and sunlight", "sweets and chocolate", "music and toys", "sand and stones"],
    ["Science", "How many legs does a spider have?", "8", "6", "4", "10"],
    ["Science", "What sound does a cow make?", "moo", "quack", "woof", "baa"],
    ["Science", "Which of these animals can fly?", "a bird", "a dog", "a fish", "a horse"],
    ["Science", "What gives us heat and light in the daytime?", "the Sun", "the Moon", "a cloud", "a rainbow"],
    ["Science", "Which of these is a liquid?", "water", "rock", "wood", "glass"],
    ["Science", "How many legs does a dog have?", "4", "2", "6", "8"],
    ["Science", "Which part of your body do you use to see?", "your eyes", "your ears", "your nose", "your hands"],
    ["Science", "Which season is the coldest?", "winter", "summer", "spring", "autumn"],
    ["Science", "What do fish use to breathe underwater?", "gills", "wings", "legs", "hair"],
    ["Science", "What does a caterpillar turn into?", "a butterfly", "a beetle", "a bee", "a bird"],
    ["Science", "Which of these animals lives in the sea?", "a shark", "a lion", "a cow", "a rabbit"],
    ["Science", "What do we call frozen water?", "ice", "steam", "smoke", "sand"],
    ["Science", "What colour do you make by mixing blue and yellow?", "green", "purple", "orange", "pink"],
    ["Science", "What do bees make?", "honey", "milk", "bread", "butter"],
    ["Science", "How many senses do humans have (sight, hearing, smell, taste and touch)?", "5", "3", "7", "10"],
    ["Science", "Which part of your body do you use to smell?", "your nose", "your knees", "your elbows", "your hair"],
    ["Science", "What is a baby frog called?", "a tadpole", "a kitten", "a chick", "a lamb"],
    ["Science", "What falls from the clouds when it rains?", "water", "sand", "paper", "milk"],
    ["Science", "What is a baby sheep called?", "a lamb", "a calf", "a foal", "a cub"],
    ["Science", "Which of these animals lays eggs?", "a hen", "a dog", "a cat", "a horse"],
    ["Science", "What shape is the Earth?", "like a ball (a sphere)", "flat like a plate", "like a cube", "like a pyramid"],
    ["Science", "Which animal gives us milk?", "a cow", "a hen", "a fish", "a frog"],
    ["Science", "What do we need to breathe?", "air", "sand", "juice", "grass"],
    ["Science", "In which season do the leaves fall off the trees?", "autumn", "spring", "summer", "winter"],
    ["Science", "How many legs does an insect have?", "6", "4", "8", "10"],
    ["Science", "How many legs does a bird have?", "2", "4", "6", "8"],
    ["Science", "How many legs does a cat have?", "4", "2", "6", "8"],
    ["Science", "How many wings does a butterfly have?", "4", "2", "6", "8"],
    ["Science", "Which animal has a very long neck?", "a giraffe", "a rabbit", "a mouse", "a pig"],
    ["Science", "Which animal is the biggest on land?", "an elephant", "a cat", "a dog", "a rabbit"],
    ["Science", "Which animal has a trunk?", "an elephant", "a horse", "a lion", "a bear"],
    ["Science", "Which animal hops and says 'ribbit'?", "a frog", "a cow", "a hen", "a sheep"],
    ["Science", "Which animal has black and white stripes?", "a zebra", "a lion", "a camel", "a bear"],
    ["Science", "Which animal carries a hump on its back?", "a camel", "a horse", "a goat", "a duck"],
    ["Science", "What do we call animals that live in a farm and give us wool?", "sheep", "hens", "pigs", "ducks"],
    ["Science", "Which animal gives us eggs?", "a hen", "a cow", "a sheep", "a pig"],
    ["Science", "Which animal can swim and has feathers?", "a duck", "a dog", "a cat", "a rabbit"],
    ["Science", "Which animal builds a web?", "a spider", "a bee", "a dog", "a fish"],
    ["Science", "Which animal lives in a hive?", "a bee", "a bear", "a bat", "a bird"],
    ["Science", "Which animal sleeps upside down in a cave?", "a bat", "a horse", "a duck", "a frog"],
    ["Science", "What do rabbits like to eat?", "carrots", "fish", "chocolate", "bread and jam"],
    ["Science", "What covers the body of a bird?", "feathers", "fur", "scales", "shells"],
    ["Science", "What covers the body of a fish?", "scales", "feathers", "wool", "fur"],
    ["Science", "What covers the body of a sheep?", "wool", "feathers", "scales", "shell"],
    ["Science", "Where does a bird lay its eggs?", "in a nest", "in a river", "in a puddle", "in a car"],
    ["Science", "What part of a plant is usually green and grows from the stem?", "leaves", "roots", "petals", "seeds"],
    ["Science", "Which part of a plant is under the ground?", "roots", "flowers", "leaves", "fruit"],
    ["Science", "Which part of a plant is often colourful and smells nice?", "a flower", "a root", "a stem", "a seed"],
    ["Science", "What grows from a tiny seed?", "a plant", "a stone", "a toy", "a spoon"],
    ["Science", "Which of these is a fruit?", "an apple", "a carrot", "a potato", "an onion"],
    ["Science", "Which of these is a vegetable?", "a carrot", "a banana", "a grape", "a strawberry"],
    ["Science", "Which fruit is yellow and curved?", "a banana", "an orange", "a plum", "a cherry"],
    ["Science", "Which tree makes acorns?", "an oak tree", "a palm tree", "a pine tree", "an apple tree"],
    ["Science", "What do we need to drink to stay healthy?", "water", "paint", "petrol", "glue"],
    ["Science", "Which food is good for our teeth?", "an apple", "a sticky sweet", "a lollipop", "a toffee"],
    ["Science", "What should we do to keep our teeth clean?", "brush them", "paint them", "tap them", "stretch them"],
    ["Science", "What should we wear when it is very sunny?", "a sun hat", "a woolly scarf", "a raincoat", "snow boots"],
    ["Science", "What should we wear when it is raining?", "a raincoat", "a sun hat", "sandals", "shorts only"],
    ["Science", "What do we use our ears for?", "hearing", "seeing", "smelling", "tasting"],
    ["Science", "What do we use our tongue for?", "tasting", "hearing", "seeing", "smelling"],
    ["Science", "What do we use our hands to do?", "touch and hold things", "hear sounds", "smell flowers", "see colours"],
    ["Science", "How many fingers do you have on one hand?", "5", "4", "6", "10"],
    ["Science", "How many toes do you have on two feet altogether?", "10", "5", "8", "20"],
    ["Science", "Which part of your body helps you to think?", "your brain", "your knee", "your elbow", "your toe"],
    ["Science", "Which part of your body pumps blood?", "your heart", "your elbow", "your nose", "your toe"],
    ["Science", "What do we call the hard parts inside our body that hold us up?", "bones", "muscles", "hair", "nails"],
    ["Science", "Which of these is hot?", "fire", "ice", "snow", "a frozen lolly"],
    ["Science", "Which of these is cold?", "ice", "fire", "a hot bath", "a candle"],
    ["Science", "What happens to ice when it gets warm?", "it melts", "it grows", "it turns to stone", "it floats away"],
    ["Science", "What do we call water that falls from the sky in tiny drops?", "rain", "sand", "leaves", "feathers"],
    ["Science", "What do we call frozen rain that falls in white flakes?", "snow", "sand", "mud", "fog"],
    ["Science", "What appears in the sky when it is sunny and rainy at the same time?", "a rainbow", "a star", "a kite", "a balloon"],
    ["Science", "How many colours are in a rainbow?", "7", "3", "5", "12"],
    ["Science", "What is the colour of the sky on a clear day?", "blue", "green", "purple", "brown"],
    ["Science", "What do we see in the sky at night that shine?", "stars", "kites", "leaves", "flowers"],
    ["Science", "What goes around the Earth and shines at night?", "the Moon", "the Sun", "a cloud", "a plane"],
    ["Science", "What is the name of the star we see in the daytime?", "the Sun", "the Moon", "Mars", "Earth"],
    ["Science", "Which is bigger?", "the Sun", "a football", "a house", "a mountain"],
    ["Science", "Which of these is a planet?", "Mars", "the Sun", "the Moon", "a comet"],
    ["Science", "Which season comes after winter?", "spring", "summer", "autumn", "winter again"],
    ["Science", "Which season is the hottest?", "summer", "winter", "autumn", "spring"],
    ["Science", "In which season do flowers begin to bloom?", "spring", "winter", "autumn", "midnight"],
    ["Science", "Which of these things is soft?", "a pillow", "a rock", "a brick", "a spoon"],
    ["Science", "Which of these things is hard?", "a rock", "a cloud", "a feather", "cotton wool"],
    ["Science", "Which of these materials is bendy and stretchy?", "rubber", "stone", "glass", "metal"],
    ["Science", "What is a window made of?", "glass", "wool", "paper", "cheese"],
    ["Science", "What are most pots and pans made of?", "metal", "paper", "wool", "jelly"],
    ["Science", "What is a pencil mostly made of?", "wood", "glass", "wool", "rubber"],
    ["Science", "Which of these floats on water?", "a wooden boat", "a stone", "a coin", "a key"],
    ["Science", "Which of these sinks in water?", "a stone", "a feather", "a leaf", "a cork"],
    ["Science", "What do we use to see in the dark?", "a torch", "a spoon", "a sock", "a book"],
    ["Science", "What does a magnet pick up?", "iron things like a paper clip", "a feather", "a leaf", "a sock"],
    ["Science", "What do we call the sound a dog makes?", "a bark", "a moo", "a quack", "a roar"],
    ["Science", "What do we need to hear a sound?", "our ears", "our knees", "our elbows", "our toes"],
    ["Science", "What makes a shadow?", "something blocking the light", "wind", "cold", "water"],
    ["Science", "What do we use to keep us warm in winter?", "a coat", "shorts", "sandals", "a swimsuit"],
    ["Science", "What do plants give us that we need to breathe?", "oxygen", "dust", "smoke", "glue"],
    ["Science", "What do all living things need to stay alive?", "food and water", "toys", "music", "paint"],
    ["Science", "What do we call a person who looks after sick animals?", "a vet", "a baker", "a pilot", "a farmer"],
    ["Maths", "What is 2 + 6?", "8", "9", "12", "10"],
    ["Maths", "What is 4 + 1?", "5", "0", "10", "2"],
    ["Maths", "What is 5 + 6?", "11", "9", "12", "1"],
    ["Maths", "What is 5 + 1?", "6", "8", "10", "7"],
    ["Maths", "What is 9 + 8?", "17", "21", "15", "19"],
    ["Maths", "What is 7 + 8?", "15", "16", "25", "19"],
    ["Maths", "What is 4 + 5?", "9", "5", "3", "6"],
    ["Maths", "What is 7 + 9?", "16", "14", "22", "21"],
    ["Maths", "What is 16 - 8?", "8", "10", "9", "14"],
    ["Maths", "What is 11 - 1?", "10", "7", "14", "4"],
    ["Maths", "What is 12 - 1?", "11", "21", "5", "12"],
    ["Maths", "What is 20 - 3?", "17", "11", "18", "15"],
    ["Maths", "What is 11 - 7?", "4", "7", "6", "10"],
    ["Maths", "What is double 3?", "6", "7", "1", "4"],
    ["Maths", "What is double 5?", "10", "13", "6", "12"],
    ["Maths", "What is double 6?", "12", "8", "7", "17"],
    ["Maths", "What is double 8?", "16", "17", "22", "14"],
    ["Maths", "What is half of 10?", "5", "1", "4", "6"],
    ["Maths", "What is half of 14?", "7", "17", "10", "11"],
    ["Maths", "What is half of 8?", "4", "14", "9", "0"],
    ["Maths", "What number comes next? 2, 4, 6, 8, ...", "10", "12", "9", "5"],
    ["Maths", "What number comes next? 5, 10, 15, 20, ...", "25", "30", "24", "28"],
    ["Maths", "What number comes next? 10, 20, 30, 40, ...", "50", "60", "49", "54"],
    ["Maths", "How many sides does a triangle have?", "3", "4", "5", "2"],
    ["Maths", "How many days are there in a week?", "7", "5", "6", "8"],
    ["Maths", "What is 7 + 12?", "19", "21", "20", "15"],
    ["Maths", "What is 17 - 4?", "13", "15", "11", "12"],
    ["Maths", "What is 20 + 10?", "30", "35", "33", "29"],
    ["Maths", "What is double 7?", "14", "11", "17", "16"],
    ["Maths", "What is half of 4?", "2", "5", "12", "4"],
    ["Maths", "What number comes next? 20, 30, 40, 50, ...", "60", "70", "61", "59"],
    ["Maths", "What number makes this true? 3 + ? = 13", "10", "6", "11", "8"],
    ["Maths", "Which is the biggest number: 25, 81, 97, 64?", "97", "81", "64", "25"],
    ["Maths", "Which is the smallest number: 38, 33, 41, 54?", "33", "41", "54", "38"],
    ["Maths", "What is ten less than 21?", "11", "9", "22", "1"],
    ["Maths", "Which number is between 76 and 78?", "77", "154", "74", "87"],
    ["Maths", "How many sides does a circle have?", "0", "2", "4", "1"],
    ["Maths", "How many minutes are in half an hour?", "30", "45", "60", "15"],
    ["Maths", "How much are 2 coins of 5p worth altogether?", "10p", "7p", "20p", "5p"],
    ["Maths", "What number has 4 tens and 5 ones?", "45", "42", "43", "44"],
    ["Maths", "Zara has 8 sweets and finds 4 more. How many sweets does Zara have now?", "12", "8", "24", "22"],
    ["Maths", "How many fingers are there on 4 hands?", "20", "23", "16", "19"],
    ["Maths", "Is 12 an odd or an even number?", "even", "odd", "neither", "both"],
    ["Maths", "What is 11 + 3?", "14", "15", "4", "13"],
    ["Maths", "What is 16 - 9?", "7", "8", "17", "3"],
    ["Maths", "What is 10 + 10?", "20", "17", "10", "23"],
    ["Maths", "What is double 12?", "24", "29", "28", "23"],
    ["Maths", "What is half of 18?", "9", "7", "5", "12"],
    ["Maths", "What number comes next? 10, 15, 20, 25, ...", "30", "35", "40", "29"],
    ["Maths", "What number makes this true? 5 + ? = 7", "2", "1", "3", "5"],
    ["Maths", "Which is the biggest number: 80, 47, 43, 98?", "98", "43", "47", "80"],
    ["Maths", "Which is the smallest number: 52, 6, 19, 91?", "6", "19", "91", "52"],
    ["Maths", "What is one more than 79?", "80", "82", "160", "83"],
    ["Maths", "Which number is between 10 and 12?", "11", "9", "21", "10"],
    ["Maths", "How many corners does a triangle have?", "3", "6", "5", "4"],
    ["Maths", "How many months are there in a year?", "12", "52", "7", "10"],
    ["Maths", "A toy costs 6p and a sweet costs 2p. How much do they cost altogether?", "8p", "18p", "16p", "7p"],
    ["Maths", "What number has 9 tens and 6 ones?", "96", "98", "94", "99"],
    ["Maths", "Amira has 12 pencils and gives away 8. How many pencils does Amira have left?", "4", "2", "7", "0"],
    ["Maths", "How many wheels do 3 bicycles have altogether?", "6", "10", "8", "1"],
    ["Maths", "Is 15 an odd or an even number?", "odd", "both", "even", "neither"],
    ["Maths", "What is 11 + 5?", "16", "20", "15", "14"],
    ["Maths", "What is 20 - 16?", "4", "2", "8", "1"],
    ["Maths", "What is 30 + 60?", "90", "80", "180", "95"],
    ["Maths", "What is double 1?", "2", "1", "6", "5"],
    ["Maths", "What is half of 20?", "10", "8", "12", "11"],
    ["Maths", "What number comes next? 6, 9, 12, 15, ...", "18", "22", "8", "20"],
    ["Maths", "What number makes this true? 5 + ? = 13", "8", "4", "18", "6"],
    ["Maths", "Which is the biggest number: 16, 23, 6, 72?", "72", "23", "6", "16"],
    ["Maths", "Which is the smallest number: 66, 93, 6, 9?", "6", "93", "66", "9"],
    ["Maths", "What is ten less than 60?", "50", "60", "52", "100"],
    ["Maths", "Which number is between 52 and 54?", "53", "50", "55", "49"],
    ["Maths", "A cube has how many faces?", "6", "4", "12", "8"],
    ["Maths", "Which day comes after Tuesday?", "Wednesday", "Monday", "Thursday", "Friday"],
    ["Maths", "Which coin is worth the most?", "£1", "50p", "10p", "20p"],
    ["Maths", "What number has 8 tens and 3 ones?", "83", "82", "78", "79"],
    ["Maths", "Omar has 2 cards and finds 6 more. How many cards does Omar have now?", "8", "4", "13", "12"],
    ["Maths", "How many legs do 5 dogs have altogether?", "20", "40", "25", "30"],
    ["Maths", "Is 18 an odd or an even number?", "even", "odd", "neither", "both"],
    ["Maths", "What is 2 + 12?", "14", "9", "17", "16"],
    ["Maths", "What is 13 - 12?", "1", "0", "5", "2"],
    ["Maths", "What is 50 + 30?", "80", "83", "85", "77"],
    ["Maths", "What is double 4?", "8", "3", "16", "7"],
    ["Maths", "What is half of 22?", "11", "15", "6", "13"],
    ["Maths", "What number comes next? 1, 11, 21, 31, ...", "41", "46", "44", "31"],
    ["Maths", "What number makes this true? 6 + ? = 15", "9", "6", "11", "12"],
    ["Maths", "Which is the biggest number: 86, 10, 38, 9?", "86", "9", "38", "10"],
    ["Maths", "Which is the smallest number: 97, 72, 58, 11?", "11", "58", "97", "72"],
    ["Maths", "What is one less than 35?", "34", "32", "44", "35"],
    ["Maths", "Which number is between 46 and 48?", "47", "57", "42", "46"],
    ["Maths", "How many corners does a square have?", "4", "7", "5", "3"],
    ["Maths", "Which day comes before Sunday?", "Saturday", "Tuesday", "Monday", "Friday"],
    ["Maths", "How many pence are there in £1?", "100", "10", "20", "50"],
    ["Maths", "What number has 3 tens and 4 ones?", "34", "35", "32", "33"],
    ["Maths", "Ella has 7 pencils and finds 3 more. How many pencils does Ella have now?", "10", "15", "20", "0"],
    ["Maths", "What is 5 + 5 + 5?", "15", "17", "20", "10"],
    ["Maths", "Is 30 an odd or an even number?", "even", "odd", "both", "neither"],
    ["Maths", "What is 9 + 5?", "14", "13", "12", "10"],
    ["Maths", "What is 17 - 16?", "1", "0", "11", "4"],
    ["Maths", "What is 20 + 40?", "60", "120", "56", "57"],
    ["Geography", "Which of these is the biggest?", "an ocean", "a pond", "a puddle", "a stream"],
    ["Geography", "What colour is the sea usually shown on a map?", "blue", "red", "yellow", "brown"],
    ["Geography", "Which of these is a continent?", "Africa", "London", "the Nile", "Everest"],
    ["Geography", "What do we call a very tall hill?", "a mountain", "a puddle", "a beach", "a pond"],
    ["Geography", "What do we call land with water all around it?", "an island", "a desert", "a hill", "a forest"],
    ["Geography", "Which place is very hot and dry with lots of sand?", "a desert", "a lake", "a river", "a mountain"],
    ["Geography", "Which animal lives at the North Pole?", "a polar bear", "a lion", "a camel", "a monkey"],
    ["Geography", "What flows along to reach the sea?", "a river", "a hill", "a road", "a tree"],
    ["Geography", "What do we use a map for?", "finding places", "baking cakes", "sleeping", "singing"],
    ["Geography", "Which of these is a type of weather?", "rain", "pencil", "table", "milk"],
    ["Geography", "Which direction is the opposite of north?", "south", "east", "west", "up"],
    ["Geography", "Which sandy place is beside the sea?", "a beach", "a forest", "a farm", "a mountain"],
    ["Geography", "What shape is a globe?", "a ball (a sphere)", "a cube", "a triangle", "a square"],
    ["Geography", "When do we need an umbrella?", "when it is rainy", "when it is sunny", "when it is hot", "when it is clear"],
    ["Geography", "What is at the very top of the world called?", "the North Pole", "the South Pole", "the Equator", "the Sahara"],
    ["Geography", "Which animal lives on the African savannah?", "a lion", "a polar bear", "a penguin", "a seal"],
    ["Geography", "Where do penguins live?", "Antarctica", "the desert", "the jungle", "the city"],
    ["Geography", "What is the name of the planet we live on?", "Earth", "Mars", "the Moon", "the Sun"],
    ["Geography", "In which direction does the Sun rise?", "east", "west", "north", "south"],
    ["Geography", "What do we call a very big area full of trees?", "a forest", "a pond", "a beach", "a road"],
    ["Geography", "What do we call water falling over a high cliff?", "a waterfall", "a wave", "a puddle", "a bubble"],
    ["Geography", "Which place is the coldest?", "the North Pole", "a desert", "a beach", "a jungle"],
    ["Geography", "Where do aeroplanes take off from?", "an airport", "a farm", "a beach", "a school"],
    ["Geography", "Which of these is a country?", "Japan", "Paris", "Everest", "the Pacific"],
    ["Geography", "What is the capital city of England?", "London", "Paris", "Rome", "Cairo"],
    ["Geography", "Which of these is a country?", "France", "London", "Thames", "Europe"],
    ["Geography", "Which country do we live in if we live in London?", "England", "France", "India", "Egypt"],
    ["Geography", "Which of these is a city?", "Paris", "Africa", "the Atlantic", "Asia"],
    ["Geography", "What do we call a very large area of salt water?", "an ocean", "a pond", "a puddle", "a stream"],
    ["Geography", "What do we call a small area of water in a garden?", "a pond", "an ocean", "a desert", "a mountain"],
    ["Geography", "Which of these is a type of weather?", "sunny", "pencil", "table", "apple"],
    ["Geography", "What do we call very strong moving air?", "wind", "rain", "fog", "mud"],
    ["Geography", "What do we call thick cloud close to the ground that is hard to see through?", "fog", "snow", "a rainbow", "a breeze"],
    ["Geography", "Which clothes do we wear in snowy weather?", "a warm coat and gloves", "a swimsuit", "sandals", "shorts"],
    ["Geography", "What do we call a hot, dry weather season with no rain for a long time?", "a drought", "a flood", "a snowstorm", "a rainbow"],
    ["Geography", "What do we call too much water covering the land?", "a flood", "a desert", "a hill", "a path"],
    ["Geography", "Which place is usually very cold and covered in ice and snow?", "the North Pole", "a desert", "a jungle", "a beach"],
    ["Geography", "Which place is hot with lots of tall trees, rain and animals?", "a jungle", "the South Pole", "a desert", "a glacier"],
    ["Geography", "Which place has very little rain and lots of sand?", "a desert", "a jungle", "a lake", "a river"],
    ["Geography", "What do we call a large area of water with land all around it?", "a lake", "an island", "a hill", "a path"],
    ["Geography", "What do we call a long strip of water that flows to the sea?", "a river", "a mountain", "a desert", "a field"],
    ["Geography", "Which is higher?", "a mountain", "a hill that is small", "a molehill", "a stone"],
    ["Geography", "Where do farmers grow crops and keep animals?", "on a farm", "in a library", "in a hospital", "at an airport"],
    ["Geography", "Where do we go to see lots of animals from around the world?", "a zoo", "a bakery", "a bank", "a garage"],
    ["Geography", "Where do we go to catch a train?", "a train station", "a library", "a school", "a swimming pool"],
    ["Geography", "Where do ships and boats stay when they are not at sea?", "a harbour", "a library", "a garden", "a field"],
    ["Geography", "Where do we go to borrow books?", "a library", "a supermarket", "a harbour", "a garage"],
    ["Geography", "Where do we go to buy food?", "a shop", "a library", "a museum", "a church only"],
    ["Geography", "Which place do children go to learn?", "a school", "a farm", "a shop", "a station"],
    ["Geography", "Which place do we go to when we are ill and need a doctor?", "a hospital", "a bakery", "a cinema", "a zoo"],
    ["Geography", "Which vehicle travels on water?", "a boat", "a bicycle", "a car", "a train"],
    ["Geography", "Which vehicle travels on rails?", "a train", "a boat", "a car", "a bus"],
    ["Geography", "Which vehicle flies in the sky?", "an aeroplane", "a bicycle", "a boat", "a bus"],
    ["Geography", "What do we call the big road where cars drive very fast?", "a motorway", "a garden path", "a river", "a field"],
    ["Geography", "What do we use to cross a river?", "a bridge", "a ladder", "a sock", "a hat"],
    ["Geography", "What are the four main directions on a compass?", "north, south, east and west", "red, green, blue and yellow", "up, down, in and out", "hot, cold, wet and dry"],
    ["Geography", "Which direction is opposite to east?", "west", "north", "south", "up"],
    ["Geography", "Which direction is opposite to south?", "north", "east", "west", "down"],
    ["Geography", "In which direction does the Sun set?", "west", "east", "north", "south"],
    ["Geography", "Which tool helps us find our way to a place?", "a map", "a spoon", "a pencil case", "a hat"],
    ["Geography", "What do we call a drawing of a place seen from above?", "a map", "a story", "a song", "a puzzle"],
    ["Geography", "How many countries make up the United Kingdom?", "4", "2", "10", "7"],
    ["Geography", "Which of these is part of the United Kingdom?", "Scotland", "Spain", "Egypt", "Japan"],
    ["Geography", "What is the capital city of Scotland?", "Edinburgh", "Cardiff", "London", "Dublin"],
    ["Geography", "What is the capital city of Wales?", "Cardiff", "Edinburgh", "London", "Belfast"],
    ["Geography", "Which animal lives in the Arctic?", "a polar bear", "a camel", "a zebra", "a monkey"],
    ["Geography", "Which animal lives in the desert?", "a camel", "a penguin", "a whale", "a seal"],
    ["Geography", "Which animal lives in the jungle?", "a monkey", "a polar bear", "a penguin", "a sheep"],
    ["Geography", "Which animal lives in the sea?", "a whale", "a cow", "a lion", "a camel"],
    ["Geography", "Which bird cannot fly and lives in very cold places?", "a penguin", "a robin", "an eagle", "a parrot"],
    ["Geography", "What do we call the very top of a mountain?", "the peak", "the root", "the bottom", "the beach"],
    ["Geography", "What is the sandy edge of the sea called?", "the coast or beach", "the mountain top", "the desert", "the jungle"],
    ["Geography", "What do we call the sea water that comes up on the beach and goes back out?", "the tide", "the wind", "the sun", "the sand"],
    ["Geography", "Which season usually has the longest days?", "summer", "winter", "autumn", "none of them"],
    ["Geography", "Which of these is a continent?", "Asia", "Paris", "France", "London"],
    ["Geography", "Which continent is Egypt in?", "Africa", "Asia", "Europe", "Australia"],
    ["Geography", "Which continent is the United Kingdom in?", "Europe", "Africa", "Asia", "Antarctica"],
    ["Geography", "Which continent is India in?", "Asia", "Africa", "Europe", "South America"],
    ["Geography", "What is the name of the biggest ocean?", "the Pacific Ocean", "the Indian Ocean", "the Arctic Ocean", "the Atlantic Ocean"],
    ["Geography", "Which country is home to the kangaroo?", "Australia", "Canada", "Egypt", "Norway"],
    ["Geography", "Which country is famous for the Eiffel Tower?", "France", "Italy", "Spain", "Egypt"],
    ["Geography", "Which country is famous for pizza and pasta?", "Italy", "Japan", "India", "Brazil"],
    ["Geography", "Which country is famous for sushi?", "Japan", "Mexico", "Iceland", "Kenya"],
    ["Geography", "Which country is famous for the Taj Mahal?", "India", "Egypt", "China", "Greece"],
    ["Geography", "In which country is the Great Wall found?", "China", "Spain", "Peru", "Canada"],
    ["Geography", "Which country is famous for its Big Ben clock tower?", "England", "Brazil", "India", "Kenya"],
    ["Geography", "Which of these countries is very cold, with lots of ice and volcanoes?", "Iceland", "Egypt", "Kenya", "Brazil"],
    ["Geography", "In which country is the city of Dubai?", "the United Arab Emirates", "Canada", "Australia", "Brazil"],
    ["Geography", "In which country is the city of Mumbai?", "India", "Egypt", "Japan", "Spain"],
    ["Geography", "In which country do people speak mostly Arabic and the pyramids stand?", "Egypt", "Japan", "Canada", "Norway"],
    ["Geography", "What do we call water that is not salty, such as in rivers and lakes?", "fresh water", "sea water", "sand water", "mud only"],
    ["Geography", "What do we call a group of houses in the countryside that is smaller than a town?", "a village", "a city", "a country", "a continent"],
    ["Geography", "What is the name for a very big, busy place with lots of buildings?", "a city", "a nest", "a pond", "a hill"],
    ["Geography", "Which of these is found in a city?", "tall buildings", "only fields", "only trees", "only sand"],
    ["Geography", "Which of these is found in the countryside?", "fields and farms", "skyscrapers", "a metro", "a big airport only"],
    ["Geography", "What do we call a path where cars can drive?", "a road", "a river", "a lake", "a bridge only"],
    ["Geography", "What is the Earth mostly covered with?", "water", "sand", "ice", "grass"],
    ["Geography", "What lights up the Earth in the day?", "the Sun", "a street lamp", "a torch", "a candle"],
    ["Geography", "Which season has the shortest days?", "winter", "summer", "spring", "none of them"],
    ["Geography", "Which direction does a compass needle point to?", "north", "south", "east", "west"],
    ["History", "Long ago, who lived in castles?", "kings and queens", "astronauts", "footballers", "robots"],
    ["History", "When did dinosaurs live?", "millions of years ago", "last year", "yesterday", "next week"],
    ["History", "Which is older?", "a horse and cart", "a car", "a rocket", "a helicopter"],
    ["History", "What did people use for light before electric lights?", "candles and oil lamps", "mobile phones", "televisions", "computers"],
    ["History", "Who wore armour long ago?", "knights", "doctors", "bakers", "teachers"],
    ["History", "In which country can you see the famous Great Pyramids?", "Egypt", "Canada", "Norway", "Peru"],
    ["History", "What did the ancient Egyptians write with?", "pictures called hieroglyphs", "emojis", "emails", "text messages"],
    ["History", "What do we call a big old stone building where kings and knights lived?", "a castle", "an igloo", "a tent", "a shed"],
    ["History", "Who was the first person to walk on the Moon?", "Neil Armstrong", "Isaac Newton", "Albert Einstein", "Charles Darwin"],
    ["History", "In which month do people celebrate Christmas?", "December", "June", "March", "August"],
    ["History", "What did pirates sail on?", "ships", "trains", "buses", "bicycles"],
    ["History", "How did people travel before there were cars?", "by horse and cart", "by rocket", "by scooter", "by helicopter"],
    ["History", "What did knights ride?", "horses", "elephants", "bicycles", "tractors"],
    ["History", "What does a museum show us?", "old things from the past", "cartoons", "cakes", "toys to buy"],
    ["History", "Who was the Queen of England for a very long time until 2022?", "Queen Elizabeth II", "Queen Victoria", "Queen Anne", "Queen Mary"],
    ["History", "What were the ancient Romans famous for building?", "roads", "skyscrapers", "airports", "rockets"],
    ["History", "Which came first?", "dinosaurs", "castles", "cars", "mobile phones"],
    ["History", "What did the Vikings sail in?", "longships", "submarines", "hot air balloons", "steamboats"],
    ["History", "How did people cook long ago, before cookers?", "over a fire", "in a microwave", "in an air fryer", "on an induction hob"],
    ["History", "What do we call a person who digs up old things from the ground to learn about the past?", "an archaeologist", "an astronaut", "a chef", "a pilot"],
    ["History", "Which animal did the ancient Egyptians treat as special and sacred?", "cats", "penguins", "kangaroos", "polar bears"],
    ["History", "What does a king wear on his head?", "a crown", "a helmet", "a scarf", "a cap"],
    ["History", "What carried astronauts to the Moon?", "a rocket", "a bus", "a boat", "a train"],
    ["History", "What did the ancient Romans wear?", "togas", "jeans", "trainers", "hoodies"],
    ["History", "Which of these people lived in a castle long ago?", "a knight", "a pilot", "a footballer", "a vlogger"],
    ["History", "What do we call the time that has already happened, long ago?", "the past", "the future", "tomorrow", "the weekend"],
    ["History", "What do we call the time that has not happened yet?", "the future", "the past", "yesterday", "last year"],
    ["History", "Which came first?", "a candle", "a torch with a battery", "a light bulb", "a phone torch"],
    ["History", "Which is older?", "a castle", "a skyscraper", "a shopping mall", "a cinema"],
    ["History", "Which of these did people use long ago to write?", "a quill pen", "a computer", "a smartphone", "a tablet"],
    ["History", "What did people use long ago to send letters quickly across the land?", "a horse rider", "a rocket", "a drone", "a text message"],
    ["History", "Which of these is a very old toy?", "a spinning top", "a video game", "a robot dog", "a tablet"],
    ["History", "What did people use to wash clothes long ago?", "a washboard and tub", "a washing machine", "a dishwasher", "a tumble dryer"],
    ["History", "Who lived in a palace?", "a king or queen", "a farmer in a barn", "a fish", "a bear"],
    ["History", "What was a knight's job long ago?", "to protect and fight for a lord or king", "to bake bread", "to teach reading", "to drive a train"],
    ["History", "What did a knight wear to protect their body?", "armour", "a swimsuit", "pyjamas", "a woolly hat only"],
    ["History", "What did a knight carry to protect themselves from swords?", "a shield", "an umbrella", "a book", "a teddy bear"],
    ["History", "What did a knight use to fight?", "a sword", "a pencil", "a spoon", "a ball"],
    ["History", "What surrounds many old castles to keep enemies out?", "a moat", "a swimming pool", "a garden fence", "a road"],
    ["History", "What was a drawbridge used for?", "to cross the moat into a castle", "to cross a road", "to catch fish", "to fly a kite"],
    ["History", "What did pirates fly on their ships?", "a skull and crossbones flag", "a rainbow flag", "a school flag", "a football flag"],
    ["History", "What did pirates hide long ago?", "treasure", "homework", "ice cream", "shoes"],
    ["History", "Which people lived in Egypt long ago and built pyramids?", "the ancient Egyptians", "the Vikings", "the Romans", "the Normans"],
    ["History", "What did the ancient Egyptians build for their pharaohs to be buried in?", "pyramids", "castles", "windmills", "skyscrapers"],
    ["History", "What was the ruler of Ancient Egypt called?", "a pharaoh", "a knight", "a sheriff", "an emperor"],
    ["History", "Which river was very important to the ancient Egyptians?", "the River Nile", "the River Thames", "the River Severn", "the River Seine"],
    ["History", "What did the ancient Egyptians make from the papyrus plant to write on?", "paper", "bricks", "boats of metal", "clothes"],
    ["History", "Which people sailed in longships and came to Britain long ago?", "the Vikings", "the Egyptians", "the Greeks", "the Aztecs"],
    ["History", "Which people built straight roads and baths in Britain long ago?", "the Romans", "the Vikings", "the Egyptians", "the Aztecs"],
    ["History", "Who wore a toga long ago?", "a Roman", "a knight", "a pirate", "an astronaut"],
    ["History", "Which famous Roman building was used for gladiator fights?", "the Colosseum", "the Eiffel Tower", "Big Ben", "the Taj Mahal"],
    ["History", "What was the Roman capital city?", "Rome", "Paris", "London", "Athens"],
    ["History", "Which people hunted mammoths in the Stone Age?", "cave people", "knights", "pirates", "Romans"],
    ["History", "What did Stone Age people live in?", "caves", "skyscrapers", "castles", "palaces"],
    ["History", "What did Stone Age people make tools from?", "stone and bone", "plastic", "steel", "rubber"],
    ["History", "What did early people discover that kept them warm and cooked food?", "fire", "television", "electricity", "the telephone"],
    ["History", "Which animals lived millions of years ago and are now extinct?", "dinosaurs", "cows", "dogs", "cats"],
    ["History", "What do we call the bones of animals that lived long ago and are found in rock?", "fossils", "magnets", "crystals", "coins"],
    ["History", "What is the name of a person who studies dinosaur fossils?", "a palaeontologist", "a baker", "a pilot", "a farmer"],
    ["History", "Which dinosaur was famous for being the 'king of the tyrant lizards'?", "Tyrannosaurus rex", "Triceratops", "Stegosaurus", "Diplodocus"],
    ["History", "Which dinosaur had three horns on its face?", "Triceratops", "Tyrannosaurus rex", "Velociraptor", "Pterodactyl"],
    ["History", "Who was Queen of England for 70 years until 2022?", "Queen Elizabeth II", "Queen Victoria", "Queen Mary", "Queen Anne"],
    ["History", "Which king had six wives?", "Henry VIII", "Richard III", "George III", "Edward I"],
    ["History", "What was a Victorian child's school desk often made of?", "wood", "plastic", "glass", "foam"],
    ["History", "What did Victorian children often write on at school?", "a slate", "a tablet computer", "a whiteboard with a pen", "a laptop"],
    ["History", "Which English city did a famous Great Fire burn down in 1666?", "London", "Paris", "Rome", "York"],
    ["History", "Where did the Great Fire of London start in 1666?", "in a bakery in Pudding Lane", "in a palace", "in a church tower", "on a ship"],
    ["History", "What did people use to travel across seas in the past, before aeroplanes?", "ships", "rockets", "trams", "scooters"],
    ["History", "Which two brothers made the first powered aeroplane flight in 1903?", "the Wright brothers", "the Marx brothers", "the Grimm brothers", "the Mario brothers"],
    ["History", "Who was the first person in space?", "Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "Tim Peake"],
    ["History", "Which country sent the first person into space?", "the Soviet Union", "Canada", "Egypt", "Australia"],
    ["History", "Which space programme took astronauts to the Moon?", "Apollo", "Titanic", "Concorde", "Mayflower"],
    ["History", "On which day do people in Britain remember soldiers who died in wars?", "Remembrance Day", "Easter", "Halloween", "Pancake Day"],
    ["History", "What flower do many people wear to remember soldiers?", "a poppy", "a rose", "a daisy", "a tulip"],
    ["History", "On which night do people in Britain light bonfires and remember Guy Fawkes?", "5th November", "1st January", "25th December", "14th February"],
    ["History", "What do we celebrate on 25th December?", "Christmas", "Easter", "Halloween", "Diwali"],
    ["History", "What is Diwali also known as?", "the festival of lights", "the festival of snow", "the festival of flowers", "the festival of eggs"],
    ["History", "Which festival celebrates the end of Ramadan?", "Eid al-Fitr", "Diwali", "Easter", "Hanukkah"],
    ["History", "What do Christians celebrate at Easter?", "the resurrection of Jesus", "the birth of Jesus", "the New Year", "the harvest"],
    ["History", "What do people often give each other at Easter?", "chocolate eggs", "fireworks", "pumpkins", "snowmen"],
    ["History", "What did people in the past use to get water before taps?", "a well", "a tap", "a bottle shop", "a fountain pen"],
    ["History", "What did people use to light their houses before electricity?", "candles and oil lamps", "phone torches", "LED lamps", "neon signs"],
    ["History", "What was a stagecoach pulled by?", "horses", "cars", "engines", "oxen on rails"],
    ["History", "What was the first kind of train powered by?", "steam", "batteries", "petrol", "the wind"],
    ["History", "Who invented the first telephone?", "Alexander Graham Bell", "Isaac Newton", "Albert Einstein", "Charles Darwin"],
    ["History", "What do we call a story told about people and events from long ago?", "history", "a recipe", "a spelling test", "a maths problem"],
    ["History", "What do historians use to learn about the past?", "old objects, photos and books", "only new toys", "only fairy tales", "only cartoons"],
    ["History", "Which building keeps old things from the past for people to see?", "a museum", "a bakery", "a garage", "a supermarket"],
    ["History", "What do we call a picture of a person that has been painted?", "a portrait", "a map", "a photograph of a cloud", "a jigsaw"],
    ["History", "What was used for money long ago?", "coins", "credit cards", "phones", "tickets"],
    ["History", "How did people cook long ago before ovens?", "over open fires", "in microwaves", "on electric hobs", "in toasters"],
    ["History", "What was the name of the ship the Pilgrims sailed on in 1620?", "the Mayflower", "the Titanic", "the Golden Hind", "the Victory"],
    ["History", "Which famous ship sank on its first journey in 1912?", "the Titanic", "the Mayflower", "the Golden Hind", "the Cutty Sark"],
    ["History", "Which Roman leader is famous for his many battles and for being called Caesar?", "Julius Caesar", "Henry VIII", "Tutankhamun", "Alfred"],
    ["History", "Which king is said to have burned some cakes?", "King Alfred", "King Henry VIII", "King John", "King Richard"],
    ["History", "Who is the famous king in the legend with the Knights of the Round Table?", "King Arthur", "King Alfred", "King John", "King Henry"],
    ["History", "What famous sword was King Arthur said to have pulled from a stone?", "Excalibur", "Narsil", "Sting", "Glamdring"],
    ["History", "Which nurse, known as 'the Lady with the Lamp', helped soldiers in the Crimean War?", "Florence Nightingale", "Queen Victoria", "Anne Frank", "Queen Elizabeth I"],
    ["History", "Which people in Britain long ago built hill forts and lived in round houses?", "the Celts", "the Vikings", "the Egyptians", "the Normans"],
    ["History", "Which Egyptian boy king's tomb was found full of treasure in 1922?", "Tutankhamun", "Ramesses", "Cleopatra", "Julius Caesar"],
];
