import {PuzzleRow} from '../puzzleTypes.ts';

export const AGE_8_TO_10: PuzzleRow[] = [
    ["English", "Which word is a synonym (means the same) of \"big\"?", "large", "tiny", "thin", "quiet"],
    ["English", "In the sentence \"The dog barked noisily\", which word is the adverb?", "noisily", "dog", "barked", "The"],
    ["English", "What is the plural of \"child\"?", "children", "childs", "childes", "childrens"],
    ["English", "What is the past tense of \"run\"?", "ran", "runned", "running", "runs"],
    ["English", "Which punctuation mark ends a question?", "a question mark", "a full stop", "a comma", "an apostrophe"],
    ["English", "What is the opposite of \"ancient\"?", "modern", "old", "historic", "dusty"],
    ["English", "Which word is spelled correctly?", "because", "becuase", "becaus", "becase"],
    ["English", "What is a simile?", "a comparison using \"like\" or \"as\"", "two words that rhyme", "a word that sounds like its meaning", "a very short story"],
    ["English", "\"As busy as a bee\" is an example of what?", "a simile", "alliteration", "onomatopoeia", "a rhyme"],
    ["English", "Which of these words is an example of onomatopoeia?", "buzz", "table", "quiet", "green"],
    ["English", "Which of these is a proper noun?", "London", "city", "river", "town"],
    ["English", "What is the opposite of \"generous\"?", "mean", "kind", "giving", "friendly"],
    ["English", "Which word is spelled correctly?", "separate", "seperate", "separete", "seprate"],
    ["English", "What is the contraction of \"do not\"?", "don't", "do'nt", "dont'", "d'not"],
    ["English", "What is the plural of \"mouse\" (the animal)?", "mice", "mouses", "mices", "mouse"],
    ["English", "Which word is the verb in \"The children play in the park\"?", "play", "children", "park", "the"],
    ["English", "What do we call a word that means the same as another word?", "a synonym", "an antonym", "a homophone", "an acronym"],
    ["English", "Which word sounds the same as \"their\" but means \"in that place\"?", "there", "the", "them", "three"],
    ["English", "Which sentence is correct?", "We were happy.", "We was happy.", "We is happy.", "We be happy."],
    ["English", "What do we call a word that has the opposite meaning of another word?", "an antonym", "a synonym", "an acronym", "a prefix"],
    ["English", "Which prefix turns \"happy\" into its opposite?", "un-", "re-", "pre-", "-ful"],
    ["English", "What do we call the story of a real person's life, written by someone else?", "a biography", "a fable", "a diary", "a recipe"],
    ["English", "A fable usually ends with what?", "a moral (a lesson)", "a recipe", "a map", "a song"],
    ["English", "Which of these is a conjunction (a joining word)?", "but", "quickly", "table", "red"],
    ["English", "Which word completes the sentence? \"The children left ___ coats at school.\"", "their", "there", "they're", "thare"],
    ["English", "Which word is a noun in the sentence 'The tall giraffe ate leaves'?", "giraffe", "tall", "ate", "the"],
    ["English", "Which word is an adjective in the sentence 'The green frog jumped high'?", "green", "frog", "jumped", "high"],
    ["English", "Which word is a verb in the sentence 'Birds sing in the morning'?", "sing", "birds", "morning", "in"],
    ["English", "What is the plural of 'baby'?", "babies", "babys", "babyes", "babis"],
    ["English", "What is the plural of 'leaf'?", "leaves", "leafs", "leafes", "leavs"],
    ["English", "What is the plural of 'sheep'?", "sheep", "sheeps", "sheepes", "sheepies"],
    ["English", "What is the plural of 'woman'?", "women", "womans", "womens", "womanes"],
    ["English", "What is the plural of 'tooth'?", "teeth", "tooths", "toothes", "teeths"],
    ["English", "What is the past tense of 'swim'?", "swam", "swimmed", "swum", "swimed"],
    ["English", "What is the past tense of 'eat'?", "ate", "eated", "eaten", "eatted"],
    ["English", "What is the past tense of 'go'?", "went", "goed", "gone", "goes"],
    ["English", "What is the past tense of 'bring'?", "brought", "brang", "bringed", "broughten"],
    ["English", "What is the past tense of 'think'?", "thought", "thinked", "thunk", "thoughten"],
    ["English", "Which word is a synonym of 'tiny'?", "minute", "giant", "heavy", "loud"],
    ["English", "Which word is a synonym of 'angry'?", "furious", "joyful", "calm", "sleepy"],
    ["English", "Which word is a synonym of 'brave'?", "courageous", "fearful", "lazy", "quiet"],
    ["English", "Which word is a synonym of 'clever'?", "intelligent", "silly", "weak", "slow"],
    ["English", "Which word is a synonym of 'shout'?", "yell", "whisper", "mumble", "hum"],
    ["English", "Which word is an antonym of 'always'?", "never", "often", "usually", "forever"],
    ["English", "Which word is an antonym of 'difficult'?", "easy", "hard", "tricky", "complex"],
    ["English", "Which word is an antonym of 'discover'?", "lose", "find", "uncover", "reveal"],
    ["English", "Which word is an antonym of 'victory'?", "defeat", "triumph", "success", "win"],
    ["English", "Which word is an antonym of 'rough'?", "smooth", "bumpy", "jagged", "coarse"],
    ["English", "Which punctuation mark shows that letters are missing, as in 'can't'?", "an apostrophe", "a comma", "a colon", "a hyphen"],
    ["English", "Which punctuation mark do we use in a list to separate items?", "a comma", "a full stop", "a question mark", "an exclamation mark"],
    ["English", "What does an exclamation mark show?", "strong feeling or surprise", "a question", "a pause only", "a list"],
    ["English", "Which sentence is punctuated correctly?", "Where are you going?", "Where are you going.", "where are you going?", "Where are you going,"],
    ["English", "Which sentence is punctuated correctly?", "Tom said, \"I am hungry.\"", "Tom said, I am hungry.\"", "Tom said \"I am hungry,\"", "\"Tom said I am hungry.\""],
    ["English", "What are the marks \" \" used for in writing?", "showing what someone says", "ending a sentence", "joining two words", "showing a list"],
    ["English", "What is the contraction of 'I am'?", "I'm", "Im", "I'am", "Ia'm"],
    ["English", "What is the contraction of 'they are'?", "they're", "their", "there's", "they'er"],
    ["English", "What is the contraction of 'will not'?", "won't", "willn't", "wo'nt", "wont'"],
    ["English", "Which word is spelled correctly?", "necessary", "neccessary", "necesary", "neccesary"],
    ["English", "Which word is spelled correctly?", "believe", "beleive", "belive", "bellieve"],
    ["English", "Which word is spelled correctly?", "Wednesday", "Wensday", "Wendsday", "Wednsday"],
    ["English", "Which word is spelled correctly?", "favourite", "favorit", "favourit", "faverite"],
    ["English", "Which word is spelled correctly?", "different", "diffrent", "diferent", "differant"],
    ["English", "Which word is spelled correctly?", "island", "iland", "islund", "ireland"],
    ["English", "Which word is spelled correctly?", "library", "libary", "liberry", "librery"],
    ["English", "Which word is spelled correctly?", "February", "Febuary", "Febrary", "Feburary"],
    ["English", "Which word is spelled correctly?", "beautiful", "beutiful", "beautifull", "beatiful"],
    ["English", "Which word sounds the same as 'whole'?", "hole", "wheel", "whale", "hall"],
    ["English", "Which word sounds the same as 'sea'?", "see", "say", "saw", "sew"],
    ["English", "Which word sounds the same as 'flour'?", "flower", "floor", "fly", "flare"],
    ["English", "Which word sounds the same as 'knew'?", "new", "know", "now", "key"],
    ["English", "Which word sounds the same as 'right'?", "write", "rice", "ride", "rain"],
    ["English", "Which word sounds the same as 'bear'?", "bare", "beer", "beard", "bar"],
    ["English", "Which word completes the sentence? 'I want to go ___ the park.'", "to", "too", "two", "tow"],
    ["English", "Which word completes the sentence? 'It is ___ cold to swim today.'", "too", "to", "two", "tow"],
    ["English", "Which word completes the sentence? 'The dog wagged ___ tail.'", "its", "it's", "its'", "it"],
    ["English", "Which word completes the sentence? 'She ___ her homework yesterday.'", "finished", "finish", "finishing", "finishes"],
    ["English", "Which word completes the sentence? 'We ___ to the beach last summer.'", "went", "gone", "go", "going"],
    ["English", "Which sentence uses a capital letter correctly?", "My friend lives in Manchester.", "My friend lives in manchester.", "my friend lives in Manchester.", "My Friend lives in manchester."],
    ["English", "Which of these is a metaphor?", "The moon is a silver coin.", "The moon is like a silver coin.", "The moon shines brightly.", "The moon is far away."],
    ["English", "Which of these is a simile?", "He ran like the wind.", "He was the wind.", "He ran quickly.", "The wind ran."],
    ["English", "What do we call words that start with the same sound, such as 'big brown bear'?", "alliteration", "rhyme", "a simile", "a verb"],
    ["English", "What word describes a story that is made up and not real?", "fiction", "non-fiction", "biography", "report"],
    ["English", "What word describes a book with real facts, such as an encyclopaedia?", "non-fiction", "fiction", "fantasy", "fairy tale"],
    ["English", "Who is the author of a book?", "the person who wrote it", "the person who sells it", "the person who reads it", "the person who draws on it only"],
    ["English", "Who is the illustrator of a book?", "the person who draws the pictures", "the person who prints it", "the person who reads it", "the person who sells it"],
    ["English", "What do we call the words on the back of a book that tell us what it is about?", "the blurb", "the index", "the glossary", "the chapter"],
    ["English", "In a non-fiction book, which page lists topics and where to find them at the back?", "the index", "the blurb", "the title", "the cover"],
    ["English", "What do we call a list of words and their meanings at the back of a book?", "a glossary", "a blurb", "a plot", "a chorus"],
    ["English", "What is a paragraph?", "a group of sentences about one idea", "a single word", "a type of poem", "a punctuation mark"],
    ["English", "What do we call a poem of 17 syllables from Japan, with three short lines?", "a haiku", "a limerick", "a sonnet", "an ode"],
    ["English", "What type of poem has five lines and is often funny, with an AABBA rhyme?", "a limerick", "a haiku", "a sonnet", "an elegy"],
    ["English", "Which Roald Dahl book is about a boy who visits a chocolate factory?", "Charlie and the Chocolate Factory", "Matilda", "The BFG", "The Twits"],
    ["English", "Who wrote the 'Harry Potter' books?", "J.K. Rowling", "Roald Dahl", "Enid Blyton", "C.S. Lewis"],
    ["English", "In which story does a girl called Alice fall down a rabbit hole?", "Alice's Adventures in Wonderland", "Peter Pan", "The Secret Garden", "Matilda"],
    ["English", "In 'The Lion, the Witch and the Wardrobe', through which object do the children enter Narnia?", "a wardrobe", "a mirror", "a door in a tree", "a painting"],
    ["English", "Which fairy tale features three bears and a girl called Goldilocks?", "Goldilocks and the Three Bears", "Little Red Riding Hood", "Hansel and Gretel", "Cinderella"],
    ["English", "Which character lost a glass slipper at a royal ball?", "Cinderella", "Snow White", "Rapunzel", "Sleeping Beauty"],
    ["English", "In which story does a wooden puppet's nose grow when he tells lies?", "Pinocchio", "Peter Pan", "Toy Story", "The Jungle Book"],
    ["English", "What do we call a word that describes how a verb is done, such as 'slowly'?", "an adverb", "a noun", "an adjective", "a pronoun"],
    ["English", "Which word is a pronoun in the sentence 'She kicked the ball'?", "She", "kicked", "ball", "the"],
    ["Science", "What force pulls objects towards the ground?", "gravity", "magnetism", "friction", "light"],
    ["Science", "Which planet is closest to the Sun?", "Mercury", "Venus", "Earth", "Mars"],
    ["Science", "Which gas do plants take in from the air to make food?", "carbon dioxide", "oxygen", "helium", "nitrogen"],
    ["Science", "At what temperature does water boil (in degrees Celsius)?", "100", "0", "50", "212"],
    ["Science", "Which part of a plant takes in water from the soil?", "the roots", "the leaves", "the flower", "the petals"],
    ["Science", "Which is the hardest natural material?", "diamond", "gold", "iron", "glass"],
    ["Science", "How many bones does an adult human body have?", "206", "106", "306", "150"],
    ["Science", "Which organ pumps blood around the body?", "the heart", "the lungs", "the brain", "the stomach"],
    ["Science", "What do we call animals that eat only plants?", "herbivores", "carnivores", "omnivores", "predators"],
    ["Science", "Which of these materials is magnetic?", "iron", "wood", "plastic", "glass"],
    ["Science", "What is the Sun?", "a star", "a planet", "a moon", "a comet"],
    ["Science", "What do we call a solid turning into a liquid?", "melting", "freezing", "evaporating", "condensing"],
    ["Science", "Which of these is a source of light?", "the Sun", "the Moon", "a mirror", "a window"],
    ["Science", "What is the name of the process plants use to make their own food?", "photosynthesis", "digestion", "respiration", "evaporation"],
    ["Science", "What causes the tides in the sea?", "the Moon's gravity", "the wind", "fish", "volcanoes"],
    ["Science", "Which material is a good conductor of electricity?", "copper", "rubber", "wood", "plastic"],
    ["Science", "How many teeth does a typical adult have?", "32", "20", "28", "40"],
    ["Science", "Which of these is NOT a state of matter?", "sound", "solid", "liquid", "gas"],
    ["Science", "What do we call animals that have a backbone?", "vertebrates", "invertebrates", "insects", "arachnids"],
    ["Science", "Which planet is known as the Red Planet?", "Mars", "Venus", "Jupiter", "Saturn"],
    ["Science", "What type of animal is a frog?", "an amphibian", "a reptile", "a mammal", "a bird"],
    ["Science", "Which blood vessels carry blood away from the heart?", "arteries", "veins", "nerves", "bones"],
    ["Science", "Which of these is a renewable source of energy?", "wind", "coal", "oil", "gas"],
    ["Science", "What happens to a shadow when a light is moved closer to the object?", "it gets bigger", "it gets smaller", "it disappears", "it turns red"],
    ["Science", "What do bees help flowers to do as they travel between them?", "spread pollen", "grow taller", "change colour", "close up"],
    ["Science", "Which part of the human body is the largest organ?", "the skin", "the heart", "the brain", "the stomach"],
    ["Science", "Which organ do we use to breathe?", "the lungs", "the liver", "the kidneys", "the stomach"],
    ["Science", "Which organ controls the body and helps us think?", "the brain", "the heart", "the lungs", "the liver"],
    ["Science", "Where does most digestion of food happen?", "the stomach and intestines", "the lungs", "the brain", "the skin"],
    ["Science", "What do muscles help us to do?", "move", "see", "hear", "smell"],
    ["Science", "What is the job of the skeleton?", "to support and protect the body", "to digest food", "to pump blood", "to make sounds"],
    ["Science", "Which food group helps our bodies to grow and repair, such as meat, fish and beans?", "protein", "fat", "sugar", "fibre"],
    ["Science", "Which of these gives us energy quickly?", "carbohydrates", "vitamins", "water", "fibre"],
    ["Science", "What is a healthy diet?", "a mix of different foods in the right amounts", "only sweets", "only meat", "only bread"],
    ["Science", "What are the three states of matter?", "solid, liquid and gas", "hot, warm and cold", "hard, soft and wet", "red, green and blue"],
    ["Science", "What is steam?", "water as a gas", "water as a solid", "water as a liquid only", "a type of ice"],
    ["Science", "What do we call a liquid turning into a gas?", "evaporation", "freezing", "melting", "condensation"],
    ["Science", "What do we call a gas turning into a liquid, like water drops on a cold window?", "condensation", "evaporation", "melting", "freezing"],
    ["Science", "What do we call a liquid turning into a solid?", "freezing", "melting", "evaporation", "boiling"],
    ["Science", "At what temperature does water freeze, in degrees Celsius?", "0", "10", "100", "-10"],
    ["Science", "Which of these is an insulator of heat?", "wool", "copper", "iron", "aluminium"],
    ["Science", "Which of these is a good conductor of heat?", "metal", "wood", "plastic", "wool"],
    ["Science", "What is the name for the force that slows moving things down when they rub together?", "friction", "gravity", "magnetism", "light"],
    ["Science", "What do we measure force in?", "newtons", "litres", "metres", "degrees"],
    ["Science", "What force makes a magnet pull on an iron nail?", "magnetic force", "friction", "light", "sound"],
    ["Science", "Which of these is a magnetic metal?", "iron", "copper", "gold", "aluminium"],
    ["Science", "What are the two ends of a magnet called?", "poles", "edges", "corners", "tops"],
    ["Science", "What happens when two north poles of magnets are brought together?", "they push apart", "they pull together", "nothing", "they melt"],
    ["Science", "What do we call the path that electricity flows around?", "a circuit", "a bridge", "a tunnel", "a switch only"],
    ["Science", "What do we use in a circuit to turn the electricity on and off?", "a switch", "a wire only", "a bulb", "a battery"],
    ["Science", "What provides the energy in a simple torch circuit?", "a battery", "a bulb", "a wire", "a switch"],
    ["Science", "Which of these is dangerous to touch with wet hands?", "a plug socket", "a pencil", "a ball", "a book"],
    ["Science", "What does a bulb do in a circuit?", "gives out light", "stores energy", "switches on", "carries a current"],
    ["Science", "How does sound travel to our ears?", "in waves through the air", "as a beam of light", "through magnets", "through plants"],
    ["Science", "What do we need to see things?", "light", "silence", "a battery", "a magnet"],
    ["Science", "Which of these objects is luminous (gives out its own light)?", "the Sun", "the Moon", "a mirror", "a book"],
    ["Science", "What happens to a shadow when the light source moves further away from an object?", "it gets smaller", "it gets bigger", "it disappears", "it turns blue"],
    ["Science", "What is the bouncing back of light from a surface called?", "reflection", "absorption", "evaporation", "condensation"],
    ["Science", "What do we call a material that light cannot pass through?", "opaque", "transparent", "translucent", "magnetic"],
    ["Science", "What do we call a material that you can see clearly through, such as clear glass?", "transparent", "opaque", "magnetic", "solid only"],
    ["Science", "What is the name for the dark shape made when an object blocks light?", "a shadow", "a reflection", "a spectrum", "a rainbow"],
    ["Science", "How many colours are there in a rainbow?", "7", "5", "6", "9"],
    ["Science", "What is the name of the layer of gases around the Earth?", "the atmosphere", "the crust", "the core", "the ocean"],
    ["Science", "Which planet is the largest in our Solar System?", "Jupiter", "Earth", "Mars", "Venus"],
    ["Science", "Which planet has the most famous rings?", "Saturn", "Mars", "Venus", "Mercury"],
    ["Science", "Which planet do we live on?", "Earth", "Mars", "Venus", "Neptune"],
    ["Science", "How long does the Earth take to travel around the Sun once?", "one year", "one day", "one month", "one week"],
    ["Science", "How long does the Earth take to spin once on its axis?", "about 24 hours", "about one week", "about one month", "about one year"],
    ["Science", "What causes day and night on Earth?", "the Earth spinning", "the Moon moving", "the Sun moving around Earth", "clouds"],
    ["Science", "Which planet is the hottest in our Solar System?", "Venus", "Mercury", "Mars", "Jupiter"],
    ["Science", "What is the Moon?", "a natural satellite of the Earth", "a star", "a planet", "a comet"],
    ["Science", "What do we call a group of stars that forms a pattern in the sky?", "a constellation", "a galaxy", "a planet", "a moon"],
    ["Science", "Which galaxy is our Solar System in?", "the Milky Way", "Andromeda", "the Whirlpool", "the Pinwheel"],
    ["Science", "What is a habitat?", "the place where an animal or plant lives", "a type of food", "a kind of weather", "a kind of plant disease"],
    ["Science", "What is a food chain?", "a line showing what eats what", "a long shopping list", "a chain of shops", "a type of metal"],
    ["Science", "What do we call animals that eat both plants and meat?", "omnivores", "herbivores", "carnivores", "producers"],
    ["Science", "What do we call animals that eat only meat?", "carnivores", "herbivores", "omnivores", "producers"],
    ["Science", "In a food chain, what is a plant called?", "a producer", "a predator", "a consumer", "a decomposer"],
    ["Science", "What do we call an animal that is hunted by another animal?", "prey", "a predator", "a producer", "a herbivore"],
    ["Science", "What do we call an animal that hunts others for food?", "a predator", "prey", "a producer", "a plant"],
    ["Science", "What do decomposers like fungi do?", "break down dead plants and animals", "make food from sunlight", "hunt for prey", "pollinate flowers"],
    ["Science", "Which part of a flower makes the seeds?", "the ovary", "the petals", "the stem", "the root"],
    ["Science", "What is pollination?", "moving pollen from flower to flower", "growing a new plant from a leaf", "a plant making seeds underground", "a plant losing leaves"],
    ["Science", "What do plants need for photosynthesis?", "light, water and carbon dioxide", "soil only", "meat and water", "sugar and salt"],
    ["Science", "What gas do plants give out during photosynthesis?", "oxygen", "carbon dioxide", "nitrogen", "helium"],
    ["Science", "What is the job of the stem of a plant?", "to carry water and hold the plant up", "to make seeds", "to attract bees", "to take in light only"],
    ["Science", "What is the job of a plant's leaves?", "to make food using sunlight", "to take in water from the soil", "to hold the plant in the ground", "to make roots"],
    ["Science", "Which of these is an example of a mammal?", "a whale", "a shark", "a frog", "a crocodile"],
    ["Science", "Which of these animals is a reptile?", "a snake", "a frog", "a bat", "a trout"],
    ["Science", "Which of these animals is an amphibian?", "a newt", "a lizard", "a dolphin", "a sparrow"],
    ["Science", "What do we call animals without a backbone?", "invertebrates", "vertebrates", "mammals", "reptiles"],
    ["Science", "Which of these is an invertebrate?", "a snail", "a rabbit", "a trout", "a hen"],
    ["Science", "What are the three main body parts of an insect?", "head, thorax and abdomen", "head, tail and legs", "wings, legs and eyes", "shell, body and feet"],
    ["Science", "What is the correct order of a butterfly's life cycle?", "egg, caterpillar, pupa, butterfly", "egg, butterfly, pupa, caterpillar", "caterpillar, egg, butterfly, pupa", "pupa, egg, butterfly, caterpillar"],
    ["Science", "What is the term for an animal that sleeps through the winter?", "hibernating", "migrating", "evaporating", "pollinating"],
    ["Science", "What is it called when birds travel to warmer places for winter?", "migration", "hibernation", "evolution", "pollination"],
    ["Science", "What are fossils?", "the remains of living things preserved in rock", "new rocks", "pieces of metal", "drops of oil"],
    ["Science", "Which type of rock is formed from layers of sand and mud pressed together?", "sedimentary", "igneous", "metamorphic", "volcanic"],
    ["Science", "Which of these is a type of soil that holds water well?", "clay", "sand", "gravel", "pebbles"],
    ["Science", "What is the name for the solid outer layer of the Earth?", "the crust", "the core", "the ocean", "the cloud"],
    ["Maths", "What is 4 × 4?", "16", "20", "12", "6"],
    ["Maths", "What is 7 × 7?", "49", "56", "42", "45"],
    ["Maths", "What is 3 × 8?", "24", "27", "16", "28"],
    ["Maths", "What is 8 × 5?", "40", "48", "35", "38"],
    ["Maths", "What is 7 × 6?", "42", "49", "36", "47"],
    ["Maths", "What is 8 × 12?", "96", "104", "84", "92"],
    ["Maths", "What is 25 ÷ 5?", "5", "2", "3", "9"],
    ["Maths", "What is 9 ÷ 3?", "3", "8", "9", "5"],
    ["Maths", "What is 64 ÷ 8?", "8", "9", "7", "4"],
    ["Maths", "What is 108 ÷ 9?", "12", "11", "9", "7"],
    ["Maths", "What is 163 + 283?", "446", "546", "445", "386"],
    ["Maths", "What is 321 + 324?", "645", "745", "644", "545"],
    ["Maths", "What is 278 + 151?", "429", "529", "428", "369"],
    ["Maths", "What is 596 - 442?", "154", "254", "153", "174"],
    ["Maths", "What is 776 - 194?", "582", "682", "581", "562"],
    ["Maths", "What is 806 - 432?", "374", "474", "373", "404"],
    ["Maths", "What is the perimeter of a rectangle that is 8 cm long and 5 cm wide?", "26 cm", "28 cm", "40 cm", "22 cm"],
    ["Maths", "What is the perimeter of a rectangle that is 12 cm long and 7 cm wide?", "38 cm", "40 cm", "84 cm", "34 cm"],
    ["Maths", "What is the perimeter of a rectangle that is 9 cm long and 6 cm wide?", "30 cm", "32 cm", "54 cm", "26 cm"],
    ["Maths", "What is 1/4 of 24?", "6", "10", "18", "1"],
    ["Maths", "What is 1/5 of 40?", "8", "13", "32", "3"],
    ["Maths", "What is 467 rounded to the nearest 10?", "470", "460", "500", "480"],
    ["Maths", "What is 2,350 rounded to the nearest 100?", "2400", "2300", "2350", "2500"],
    ["Maths", "How many sides does a hexagon have?", "6", "5", "7", "8"],
    ["Maths", "How many degrees are there in a right angle?", "90", "45", "180", "60"],
    ["Maths", "What is 12 × 12?", "144", "134", "146", "141"],
    ["Maths", "What is 22 ÷ 2?", "11", "13", "22", "8"],
    ["Maths", "What is 329 + 323?", "652", "654", "642", "653"],
    ["Maths", "What is 479 - 302?", "177", "354", "172", "187"],
    ["Maths", "What is 9/10 of 60?", "54", "57", "108", "49"],
    ["Maths", "What is the area of a rectangle that is 8 cm long and 8 cm wide?", "64 cm²", "66 cm²", "61 cm²", "128 cm²"],
    ["Maths", "Which Roman numeral means 22?", "XXII", "XXXII", "XXIII", "XXI"],
    ["Maths", "How many seconds are there in 4 minutes?", "240", "250", "480", "245"],
    ["Maths", "A book costs £2.86 and a pen costs £3.15. How much do they cost altogether?", "£6.01", "£5.91", "£7.01", "£6.11"],
    ["Maths", "What is 0.75 × 2?", "1.5", "2.5", "2.0", "1.0"],
    ["Maths", "What is the next multiple of 9 after 31?", "36", "35", "37", "45"],
    ["Maths", "What number comes next? 16, 24, 32, 40, ...", "48", "46", "38", "44"],
    ["Maths", "Anya has 3 bags with 9 pencils in each bag. How many pencils does Anya have altogether?", "27", "29", "54", "37"],
    ["Maths", "What is 73 rounded to the nearest ten?", "70", "69", "71", "67"],
    ["Maths", "What is the name of a triangle with two equal sides?", "isosceles", "equilateral", "scalene", "right-angled"],
    ["Maths", "What is 11 squared (11 × 11)?", "121", "116", "126", "111"],
    ["Maths", "The temperature is 12°C and falls by 5 degrees. What is the new temperature?", "7°C", "8°C", "6°C", "3°C"],
    ["Maths", "What is 5 × 10?", "50", "49", "52", "100"],
    ["Maths", "What is 22 ÷ 11?", "2", "1", "7", "0"],
    ["Maths", "What is 617 + 130?", "747", "749", "737", "746"],
    ["Maths", "What is 557 - 347?", "210", "213", "208", "209"],
    ["Maths", "What is 2/5 of 25?", "10", "11", "20", "13"],
    ["Maths", "What is the area of a rectangle that is 11 cm long and 6 cm wide?", "66 cm²", "70 cm²", "71 cm²", "76 cm²"],
    ["Maths", "Which number is the Roman numeral XXIX?", "29", "28", "39", "30"],
    ["Maths", "How many minutes are there in 4 hours?", "240", "236", "243", "250"],
    ["Maths", "You buy 3 items that each cost £5. How much do you spend?", "£15", "£10", "£25", "£20"],
    ["Maths", "What is 0.9 + 0.2?", "1.1", "2.1", "1.0", "1.2"],
    ["Maths", "Which of these is a factor of 45?", "15", "4", "20", "16"],
    ["Maths", "What number comes next? 11, 22, 33, 44, ...", "55", "56", "51", "60"],
    ["Maths", "Leo shares 64 sweets equally between 8 friends. How many does each friend get?", "8", "4", "6", "16"],
    ["Maths", "What is 3,678 rounded to the nearest ten?", "3,680", "3,682", "3,683", "3,677"],
    ["Maths", "How many degrees are there in a straight line?", "180", "360", "100", "90"],
    ["Maths", "What is 6 squared (6 × 6)?", "36", "33", "32", "37"],
    ["Maths", "At night the temperature is -1°C. By day it rises by 6 degrees. What is the daytime temperature?", "5°C", "2°C", "-5°C", "15°C"],
    ["Maths", "What is 5 × 3?", "15", "5", "16", "25"],
    ["Maths", "What is 12 ÷ 6?", "2", "3", "4", "12"],
    ["Maths", "What is 168 + 151?", "319", "315", "329", "322"],
    ["Maths", "What is 515 - 266?", "249", "250", "254", "251"],
    ["Maths", "What is 6/10 of 30?", "18", "22", "21", "8"],
    ["Maths", "What is the area of a rectangle that is 5 cm long and 5 cm wide?", "25 cm²", "21 cm²", "20 cm²", "24 cm²"],
    ["Maths", "Which Roman numeral means 36?", "XXXVI", "XXXV", "XXXVII", "XLVI"],
    ["Maths", "How many months have 31 days?", "7", "8", "6", "5"],
    ["Maths", "A book costs £1.75 and a pen costs £2.32. How much do they cost altogether?", "£4.07", "£3.97", "£4.17", "£5.07"],
    ["Maths", "What is 1.2 + 3.4?", "4.6", "5.6", "4.5", "4.7"],
    ["Maths", "What is the next multiple of 6 after 31?", "36", "35", "37", "42"],
    ["Maths", "What number comes next? 24, 36, 48, 60, ...", "72", "67", "73", "69"],
    ["Maths", "Omar shares 72 shells equally between 9 friends. How many does each friend get?", "8", "13", "18", "16"],
    ["Maths", "What is 38 rounded to the nearest ten?", "40", "41", "39", "45"],
    ["Maths", "What do we call an angle between 90 and 180 degrees?", "obtuse", "reflex", "right", "acute"],
    ["Maths", "Which of these is a square number?", "16", "15", "18", "17"],
    ["Maths", "At night the temperature is -2°C. By day it rises by 5 degrees. What is the daytime temperature?", "3°C", "-1°C", "-2°C", "-7°C"],
    ["Maths", "What is 2 × 3?", "6", "2", "11", "7"],
    ["Maths", "What is 15 ÷ 5?", "3", "6", "5", "2"],
    ["Maths", "What is 551 + 279?", "830", "833", "828", "1,660"],
    ["Maths", "What is 638 - 154?", "484", "482", "479", "483"],
    ["Maths", "What is 2/5 of 15?", "6", "10", "1", "9"],
    ["Maths", "What is the area of a rectangle that is 3 cm long and 2 cm wide?", "6 cm²", "16 cm²", "2 cm²", "9 cm²"],
    ["Maths", "Which Roman numeral means 28?", "XXVIII", "XXIX", "XXXVIII", "XXVII"],
    ["Maths", "How many minutes are there in 3 hours?", "180", "360", "179", "183"],
    ["Maths", "You buy 4 items that each cost £20. How much do you spend?", "£80", "£100", "£90", "£60"],
    ["Maths", "Which is the fraction for the decimal 0.75?", "3/4", "2/5", "3/10", "3/5"],
    ["Maths", "What is the next multiple of 3 after 45?", "48", "47", "51", "49"],
    ["Maths", "What number comes next? 25, 50, 75, 100, ...", "125", "121", "135", "129"],
    ["Maths", "Finn shares 30 apples equally between 6 friends. How many does each friend get?", "5", "1", "3", "15"],
    ["Maths", "What is 5,421 rounded to the nearest hundred?", "5,400", "5,410", "5,390", "10,800"],
    ["Maths", "How many degrees are there in half a turn?", "180", "270", "90", "360"],
    ["Maths", "What is 9 squared (9 × 9)?", "81", "85", "83", "91"],
    ["Maths", "The temperature is 6°C and falls by 5 degrees. What is the new temperature?", "1°C", "4°C", "3°C", "-2°C"],
    ["Maths", "What is 6 × 12?", "72", "69", "76", "71"],
    ["Maths", "What is 49 ÷ 7?", "7", "4", "12", "10"],
    ["Maths", "What is 446 + 146?", "592", "1,184", "602", "596"],
    ["Maths", "What is 692 - 313?", "379", "378", "380", "377"],
    ["Maths", "What is 4/10 of 40?", "16", "26", "32", "18"],
    ["Maths", "What is the area of a rectangle that is 9 cm long and 5 cm wide?", "45 cm²", "50 cm²", "48 cm²", "35 cm²"],
    ["Maths", "Which number is the Roman numeral XIX?", "19", "18", "29", "20"],
    ["Geography", "What is the capital city of France?", "Paris", "Lyon", "Marseille", "Nice"],
    ["Geography", "Which is the longest river in Africa?", "the Nile", "the Amazon", "the Thames", "the Ganges"],
    ["Geography", "Which is the largest ocean?", "the Pacific Ocean", "the Atlantic Ocean", "the Indian Ocean", "the Arctic Ocean"],
    ["Geography", "On which continent is the Sahara Desert?", "Africa", "Asia", "Australia", "South America"],
    ["Geography", "What is the capital city of Japan?", "Tokyo", "Beijing", "Seoul", "Bangkok"],
    ["Geography", "Which mountain is the tallest above sea level?", "Mount Everest", "K2", "Kilimanjaro", "Mont Blanc"],
    ["Geography", "Which imaginary line divides the Earth into northern and southern halves?", "the Equator", "the Prime Meridian", "the horizon", "the Arctic Circle"],
    ["Geography", "How many continents are there?", "7", "5", "6", "8"],
    ["Geography", "What is the capital city of Italy?", "Rome", "Milan", "Venice", "Naples"],
    ["Geography", "Which country is shaped like a boot?", "Italy", "Spain", "Greece", "France"],
    ["Geography", "Which is the largest hot desert in the world?", "the Sahara", "the Gobi", "the Kalahari", "the Thar"],
    ["Geography", "Which is the largest country in the world by area?", "Russia", "Canada", "China", "the USA"],
    ["Geography", "Which sea lies between Europe and Africa?", "the Mediterranean Sea", "the Red Sea", "the Baltic Sea", "the Black Sea"],
    ["Geography", "In which country is the city of Cairo?", "Egypt", "Kenya", "India", "Peru"],
    ["Geography", "What is the capital city of Australia?", "Canberra", "Sydney", "Melbourne", "Perth"],
    ["Geography", "Which river flows through London?", "the Thames", "the Severn", "the Seine", "the Danube"],
    ["Geography", "Which continent is the coldest?", "Antarctica", "Asia", "Africa", "Europe"],
    ["Geography", "What comes out of a volcano when it erupts?", "lava", "snow", "sand", "rain"],
    ["Geography", "In which country do kangaroos live in the wild?", "Australia", "Brazil", "India", "Canada"],
    ["Geography", "Which is the smallest continent?", "Australia", "Europe", "Antarctica", "South America"],
    ["Geography", "What is the capital city of Canada?", "Ottawa", "Toronto", "Vancouver", "Montreal"],
    ["Geography", "Which ocean lies between Africa and Australia?", "the Indian Ocean", "the Atlantic Ocean", "the Arctic Ocean", "the Pacific Ocean"],
    ["Geography", "In which country is most of the Amazon rainforest?", "Brazil", "Argentina", "Mexico", "Chile"],
    ["Geography", "Which instrument do we use to find the direction we are heading?", "a compass", "a thermometer", "a barometer", "a telescope"],
    ["Geography", "What is the capital city of Spain?", "Madrid", "Barcelona", "Lisbon", "Seville"],
    ["Geography", "What is the capital city of Scotland?", "Edinburgh", "Glasgow", "Aberdeen", "Cardiff"],
    ["Geography", "What is the capital city of Wales?", "Cardiff", "Swansea", "Edinburgh", "Belfast"],
    ["Geography", "What is the capital city of Northern Ireland?", "Belfast", "Dublin", "Cardiff", "Derry"],
    ["Geography", "What is the capital city of Ireland?", "Dublin", "Belfast", "Cork", "Galway"],
    ["Geography", "What is the capital city of the United States of America?", "Washington, D.C.", "New York", "Los Angeles", "Chicago"],
    ["Geography", "What is the capital city of Germany?", "Berlin", "Munich", "Hamburg", "Vienna"],
    ["Geography", "What is the capital city of Egypt?", "Cairo", "Alexandria", "Luxor", "Giza"],
    ["Geography", "What is the capital city of India?", "New Delhi", "Mumbai", "Kolkata", "Chennai"],
    ["Geography", "What is the capital city of China?", "Beijing", "Shanghai", "Hong Kong", "Tokyo"],
    ["Geography", "What is the capital city of Greece?", "Athens", "Sparta", "Rome", "Istanbul"],
    ["Geography", "What is the capital city of Portugal?", "Lisbon", "Porto", "Madrid", "Seville"],
    ["Geography", "What is the capital city of the United Arab Emirates?", "Abu Dhabi", "Dubai", "Sharjah", "Doha"],
    ["Geography", "What is the capital city of Saudi Arabia?", "Riyadh", "Jeddah", "Mecca", "Dubai"],
    ["Geography", "What is the capital city of Brazil?", "Brasília", "Rio de Janeiro", "São Paulo", "Buenos Aires"],
    ["Geography", "What is the capital city of Kenya?", "Nairobi", "Mombasa", "Kampala", "Addis Ababa"],
    ["Geography", "What is the capital city of New Zealand?", "Wellington", "Auckland", "Sydney", "Christchurch"],
    ["Geography", "What is the capital city of Russia?", "Moscow", "Saint Petersburg", "Kyiv", "Minsk"],
    ["Geography", "What is the capital city of Mexico?", "Mexico City", "Cancún", "Acapulco", "Lima"],
    ["Geography", "What is the capital city of Norway?", "Oslo", "Bergen", "Stockholm", "Helsinki"],
    ["Geography", "What is the capital city of the Netherlands?", "Amsterdam", "Rotterdam", "The Hague", "Brussels"],
    ["Geography", "Which river flows through Paris?", "the Seine", "the Thames", "the Rhine", "the Danube"],
    ["Geography", "Which river flows through Cairo in Egypt?", "the Nile", "the Amazon", "the Ganges", "the Tigris"],
    ["Geography", "Which river is the longest in the United Kingdom?", "the River Severn", "the Thames", "the Tyne", "the Clyde"],
    ["Geography", "Which sea lies to the east of Great Britain?", "the North Sea", "the Irish Sea", "the Black Sea", "the Red Sea"],
    ["Geography", "Which sea lies between Great Britain and Ireland?", "the Irish Sea", "the North Sea", "the Baltic Sea", "the Arctic Sea"],
    ["Geography", "Which is the largest continent by area?", "Asia", "Africa", "Europe", "North America"],
    ["Geography", "Which continent is home to the Amazon rainforest?", "South America", "Africa", "Asia", "Australia"],
    ["Geography", "Which continent is the Sahara Desert in?", "Africa", "Asia", "Australia", "South America"],
    ["Geography", "Which is the second largest continent by area?", "Africa", "Europe", "Antarctica", "South America"],
    ["Geography", "Which ocean is between Europe and North America?", "the Atlantic Ocean", "the Pacific Ocean", "the Indian Ocean", "the Arctic Ocean"],
    ["Geography", "Which ocean is the smallest?", "the Arctic Ocean", "the Indian Ocean", "the Atlantic Ocean", "the Pacific Ocean"],
    ["Geography", "Which line of latitude is at 0 degrees?", "the Equator", "the Tropic of Cancer", "the Prime Meridian", "the Arctic Circle"],
    ["Geography", "Which imaginary line runs from the North Pole to the South Pole through Greenwich?", "the Prime Meridian", "the Equator", "the Tropic of Capricorn", "the Arctic Circle"],
    ["Geography", "What is the name of the highest mountain in the United Kingdom?", "Ben Nevis", "Snowdon", "Scafell Pike", "Mount Everest"],
    ["Geography", "What is the name of the highest mountain in Wales?", "Snowdon", "Ben Nevis", "Scafell Pike", "Skiddaw"],
    ["Geography", "Which mountain range separates France and Spain?", "the Pyrenees", "the Alps", "the Andes", "the Rockies"],
    ["Geography", "Which mountain range is found in South America?", "the Andes", "the Alps", "the Himalayas", "the Rockies"],
    ["Geography", "Which mountain range includes Mount Everest?", "the Himalayas", "the Alps", "the Andes", "the Rockies"],
    ["Geography", "Which of these countries has a population of over one billion people?", "China", "Canada", "Brazil", "Australia"],
    ["Geography", "Which is the smallest country in the world?", "Vatican City", "Monaco", "Malta", "Luxembourg"],
    ["Geography", "Which country is famous for tulips and windmills?", "the Netherlands", "Spain", "Egypt", "Kenya"],
    ["Geography", "Which country is known as the Land of the Rising Sun?", "Japan", "China", "India", "Thailand"],
    ["Geography", "Which country is famous for the Great Barrier Reef?", "Australia", "Canada", "India", "Brazil"],
    ["Geography", "Which country is known for the fjords in its north-west coast?", "Norway", "Spain", "Egypt", "Greece"],
    ["Geography", "In which country would you find the Colosseum?", "Italy", "Greece", "Spain", "France"],
    ["Geography", "In which country would you find the Parthenon?", "Greece", "Italy", "Egypt", "Turkey"],
    ["Geography", "In which country would you find the Pyramids of Giza?", "Egypt", "Mexico", "Peru", "India"],
    ["Geography", "In which country would you find Machu Picchu?", "Peru", "Mexico", "Spain", "Egypt"],
    ["Geography", "In which country would you find the city of Istanbul?", "Turkey", "Greece", "Egypt", "Italy"],
    ["Geography", "In which country would you find Sydney Opera House?", "Australia", "New Zealand", "Canada", "the United Kingdom"],
    ["Geography", "In which country would you find the Statue of Liberty?", "the USA", "Canada", "England", "Mexico"],
    ["Geography", "Which country has the maple leaf on its flag?", "Canada", "Australia", "Ireland", "New Zealand"],
    ["Geography", "What is the largest island in the world (not counting continents)?", "Greenland", "Australia", "Madagascar", "Iceland"],
    ["Geography", "Which type of energy comes from the Sun?", "solar", "wind", "wave", "tidal"],
    ["Geography", "What do we call the layer of soil on the very top of the ground?", "topsoil", "bedrock", "magma", "crust"],
    ["Geography", "What is the name for a large area of ice that moves slowly down a valley?", "a glacier", "a river", "a lake", "a waterfall"],
    ["Geography", "What do we call the place where a river meets the sea?", "the mouth", "the source", "the bank", "the tributary"],
    ["Geography", "What do we call the place where a river begins?", "the source", "the mouth", "the delta", "the estuary"],
    ["Geography", "What do we call a smaller river that joins a bigger river?", "a tributary", "a delta", "a source", "a lake"],
    ["Geography", "What is the name for a tall wave caused by an undersea earthquake?", "a tsunami", "a monsoon", "a tornado", "a hurricane"],
    ["Geography", "What is a hurricane?", "a violent tropical storm with strong winds", "a gentle breeze", "a type of rain", "a dry spell"],
    ["Geography", "What instrument measures the temperature?", "a thermometer", "a barometer", "a ruler", "a compass"],
    ["Geography", "What instrument measures rainfall?", "a rain gauge", "a thermometer", "a compass", "a clock"],
    ["Geography", "What do we call a wind that blows in from the sea in daytime?", "a sea breeze", "a monsoon", "a tornado", "a trade wind"],
    ["Geography", "Which season comes after summer in the UK?", "autumn", "winter", "spring", "summer again"],
    ["Geography", "What do we call very hot dry weather lasting a long time with little rain?", "a drought", "a flood", "a blizzard", "a storm"],
    ["Geography", "What do we call the money used in the United Kingdom?", "the pound", "the euro", "the dollar", "the yen"],
    ["Geography", "What do we call the money used in many European countries such as France and Germany?", "the euro", "the pound", "the dollar", "the rupee"],
    ["Geography", "Which of these is a form of renewable energy?", "solar power", "coal", "oil", "natural gas"],
    ["Geography", "What is recycling?", "using materials again to make new things", "burning rubbish", "burying rubbish", "throwing things in the sea"],
    ["Geography", "What is the name of the tallest waterfall in the world, found in Venezuela?", "Angel Falls", "Niagara Falls", "Victoria Falls", "Iguazu Falls"],
    ["Geography", "What is the capital city of Thailand?", "Bangkok", "Phuket", "Hanoi", "Manila"],
    ["Geography", "What is the capital city of Pakistan?", "Islamabad", "Karachi", "Lahore", "Dhaka"],
    ["Geography", "What is the capital city of Switzerland?", "Bern", "Zurich", "Geneva", "Vienna"],
    ["Geography", "What is the capital city of Sweden?", "Stockholm", "Gothenburg", "Oslo", "Copenhagen"],
    ["History", "Which people built the pyramids at Giza?", "the ancient Egyptians", "the Romans", "the Vikings", "the Greeks"],
    ["History", "Who sailed across the Atlantic and reached the Americas in 1492?", "Christopher Columbus", "Captain Cook", "Marco Polo", "Ferdinand Magellan"],
    ["History", "In which country did the ancient Olympic Games begin?", "Greece", "Italy", "Egypt", "France"],
    ["History", "How many wives did King Henry VIII have?", "6", "4", "8", "2"],
    ["History", "What did the Romans build to carry water to their cities?", "aqueducts", "skyscrapers", "railways", "windmills"],
    ["History", "Who was the first person to walk on the Moon?", "Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "Michael Collins"],
    ["History", "In which year did the Second World War end?", "1945", "1918", "1939", "1960"],
    ["History", "In which year was the Great Fire of London?", "1666", "1066", "1766", "1566"],
    ["History", "Who invented the telephone?", "Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Isaac Newton"],
    ["History", "Which people invaded England in 1066?", "the Normans", "the Romans", "the Greeks", "the Egyptians"],
    ["History", "Who led India to independence using peaceful protest?", "Mahatma Gandhi", "Winston Churchill", "Nelson Mandela", "Abraham Lincoln"],
    ["History", "Which ship sank in 1912 after hitting an iceberg?", "the Titanic", "the Mayflower", "the Victory", "the Endeavour"],
    ["History", "Who painted the Mona Lisa?", "Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Claude Monet"],
    ["History", "What was the name of the ship the Pilgrims sailed to America in 1620?", "the Mayflower", "the Titanic", "the Santa Maria", "the Golden Hind"],
    ["History", "Who was Tutankhamun?", "an Egyptian pharaoh", "a Roman emperor", "a Greek philosopher", "a Viking king"],
    ["History", "Who ruled the Roman Empire?", "emperors", "pharaohs", "samurai", "pirates"],
    ["History", "Which wall did the Romans build in the north of Britain?", "Hadrian's Wall", "the Berlin Wall", "the Great Wall of China", "the Wailing Wall"],
    ["History", "Who was the first female Prime Minister of the United Kingdom?", "Margaret Thatcher", "Theresa May", "Queen Victoria", "Elizabeth II"],
    ["History", "Who was the first President of the United States?", "George Washington", "Abraham Lincoln", "Thomas Jefferson", "John Adams"],
    ["History", "Which scientist is famous for the story of the falling apple and gravity?", "Isaac Newton", "Galileo Galilei", "Albert Einstein", "Charles Darwin"],
    ["History", "In which century did the Wright brothers make the first powered aeroplane flight?", "the 20th century", "the 19th century", "the 18th century", "the 21st century"],
    ["History", "Who were gladiators in ancient Rome?", "fighters who entertained crowds", "doctors", "farmers", "sailors"],
    ["History", "Which civilisation built the mountain city of Machu Picchu?", "the Inca", "the Aztec", "the Romans", "the Vikings"],
    ["History", "Who wrote the play Romeo and Juliet?", "William Shakespeare", "Charles Dickens", "Roald Dahl", "Jane Austen"],
    ["History", "What were the tools of Stone Age people mostly made from?", "stone", "plastic", "steel", "aluminium"],
    ["History", "Which ancient civilisation built the Parthenon?", "the ancient Greeks", "the Romans", "the Egyptians", "the Vikings"],
    ["History", "In which city were the first modern Olympic Games held in 1896?", "Athens", "Paris", "London", "Rome"],
    ["History", "Who was the Greek god of the sea in ancient myths?", "Poseidon", "Zeus", "Hades", "Apollo"],
    ["History", "Who was the king of the gods in ancient Greek myths?", "Zeus", "Poseidon", "Hades", "Ares"],
    ["History", "Which Roman emperor built a wall across the north of England?", "Hadrian", "Nero", "Augustus", "Caligula"],
    ["History", "What was the name of the Roman army's basic fighting unit of about 5,000 soldiers?", "a legion", "a platoon", "a squadron", "a fleet"],
    ["History", "Which Celtic queen led a rebellion against the Romans in Britain?", "Boudica", "Cleopatra", "Elizabeth I", "Victoria"],
    ["History", "What did Romans use to heat their baths and floors?", "a hypocaust", "a chimney only", "a candle", "a stove only"],
    ["History", "Which volcano erupted in AD 79 and buried the Roman town of Pompeii?", "Mount Vesuvius", "Mount Etna", "Mount Fuji", "Krakatoa"],
    ["History", "What were Roman houses' central open courtyards called?", "an atrium", "a forum", "an arena", "a villa"],
    ["History", "What is the name for an ancient Roman public square?", "a forum", "an atrium", "an amphitheatre", "a temple"],
    ["History", "Which people invaded Britain after the Romans left, including Angles and Saxons?", "the Anglo-Saxons", "the Normans", "the Greeks", "the Egyptians"],
    ["History", "What is the name of Thor's hammer in Viking myths?", "Mjölnir", "Excalibur", "Gungnir", "the Trident"],
    ["History", "What kind of building did the Vikings raid at Lindisfarne in AD 793?", "a monastery", "a castle", "a market", "a lighthouse"],
    ["History", "What was the name of King Alfred's kingdom, where he fought the Vikings?", "Wessex", "Mercia", "Northumbria", "Cornwall"],
    ["History", "Who became the King of England after the Battle of Hastings in 1066?", "William the Conqueror", "Harold Godwinson", "King Alfred", "Henry VIII"],
    ["History", "What famous tapestry shows the story of the Norman invasion of England?", "the Bayeux Tapestry", "the Lindisfarne Gospels", "the Domesday Book", "the Magna Carta"],
    ["History", "What was the Domesday Book?", "a survey of land and people in England", "a book of spells", "a story of King Arthur", "a book of maps only"],
    ["History", "What was the name of the sickness that killed millions of people in Europe in the 1300s?", "the Black Death", "the Great Fire", "the Spanish flu", "chickenpox"],
    ["History", "Which animal's fleas helped spread the Black Death?", "rats", "cats", "dogs", "horses"],
    ["History", "Who was the English king forced to sign the Magna Carta in 1215?", "King John", "King Henry VIII", "King Alfred", "King Richard III"],
    ["History", "What is the name of the war between the houses of Lancaster and York?", "the Wars of the Roses", "the Hundred Years' War", "the Crusades", "the Civil War"],
    ["History", "Which Tudor queen ruled England for 45 years from 1558?", "Elizabeth I", "Mary I", "Victoria", "Anne"],
    ["History", "Which Tudor king broke away from the Catholic Church in Rome?", "Henry VIII", "Henry VII", "Edward VI", "Richard III"],
    ["History", "What name is given to the ships sent by Spain in 1588 to invade England?", "the Spanish Armada", "the Mayflower", "the Golden Hind", "the Victory"],
    ["History", "Which English sailor was the first to sail around the world, in the Golden Hind?", "Francis Drake", "Walter Raleigh", "Christopher Columbus", "James Cook"],
    ["History", "Which playwright wrote 'Macbeth' and 'Hamlet'?", "William Shakespeare", "Charles Dickens", "Jane Austen", "Roald Dahl"],
    ["History", "What was the name of Shakespeare's theatre in London?", "the Globe", "the Palladium", "the Colosseum", "the Odeon"],
    ["History", "Who tried to blow up the Houses of Parliament in 1605?", "Guy Fawkes", "Oliver Cromwell", "Robin Hood", "Francis Drake"],
    ["History", "Who was Charles I's opponent in the English Civil War?", "Oliver Cromwell", "Walter Raleigh", "Guy Fawkes", "Francis Drake"],
    ["History", "In which year did the Great Fire of London burn the city?", "1666", "1066", "1805", "1914"],
    ["History", "Which famous diary writer described the Great Fire of London?", "Samuel Pepys", "Charles Dickens", "Anne Frank", "William Shakespeare"],
    ["History", "Who designed the new St Paul's Cathedral after the Great Fire of London?", "Christopher Wren", "Isaac Newton", "Capability Brown", "Inigo Jones"],
    ["History", "What is the name of the period of change when machines and factories took over from hand-made goods?", "the Industrial Revolution", "the Renaissance", "the Stone Age", "the Middle Ages"],
    ["History", "Which Victorian engineer built the Great Western Railway and ships like the SS Great Britain?", "Isambard Kingdom Brunel", "George Stephenson", "James Watt", "Thomas Telford"],
    ["History", "Who built the famous steam locomotive 'Rocket'?", "George and Robert Stephenson", "Isambard Brunel", "James Watt", "Richard Trevithick"],
    ["History", "Who was the British queen for most of the 1800s, giving her name to an age?", "Queen Victoria", "Queen Elizabeth I", "Queen Anne", "Queen Mary"],
    ["History", "Which Victorian author wrote 'Oliver Twist' and 'A Christmas Carol'?", "Charles Dickens", "Jane Austen", "Lewis Carroll", "Rudyard Kipling"],
    ["History", "What was the name of the first ever adhesive postage stamp, issued in 1840?", "the Penny Black", "the Penny Red", "the Blue Mauritius", "the Two Penny Blue"],
    ["History", "In which year did the First World War begin?", "1914", "1939", "1918", "1905"],
    ["History", "What was the name given to the long lines of ditches soldiers lived in during the First World War?", "trenches", "tunnels", "barracks", "bunkers"],
    ["History", "On which date is Armistice (Remembrance) Day marked each year?", "11th November", "25th December", "1st January", "5th November"],
    ["History", "Who was the British Prime Minister for most of the Second World War?", "Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Margaret Thatcher"],
    ["History", "What was the name given to the evacuation of children from British cities in the Second World War?", "Operation Pied Piper", "Operation Overlord", "Operation Dynamo", "Operation Sealion"],
    ["History", "What was the evacuation of British soldiers from the beaches in 1940 called?", "Dunkirk", "D-Day", "Waterloo", "Trafalgar"],
    ["History", "Which battle in 1940 was fought in the skies above Britain?", "the Battle of Britain", "the Battle of Hastings", "the Battle of Waterloo", "the Battle of the Somme"],
    ["History", "Which girl wrote a famous diary while hiding in Amsterdam during the Second World War?", "Anne Frank", "Marie Curie", "Mary Seacole", "Florence Nightingale"],
    ["History", "Who was the first woman to fly solo across the Atlantic Ocean?", "Amelia Earhart", "Amy Johnson", "Bessie Coleman", "Jean Batten"],
    ["History", "Who was the first man to reach the South Pole in 1911?", "Roald Amundsen", "Robert Falcon Scott", "Ernest Shackleton", "Edmund Hillary"],
    ["History", "Who were the first two people to reach the summit of Mount Everest in 1953?", "Edmund Hillary and Tenzing Norgay", "Neil Armstrong and Buzz Aldrin", "Robert Scott and Roald Amundsen", "Marco Polo and Ibn Battuta"],
    ["History", "Which explorer is famous for travelling to China along the Silk Road in the 13th century?", "Marco Polo", "Vasco da Gama", "James Cook", "Ferdinand Magellan"],
    ["History", "Which Italian explorer reached the Caribbean in 1492?", "Christopher Columbus", "Marco Polo", "Vasco da Gama", "Francis Drake"],
    ["History", "Which explorer's expedition was the first to sail around the world, completed after his death?", "Ferdinand Magellan", "Christopher Columbus", "James Cook", "Vasco da Gama"],
    ["History", "Which British explorer charted the coast of eastern Australia in 1770?", "James Cook", "Francis Drake", "Walter Raleigh", "Henry Hudson"],
    ["History", "Which empire built the cities of Tenochtitlan, in what is now Mexico?", "the Aztecs", "the Mayans", "the Incas", "the Romans"],
    ["History", "Which ancient civilisation is famous for building the city of Machu Picchu in the Andes?", "the Inca", "the Aztecs", "the Mayans", "the Olmecs"],
    ["History", "Which empire was ruled by Genghis Khan?", "the Mongol Empire", "the Roman Empire", "the Ottoman Empire", "the British Empire"],
    ["History", "Which ancient people invented hieroglyphs?", "the Egyptians", "the Romans", "the Greeks", "the Vikings"],
    ["History", "What was found inside the Great Pyramids, hidden for the pharaohs?", "burial chambers", "gold mines", "castles", "theatres"],
    ["History", "What did the ancient Egyptians do to preserve dead bodies?", "mummification", "burning", "freezing", "drying in the sun only"],
    ["History", "What was the name of the stone that helped scholars understand Egyptian hieroglyphs?", "the Rosetta Stone", "the Blarney Stone", "the Stone of Scone", "the Sphinx"],
    ["History", "Which Egyptian pharaoh's tomb was discovered by Howard Carter in 1922?", "Tutankhamun", "Ramesses II", "Khufu", "Cleopatra"],
    ["History", "What did the ancient Greeks call their city-states?", "polis", "empire", "province", "legion"],
    ["History", "Which Greek philosopher taught Alexander the Great?", "Aristotle", "Socrates", "Plato", "Homer"],
    ["History", "Which great king of Macedonia conquered much of the known world by the age of 30?", "Alexander the Great", "Julius Caesar", "Genghis Khan", "Napoleon"],
    ["History", "What is the name of the long poem by Homer about the Trojan War?", "the Iliad", "the Aeneid", "Paradise Lost", "Beowulf"],
    ["History", "What was the Trojan Horse in the Greek legend?", "a wooden horse used to enter a city", "a famous racehorse", "a Roman battle ship", "a ship of gold"],
    ["History", "Which Chinese dynasty built much of the Great Wall that survives today?", "the Ming dynasty", "the Han dynasty", "the Tang dynasty", "the Qing dynasty"],
    ["History", "What was invented in China around the 2nd century, made from plant fibres, and later spread across the world?", "paper", "the telephone", "the telescope", "the steam engine"],
    ["History", "Which Indian leader led peaceful protests against British rule?", "Mahatma Gandhi", "Jawaharlal Nehru", "Nelson Mandela", "Martin Luther King"],
    ["History", "Who was the US civil rights leader who gave the 'I Have a Dream' speech?", "Martin Luther King Jr.", "Malcolm X", "Barack Obama", "Nelson Mandela"],
    ["History", "Which woman refused to give up her seat on a bus in 1955, sparking protests in the USA?", "Rosa Parks", "Harriet Tubman", "Sojourner Truth", "Maya Angelou"],
    ["History", "Who was released from prison in 1990 and became South Africa's president?", "Nelson Mandela", "Desmond Tutu", "Steve Biko", "Thabo Mbeki"],
    ["History", "Which American president ended slavery, with the Emancipation Proclamation?", "Abraham Lincoln", "George Washington", "Thomas Jefferson", "Theodore Roosevelt"],
    ["History", "Which Roman general led an invasion of Britain in 55 BC?", "Julius Caesar", "Augustus", "Nero", "Hadrian"],
];
