export type AgeBand = '5-7' | '8-10' | '11-13' | '14-17';

export type PuzzleSubject = 'English' | 'Science' | 'Maths' | 'Geography' | 'History';

export interface Puzzle {
    subject: PuzzleSubject;
    question: string;
    options: [string, string, string, string];
    answer: string;
}

type PuzzleRow = [PuzzleSubject, string, string, string, string, string];

const toPuzzles = (rows: PuzzleRow[]): Puzzle[] => rows.map(([subject, question, answer, ...wrong]) => ({
    subject,
    question,
    answer,
    options: [answer, ...wrong] as Puzzle['options'],
}));

export const AGE_BANDS: AgeBand[] = ['5-7', '8-10', '11-13', '14-17'];

const AGE_5_TO_7: PuzzleRow[] = [
    ["English", "Which word rhymes with \"cat\"?", "hat", "dog", "bed", "cup"],
    ["English", "What is the opposite of \"big\"?", "small", "tall", "wide", "loud"],
    ["English", "Which of these words begins with the letter B?", "ball", "cat", "dog", "fish"],
    ["English", "How many letters are there in the English alphabet?", "26", "24", "20", "30"],
    ["English", "What is the plural of \"dog\"?", "dogs", "doges", "dogies", "dogz"],
    ["English", "Which of these is a colour?", "green", "chair", "jump", "book"],
    ["English", "Which word means \"not wet\"?", "dry", "cold", "hot", "soft"],
    ["English", "Which sentence is written correctly?", "The cat sat on the mat.", "Cat the on sat mat.", "Sat cat mat the on.", "On the mat sat cat the."],
    ["English", "What goes at the end of a telling sentence?", "a full stop", "a question mark", "a star", "a tick"],
    ["English", "Which word rhymes with \"tree\"?", "bee", "car", "sun", "pen"],
    ["English", "Which of these letters is a vowel?", "e", "b", "k", "t"],
    ["English", "What is the opposite of \"hot\"?", "cold", "wet", "slow", "soft"],
    ["English", "Which animal's name begins with the letter S?", "snake", "rabbit", "frog", "lion"],
    ["English", "What is the opposite of \"up\"?", "down", "left", "red", "fast"],
    ["English", "Which of these is a \"doing\" word?", "run", "table", "blue", "happy"],
    ["English", "Which of these is a naming word (a noun)?", "dog", "jump", "quickly", "green"],
    ["English", "How many claps (syllables) are in the word \"banana\"?", "3", "1", "2", "4"],
    ["English", "Which word rhymes with \"sun\"?", "run", "sit", "pig", "tap"],
    ["English", "Which word is spelled correctly?", "friend", "freind", "frend", "frind"],
    ["English", "What is a baby cat called?", "a kitten", "a puppy", "a cub", "a calf"],
    ["English", "Which word means the same as \"happy\"?", "glad", "sad", "angry", "tired"],
    ["English", "Which word starts with the \"sh\" sound?", "ship", "cat", "dog", "mat"],
    ["English", "What is the first letter of the alphabet?", "A", "B", "Z", "M"],
    ["English", "Which of these is a describing word (an adjective)?", "tall", "run", "house", "and"],
    ["English", "Where would you go to borrow lots of books?", "a library", "a bakery", "a garage", "a farm"],
    ["Science", "What do plants need to grow?", "water and sunlight", "sweets and chocolate", "music and toys", "sand and stones"],
    ["Science", "How many legs does a spider have?", "8", "6", "4", "10"],
    ["Science", "What sound does a cow make?", "moo", "quack", "woof", "baa"],
    ["Science", "Which of these animals can fly?", "a bird", "a dog", "a fish", "a horse"],
    ["Science", "What gives us heat and light in the daytime?", "the Sun", "the Moon", "a cloud", "a rainbow"],
    ["Science", "Which of these is a liquid?", "water", "rock", "wood", "glass"],
    ["Science", "How many legs does a dog have?", "4", "2", "6", "8"],
    ["Science", "Which part of your body do you use to see?", "your eyes", "your ears", "your nose", "your hands"],
    ["Science", "Which season is the coldest?", "winter", "summer", "spring", "autumn"],
    ["Science", "What do fish use to breathe underwater?", "gills", "wings", "legs", "hair"],
    ["Science", "What does a caterpillar turn into?", "a butterfly", "a beetle", "a bee", "a bird"],
    ["Science", "Which of these animals lives in the sea?", "a shark", "a lion", "a cow", "a rabbit"],
    ["Science", "What do we call frozen water?", "ice", "steam", "smoke", "sand"],
    ["Science", "What colour do you make by mixing blue and yellow?", "green", "purple", "orange", "pink"],
    ["Science", "What do bees make?", "honey", "milk", "bread", "butter"],
    ["Science", "How many senses do humans have (sight, hearing, smell, taste and touch)?", "5", "3", "7", "10"],
    ["Science", "Which part of your body do you use to smell?", "your nose", "your knees", "your elbows", "your hair"],
    ["Science", "What is a baby frog called?", "a tadpole", "a kitten", "a chick", "a lamb"],
    ["Science", "What falls from the clouds when it rains?", "water", "sand", "paper", "milk"],
    ["Science", "What is a baby sheep called?", "a lamb", "a calf", "a foal", "a cub"],
    ["Science", "Which of these animals lays eggs?", "a hen", "a dog", "a cat", "a horse"],
    ["Science", "What shape is the Earth?", "like a ball (a sphere)", "flat like a plate", "like a cube", "like a pyramid"],
    ["Science", "Which animal gives us milk?", "a cow", "a hen", "a fish", "a frog"],
    ["Science", "What do we need to breathe?", "air", "sand", "juice", "grass"],
    ["Science", "In which season do the leaves fall off the trees?", "autumn", "spring", "summer", "winter"],
    ["Geography", "Which of these is the biggest?", "an ocean", "a pond", "a puddle", "a stream"],
    ["Geography", "What colour is the sea usually shown on a map?", "blue", "red", "yellow", "brown"],
    ["Geography", "Which of these is a continent?", "Africa", "London", "the Nile", "Everest"],
    ["Geography", "What do we call a very tall hill?", "a mountain", "a puddle", "a beach", "a pond"],
    ["Geography", "What do we call land with water all around it?", "an island", "a desert", "a hill", "a forest"],
    ["Geography", "Which place is very hot and dry with lots of sand?", "a desert", "a lake", "a river", "a mountain"],
    ["Geography", "Which animal lives at the North Pole?", "a polar bear", "a lion", "a camel", "a monkey"],
    ["Geography", "What flows along to reach the sea?", "a river", "a hill", "a road", "a tree"],
    ["Geography", "What do we use a map for?", "finding places", "baking cakes", "sleeping", "singing"],
    ["Geography", "Which of these is a type of weather?", "rain", "pencil", "table", "milk"],
    ["Geography", "Which direction is the opposite of north?", "south", "east", "west", "up"],
    ["Geography", "Which sandy place is beside the sea?", "a beach", "a forest", "a farm", "a mountain"],
    ["Geography", "What shape is a globe?", "a ball (a sphere)", "a cube", "a triangle", "a square"],
    ["Geography", "When do we need an umbrella?", "when it is rainy", "when it is sunny", "when it is hot", "when it is clear"],
    ["Geography", "What is at the very top of the world called?", "the North Pole", "the South Pole", "the Equator", "the Sahara"],
    ["Geography", "Which animal lives on the African savannah?", "a lion", "a polar bear", "a penguin", "a seal"],
    ["Geography", "Where do penguins live?", "Antarctica", "the desert", "the jungle", "the city"],
    ["Geography", "What is the name of the planet we live on?", "Earth", "Mars", "the Moon", "the Sun"],
    ["Geography", "In which direction does the Sun rise?", "east", "west", "north", "south"],
    ["Geography", "What do we call a very big area full of trees?", "a forest", "a pond", "a beach", "a road"],
    ["Geography", "What do we call water falling over a high cliff?", "a waterfall", "a wave", "a puddle", "a bubble"],
    ["Geography", "Which place is the coldest?", "the North Pole", "a desert", "a beach", "a jungle"],
    ["Geography", "Where do aeroplanes take off from?", "an airport", "a farm", "a beach", "a school"],
    ["Geography", "Which of these is a country?", "Japan", "Paris", "Everest", "the Pacific"],
    ["Geography", "What is the capital city of England?", "London", "Paris", "Rome", "Cairo"],
    ["History", "Long ago, who lived in castles?", "kings and queens", "astronauts", "footballers", "robots"],
    ["History", "When did dinosaurs live?", "millions of years ago", "last year", "yesterday", "next week"],
    ["History", "Which is older?", "a horse and cart", "a car", "a rocket", "a helicopter"],
    ["History", "What did people use for light before electric lights?", "candles and oil lamps", "mobile phones", "televisions", "computers"],
    ["History", "Who wore armour long ago?", "knights", "doctors", "bakers", "teachers"],
    ["History", "In which country can you see the famous Great Pyramids?", "Egypt", "Canada", "Norway", "Peru"],
    ["History", "What did the ancient Egyptians write with?", "pictures called hieroglyphs", "emojis", "emails", "text messages"],
    ["History", "What do we call a big old stone building where kings and knights lived?", "a castle", "an igloo", "a tent", "a shed"],
    ["History", "Who was the first person to walk on the Moon?", "Neil Armstrong", "Isaac Newton", "Albert Einstein", "Charles Darwin"],
    ["History", "In which month do people celebrate Christmas?", "December", "June", "March", "August"],
    ["History", "What did pirates sail on?", "ships", "trains", "buses", "bicycles"],
    ["History", "How did people travel before there were cars?", "by horse and cart", "by rocket", "by scooter", "by helicopter"],
    ["History", "What did knights ride?", "horses", "elephants", "bicycles", "tractors"],
    ["History", "What does a museum show us?", "old things from the past", "cartoons", "cakes", "toys to buy"],
    ["History", "Who was the Queen of England for a very long time until 2022?", "Queen Elizabeth II", "Queen Victoria", "Queen Anne", "Queen Mary"],
    ["History", "What were the ancient Romans famous for building?", "roads", "skyscrapers", "airports", "rockets"],
    ["History", "Which came first?", "dinosaurs", "castles", "cars", "mobile phones"],
    ["History", "What did the Vikings sail in?", "longships", "submarines", "hot air balloons", "steamboats"],
    ["History", "How did people cook long ago, before cookers?", "over a fire", "in a microwave", "in an air fryer", "on an induction hob"],
    ["History", "What do we call a person who digs up old things from the ground to learn about the past?", "an archaeologist", "an astronaut", "a chef", "a pilot"],
    ["History", "Which animal did the ancient Egyptians treat as special and sacred?", "cats", "penguins", "kangaroos", "polar bears"],
    ["History", "What does a king wear on his head?", "a crown", "a helmet", "a scarf", "a cap"],
    ["History", "What carried astronauts to the Moon?", "a rocket", "a bus", "a boat", "a train"],
    ["History", "What did the ancient Romans wear?", "togas", "jeans", "trainers", "hoodies"],
    ["History", "Which of these people lived in a castle long ago?", "a knight", "a pilot", "a footballer", "a vlogger"],
    ["Maths", "What is 2 + 6?", "8", "9", "12", "10"],
    ["Maths", "What is 4 + 1?", "5", "0", "10", "2"],
    ["Maths", "What is 5 + 6?", "11", "9", "12", "1"],
    ["Maths", "What is 5 + 1?", "6", "8", "10", "7"],
    ["Maths", "What is 9 + 8?", "17", "21", "15", "19"],
    ["Maths", "What is 7 + 8?", "15", "16", "25", "19"],
    ["Maths", "What is 4 + 5?", "9", "5", "3", "6"],
    ["Maths", "What is 7 + 9?", "16", "14", "22", "21"],
    ["Maths", "What is 16 - 8?", "8", "10", "9", "14"],
    ["Maths", "What is 11 - 1?", "10", "7", "14", "4"],
    ["Maths", "What is 12 - 1?", "11", "21", "5", "12"],
    ["Maths", "What is 20 - 3?", "17", "11", "18", "15"],
    ["Maths", "What is 11 - 7?", "4", "7", "6", "10"],
    ["Maths", "What is double 3?", "6", "7", "1", "4"],
    ["Maths", "What is double 5?", "10", "13", "6", "12"],
    ["Maths", "What is double 6?", "12", "8", "7", "17"],
    ["Maths", "What is double 8?", "16", "17", "22", "14"],
    ["Maths", "What is half of 10?", "5", "1", "4", "6"],
    ["Maths", "What is half of 14?", "7", "17", "10", "11"],
    ["Maths", "What is half of 8?", "4", "14", "9", "0"],
    ["Maths", "What number comes next? 2, 4, 6, 8, ...", "10", "12", "9", "5"],
    ["Maths", "What number comes next? 5, 10, 15, 20, ...", "25", "30", "24", "28"],
    ["Maths", "What number comes next? 10, 20, 30, 40, ...", "50", "60", "49", "54"],
    ["Maths", "How many sides does a triangle have?", "3", "4", "5", "2"],
    ["Maths", "How many days are there in a week?", "7", "5", "6", "8"],
];

const AGE_8_TO_10: PuzzleRow[] = [
    ["English", "Which word is a synonym (means the same) of \"big\"?", "large", "tiny", "thin", "quiet"],
    ["English", "In the sentence \"The dog barked noisily\", which word is the adverb?", "noisily", "dog", "barked", "The"],
    ["English", "What is the plural of \"child\"?", "children", "childs", "childes", "childrens"],
    ["English", "What is the past tense of \"run\"?", "ran", "runned", "running", "runs"],
    ["English", "Which punctuation mark ends a question?", "a question mark", "a full stop", "a comma", "an apostrophe"],
    ["English", "What is the opposite of \"ancient\"?", "modern", "old", "historic", "dusty"],
    ["English", "Which word is spelled correctly?", "because", "becuase", "becaus", "becase"],
    ["English", "What is a simile?", "a comparison using \"like\" or \"as\"", "two words that rhyme", "a word that sounds like its meaning", "a very short story"],
    ["English", "\"As busy as a bee\" is an example of what?", "a simile", "alliteration", "onomatopoeia", "a rhyme"],
    ["English", "Which of these words is an example of onomatopoeia?", "buzz", "table", "quiet", "green"],
    ["English", "Which of these is a proper noun?", "London", "city", "river", "town"],
    ["English", "What is the opposite of \"generous\"?", "mean", "kind", "giving", "friendly"],
    ["English", "Which word is spelled correctly?", "separate", "seperate", "separete", "seprate"],
    ["English", "What is the contraction of \"do not\"?", "don't", "do'nt", "dont'", "d'not"],
    ["English", "What is the plural of \"mouse\" (the animal)?", "mice", "mouses", "mices", "mouse"],
    ["English", "Which word is the verb in \"The children play in the park\"?", "play", "children", "park", "the"],
    ["English", "What do we call a word that means the same as another word?", "a synonym", "an antonym", "a homophone", "an acronym"],
    ["English", "Which word sounds the same as \"their\" but means \"in that place\"?", "there", "the", "them", "three"],
    ["English", "Which sentence is correct?", "We were happy.", "We was happy.", "We is happy.", "We be happy."],
    ["English", "What do we call a word that has the opposite meaning of another word?", "an antonym", "a synonym", "an acronym", "a prefix"],
    ["English", "Which prefix turns \"happy\" into its opposite?", "un-", "re-", "pre-", "-ful"],
    ["English", "What do we call the story of a real person's life, written by someone else?", "a biography", "a fable", "a diary", "a recipe"],
    ["English", "A fable usually ends with what?", "a moral (a lesson)", "a recipe", "a map", "a song"],
    ["English", "Which of these is a conjunction (a joining word)?", "but", "quickly", "table", "red"],
    ["English", "Which word completes the sentence? \"The children left ___ coats at school.\"", "their", "there", "they're", "thare"],
    ["Science", "What force pulls objects towards the ground?", "gravity", "magnetism", "friction", "light"],
    ["Science", "Which planet is closest to the Sun?", "Mercury", "Venus", "Earth", "Mars"],
    ["Science", "Which gas do plants take in from the air to make food?", "carbon dioxide", "oxygen", "helium", "nitrogen"],
    ["Science", "At what temperature does water boil (in degrees Celsius)?", "100", "0", "50", "212"],
    ["Science", "Which part of a plant takes in water from the soil?", "the roots", "the leaves", "the flower", "the petals"],
    ["Science", "Which is the hardest natural material?", "diamond", "gold", "iron", "glass"],
    ["Science", "How many bones does an adult human body have?", "206", "106", "306", "150"],
    ["Science", "Which organ pumps blood around the body?", "the heart", "the lungs", "the brain", "the stomach"],
    ["Science", "What do we call animals that eat only plants?", "herbivores", "carnivores", "omnivores", "predators"],
    ["Science", "Which of these materials is magnetic?", "iron", "wood", "plastic", "glass"],
    ["Science", "What is the Sun?", "a star", "a planet", "a moon", "a comet"],
    ["Science", "What do we call a solid turning into a liquid?", "melting", "freezing", "evaporating", "condensing"],
    ["Science", "Which of these is a source of light?", "the Sun", "the Moon", "a mirror", "a window"],
    ["Science", "What is the name of the process plants use to make their own food?", "photosynthesis", "digestion", "respiration", "evaporation"],
    ["Science", "What causes the tides in the sea?", "the Moon's gravity", "the wind", "fish", "volcanoes"],
    ["Science", "Which material is a good conductor of electricity?", "copper", "rubber", "wood", "plastic"],
    ["Science", "How many teeth does a typical adult have?", "32", "20", "28", "40"],
    ["Science", "Which of these is NOT a state of matter?", "sound", "solid", "liquid", "gas"],
    ["Science", "What do we call animals that have a backbone?", "vertebrates", "invertebrates", "insects", "arachnids"],
    ["Science", "Which planet is known as the Red Planet?", "Mars", "Venus", "Jupiter", "Saturn"],
    ["Science", "What type of animal is a frog?", "an amphibian", "a reptile", "a mammal", "a bird"],
    ["Science", "Which blood vessels carry blood away from the heart?", "arteries", "veins", "nerves", "bones"],
    ["Science", "Which of these is a renewable source of energy?", "wind", "coal", "oil", "gas"],
    ["Science", "What happens to a shadow when a light is moved closer to the object?", "it gets bigger", "it gets smaller", "it disappears", "it turns red"],
    ["Science", "What do bees help flowers to do as they travel between them?", "spread pollen", "grow taller", "change colour", "close up"],
    ["Geography", "What is the capital city of France?", "Paris", "Lyon", "Marseille", "Nice"],
    ["Geography", "Which is the longest river in Africa?", "the Nile", "the Amazon", "the Thames", "the Ganges"],
    ["Geography", "Which is the largest ocean?", "the Pacific Ocean", "the Atlantic Ocean", "the Indian Ocean", "the Arctic Ocean"],
    ["Geography", "On which continent is the Sahara Desert?", "Africa", "Asia", "Australia", "South America"],
    ["Geography", "What is the capital city of Japan?", "Tokyo", "Beijing", "Seoul", "Bangkok"],
    ["Geography", "Which mountain is the tallest above sea level?", "Mount Everest", "K2", "Kilimanjaro", "Mont Blanc"],
    ["Geography", "Which imaginary line divides the Earth into northern and southern halves?", "the Equator", "the Prime Meridian", "the horizon", "the Arctic Circle"],
    ["Geography", "How many continents are there?", "7", "5", "6", "8"],
    ["Geography", "What is the capital city of Italy?", "Rome", "Milan", "Venice", "Naples"],
    ["Geography", "Which country is shaped like a boot?", "Italy", "Spain", "Greece", "France"],
    ["Geography", "Which is the largest hot desert in the world?", "the Sahara", "the Gobi", "the Kalahari", "the Thar"],
    ["Geography", "Which is the largest country in the world by area?", "Russia", "Canada", "China", "the USA"],
    ["Geography", "Which sea lies between Europe and Africa?", "the Mediterranean Sea", "the Red Sea", "the Baltic Sea", "the Black Sea"],
    ["Geography", "In which country is the city of Cairo?", "Egypt", "Kenya", "India", "Peru"],
    ["Geography", "What is the capital city of Australia?", "Canberra", "Sydney", "Melbourne", "Perth"],
    ["Geography", "Which river flows through London?", "the Thames", "the Severn", "the Seine", "the Danube"],
    ["Geography", "Which continent is the coldest?", "Antarctica", "Asia", "Africa", "Europe"],
    ["Geography", "What comes out of a volcano when it erupts?", "lava", "snow", "sand", "rain"],
    ["Geography", "In which country do kangaroos live in the wild?", "Australia", "Brazil", "India", "Canada"],
    ["Geography", "Which is the smallest continent?", "Australia", "Europe", "Antarctica", "South America"],
    ["Geography", "What is the capital city of Canada?", "Ottawa", "Toronto", "Vancouver", "Montreal"],
    ["Geography", "Which ocean lies between Africa and Australia?", "the Indian Ocean", "the Atlantic Ocean", "the Arctic Ocean", "the Pacific Ocean"],
    ["Geography", "In which country is most of the Amazon rainforest?", "Brazil", "Argentina", "Mexico", "Chile"],
    ["Geography", "Which instrument do we use to find the direction we are heading?", "a compass", "a thermometer", "a barometer", "a telescope"],
    ["Geography", "What is the capital city of Spain?", "Madrid", "Barcelona", "Lisbon", "Seville"],
    ["History", "Which people built the pyramids at Giza?", "the ancient Egyptians", "the Romans", "the Vikings", "the Greeks"],
    ["History", "Who sailed across the Atlantic and reached the Americas in 1492?", "Christopher Columbus", "Captain Cook", "Marco Polo", "Ferdinand Magellan"],
    ["History", "In which country did the ancient Olympic Games begin?", "Greece", "Italy", "Egypt", "France"],
    ["History", "How many wives did King Henry VIII have?", "6", "4", "8", "2"],
    ["History", "What did the Romans build to carry water to their cities?", "aqueducts", "skyscrapers", "railways", "windmills"],
    ["History", "Who was the first person to walk on the Moon?", "Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "Michael Collins"],
    ["History", "In which year did the Second World War end?", "1945", "1918", "1939", "1960"],
    ["History", "In which year was the Great Fire of London?", "1666", "1066", "1766", "1566"],
    ["History", "Who invented the telephone?", "Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Isaac Newton"],
    ["History", "Which people invaded England in 1066?", "the Normans", "the Romans", "the Greeks", "the Egyptians"],
    ["History", "Who led India to independence using peaceful protest?", "Mahatma Gandhi", "Winston Churchill", "Nelson Mandela", "Abraham Lincoln"],
    ["History", "Which ship sank in 1912 after hitting an iceberg?", "the Titanic", "the Mayflower", "the Victory", "the Endeavour"],
    ["History", "Who painted the Mona Lisa?", "Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Claude Monet"],
    ["History", "What was the name of the ship the Pilgrims sailed to America in 1620?", "the Mayflower", "the Titanic", "the Santa Maria", "the Golden Hind"],
    ["History", "Who was Tutankhamun?", "an Egyptian pharaoh", "a Roman emperor", "a Greek philosopher", "a Viking king"],
    ["History", "Who ruled the Roman Empire?", "emperors", "pharaohs", "samurai", "pirates"],
    ["History", "Which wall did the Romans build in the north of Britain?", "Hadrian's Wall", "the Berlin Wall", "the Great Wall of China", "the Wailing Wall"],
    ["History", "Who was the first female Prime Minister of the United Kingdom?", "Margaret Thatcher", "Theresa May", "Queen Victoria", "Elizabeth II"],
    ["History", "Who was the first President of the United States?", "George Washington", "Abraham Lincoln", "Thomas Jefferson", "John Adams"],
    ["History", "Which scientist is famous for the story of the falling apple and gravity?", "Isaac Newton", "Galileo Galilei", "Albert Einstein", "Charles Darwin"],
    ["History", "In which century did the Wright brothers make the first powered aeroplane flight?", "the 20th century", "the 19th century", "the 18th century", "the 21st century"],
    ["History", "Who were gladiators in ancient Rome?", "fighters who entertained crowds", "doctors", "farmers", "sailors"],
    ["History", "Which civilisation built the mountain city of Machu Picchu?", "the Inca", "the Aztec", "the Romans", "the Vikings"],
    ["History", "Who wrote the play Romeo and Juliet?", "William Shakespeare", "Charles Dickens", "Roald Dahl", "Jane Austen"],
    ["History", "What were the tools of Stone Age people mostly made from?", "stone", "plastic", "steel", "aluminium"],
    ["Maths", "What is 4 × 4?", "16", "20", "12", "6"],
    ["Maths", "What is 7 × 7?", "49", "56", "42", "45"],
    ["Maths", "What is 3 × 8?", "24", "27", "16", "28"],
    ["Maths", "What is 8 × 5?", "40", "48", "35", "38"],
    ["Maths", "What is 7 × 6?", "42", "49", "36", "47"],
    ["Maths", "What is 8 × 12?", "96", "104", "84", "92"],
    ["Maths", "What is 25 ÷ 5?", "5", "2", "3", "9"],
    ["Maths", "What is 9 ÷ 3?", "3", "8", "9", "5"],
    ["Maths", "What is 64 ÷ 8?", "8", "9", "7", "4"],
    ["Maths", "What is 108 ÷ 9?", "12", "11", "9", "7"],
    ["Maths", "What is 163 + 283?", "446", "546", "445", "386"],
    ["Maths", "What is 321 + 324?", "645", "745", "644", "545"],
    ["Maths", "What is 278 + 151?", "429", "529", "428", "369"],
    ["Maths", "What is 596 - 442?", "154", "254", "153", "174"],
    ["Maths", "What is 776 - 194?", "582", "682", "581", "562"],
    ["Maths", "What is 806 - 432?", "374", "474", "373", "404"],
    ["Maths", "What is the perimeter of a rectangle that is 8 cm long and 5 cm wide?", "26 cm", "28 cm", "40 cm", "22 cm"],
    ["Maths", "What is the perimeter of a rectangle that is 12 cm long and 7 cm wide?", "38 cm", "40 cm", "84 cm", "34 cm"],
    ["Maths", "What is the perimeter of a rectangle that is 9 cm long and 6 cm wide?", "30 cm", "32 cm", "54 cm", "26 cm"],
    ["Maths", "What is 1/4 of 24?", "6", "10", "18", "1"],
    ["Maths", "What is 1/5 of 40?", "8", "13", "32", "3"],
    ["Maths", "What is 467 rounded to the nearest 10?", "470", "460", "500", "480"],
    ["Maths", "What is 2,350 rounded to the nearest 100?", "2400", "2300", "2350", "2500"],
    ["Maths", "How many sides does a hexagon have?", "6", "5", "7", "8"],
    ["Maths", "How many degrees are there in a right angle?", "90", "45", "180", "60"],
];

const AGE_11_TO_13: PuzzleRow[] = [
    ["English", "Which of these is a metaphor?", "\"The classroom was a zoo.\"", "\"She ran like the wind.\"", "\"Buzz!\" went the bee.", "\"Peter Piper picked peppers.\""],
    ["English", "Which phrase uses alliteration?", "\"Sally sells seashells\"", "\"as cold as ice\"", "\"the sun smiled\"", "\"Crash!\""],
    ["English", "Which sentence uses personification?", "\"The wind whispered through the trees.\"", "\"The wind was cold.\"", "\"The wind is a thief.\"", "\"Whoosh!\""],
    ["English", "Which of these words is a preposition?", "under", "quickly", "happy", "and"],
    ["English", "What is the past participle of \"write\"?", "written", "wrote", "writed", "writing"],
    ["English", "What do we call the main character, or hero, of a story?", "the protagonist", "the antagonist", "the narrator", "the editor"],
    ["English", "What is an antagonist?", "a character who opposes the hero", "the main hero", "the person telling the story", "the author"],
    ["English", "Which word is the best synonym for \"enormous\"?", "gigantic", "tiny", "average", "gentle"],
    ["English", "Which sentence is correct?", "It's raining outside.", "Its raining outside.", "Its' raining outside.", "It's' raining outside."],
    ["English", "Which sentence is in the passive voice?", "The window was broken by the ball.", "The ball broke the window.", "Break the window.", "Did the ball break the window?"],
    ["English", "What is a semicolon mainly used for?", "to join two closely related main clauses", "to end a question", "to show a missing letter", "to start a quotation"],
    ["English", "Which word sounds the same as \"knight\"?", "night", "knit", "kite", "nigh"],
    ["English", "Which genre would a story about wizards and dragons belong to?", "fantasy", "biography", "news report", "recipe"],
    ["English", "Which word is spelled correctly?", "definitely", "definately", "definitly", "defanitely"],
    ["English", "What is an acronym?", "a word made from the first letters of other words", "a word that sounds like what it means", "a word with the opposite meaning", "a very long word"],
    ["English", "What is the root word of \"unhappiness\"?", "happy", "un", "ness", "unhappy"],
    ["English", "What is a thesaurus used for?", "finding synonyms and antonyms", "finding maps", "finding recipes", "finding dates"],
    ["English", "What is hyperbole?", "deliberate exaggeration", "a comparison using \"like\"", "a repeated sound", "a rhyme"],
    ["English", "What does the idiom \"it's raining cats and dogs\" mean?", "it is raining very heavily", "animals are falling", "the rain has stopped", "pets are outside"],
    ["English", "What does the idiom \"break a leg\" mean?", "good luck", "hurt yourself", "run away", "stop"],
    ["English", "In \"The ancient castle looked mysterious\", which word is a noun?", "castle", "ancient", "looked", "mysterious"],
    ["English", "Which phrase correctly shows bones belonging to several dogs?", "the dogs' bones", "the dog's bones", "the dogs bones", "the dogs's bones"],
    ["English", "Which of these is a complex sentence?", "Although it was raining, we played outside.", "We played outside.", "It rained.", "Rain!"],
    ["English", "A story told using \"I\" and \"we\" is written in which person?", "first person", "second person", "third person", "fourth person"],
    ["English", "Which poem form has 14 lines?", "a sonnet", "a haiku", "a limerick", "a couplet"],
    ["Science", "What is the chemical formula for water?", "H2O", "CO2", "O2", "NaCl"],
    ["Science", "Which gas makes up most of the air we breathe?", "nitrogen", "oxygen", "carbon dioxide", "hydrogen"],
    ["Science", "Which part of a cell is known as its \"powerhouse\"?", "the mitochondria", "the nucleus", "the ribosome", "the membrane"],
    ["Science", "What is the unit of force?", "the newton", "the joule", "the watt", "the volt"],
    ["Science", "What is the chemical symbol for gold?", "Au", "Ag", "Go", "Gd"],
    ["Science", "What is the pH of a neutral substance such as pure water?", "7", "0", "14", "1"],
    ["Science", "Which organs filter the blood to make urine?", "the kidneys", "the liver", "the lungs", "the heart"],
    ["Science", "What do we call a liquid turning into a gas?", "evaporation", "condensation", "freezing", "melting"],
    ["Science", "Which planet is best known for its rings?", "Saturn", "Mars", "Mercury", "Venus"],
    ["Science", "What is found at the centre of an atom?", "the nucleus", "an electron", "a cell", "a molecule"],
    ["Science", "Which gas do humans breathe out?", "carbon dioxide", "oxygen", "helium", "hydrogen"],
    ["Science", "What is the green pigment in plants called?", "chlorophyll", "haemoglobin", "melanin", "keratin"],
    ["Science", "Which particles have a negative charge?", "electrons", "protons", "neutrons", "nuclei"],
    ["Science", "Which of these is a pure element?", "oxygen", "water", "salt", "air"],
    ["Science", "What is the unit of electric current?", "the ampere (amp)", "the volt", "the ohm", "the watt"],
    ["Science", "Which blood cells carry oxygen around the body?", "red blood cells", "white blood cells", "platelets", "plasma"],
    ["Science", "Which type of rock is formed from cooled lava?", "igneous", "sedimentary", "metamorphic", "fossil"],
    ["Science", "Which is the closest star to Earth?", "the Sun", "Proxima Centauri", "Sirius", "Polaris"],
    ["Science", "What is the name for water loss from a plant's leaves?", "transpiration", "respiration", "digestion", "germination"],
    ["Science", "Which part of the eye changes size to control how much light enters?", "the iris", "the cornea", "the retina", "the optic nerve"],
    ["Science", "What is the chemical formula of table salt?", "NaCl", "KCl", "NaOH", "HCl"],
    ["Science", "What do we call the tendency of an object to resist a change in its motion?", "inertia", "gravity", "friction", "magnetism"],
    ["Science", "What is the pH of an acid?", "less than 7", "exactly 7", "more than 7", "exactly 14"],
    ["Science", "What is the hot liquid rock beneath the Earth's surface called?", "magma", "granite", "basalt", "limestone"],
    ["Science", "What type of energy does a moving object have?", "kinetic energy", "potential energy", "chemical energy", "nuclear energy"],
    ["Geography", "What is the capital city of Brazil?", "Brasília", "Rio de Janeiro", "São Paulo", "Buenos Aires"],
    ["Geography", "Which is the largest country in Africa by area?", "Algeria", "Nigeria", "Egypt", "South Africa"],
    ["Geography", "Which river flows through the city of Cairo?", "the Nile", "the Niger", "the Congo", "the Zambezi"],
    ["Geography", "Which two countries share the longest land border in the world?", "Canada and the USA", "Russia and China", "India and Pakistan", "Brazil and Peru"],
    ["Geography", "Which is the highest waterfall in the world?", "Angel Falls", "Niagara Falls", "Victoria Falls", "Iguazu Falls"],
    ["Geography", "In which country is Mount Kilimanjaro?", "Tanzania", "Kenya", "Uganda", "Ethiopia"],
    ["Geography", "Off the coast of which country is the Great Barrier Reef?", "Australia", "Brazil", "Indonesia", "Mexico"],
    ["Geography", "Which is the deepest ocean trench?", "the Mariana Trench", "the Puerto Rico Trench", "the Java Trench", "the Tonga Trench"],
    ["Geography", "Which strait separates Spain from Morocco?", "the Strait of Gibraltar", "the Bering Strait", "the Strait of Malacca", "the Strait of Hormuz"],
    ["Geography", "What is the line of 0° longitude called?", "the Prime Meridian", "the Equator", "the Tropic of Cancer", "the Arctic Circle"],
    ["Geography", "What is the capital city of Turkey?", "Ankara", "Istanbul", "Izmir", "Antalya"],
    ["Geography", "On which continent are the Himalayas?", "Asia", "Europe", "Africa", "South America"],
    ["Geography", "Which is the longest river in South America?", "the Amazon", "the Orinoco", "the Paraná", "the Magdalena"],
    ["Geography", "What is the capital city of Germany?", "Berlin", "Munich", "Hamburg", "Frankfurt"],
    ["Geography", "Which country is also a continent?", "Australia", "Greenland", "India", "Brazil"],
    ["Geography", "What is the capital city of Kenya?", "Nairobi", "Mombasa", "Kampala", "Dodoma"],
    ["Geography", "In which country is Mount Fuji?", "Japan", "China", "South Korea", "the Philippines"],
    ["Geography", "Which body of water is the saltiest and has the lowest land surface on Earth?", "the Dead Sea", "the Black Sea", "the Red Sea", "the Caspian Sea"],
    ["Geography", "What is the scientific study of the weather called?", "meteorology", "geology", "ecology", "cartography"],
    ["Geography", "What causes most earthquakes?", "movement of tectonic plates", "storms", "tides", "strong winds"],
    ["Geography", "Which of these countries is landlocked (has no coast)?", "Switzerland", "Italy", "Portugal", "Greece"],
    ["Geography", "What is the capital city of Argentina?", "Buenos Aires", "Santiago", "Lima", "Montevideo"],
    ["Geography", "What is the imaginary line at 0° latitude called?", "the Equator", "the Prime Meridian", "the Tropic of Capricorn", "the International Date Line"],
    ["Geography", "Which desert lies across southern Mongolia and northern China?", "the Gobi Desert", "the Sahara Desert", "the Kalahari Desert", "the Atacama Desert"],
    ["Geography", "The River Ganges flows mainly through which country?", "India", "China", "Egypt", "Brazil"],
    ["History", "In which year was the Magna Carta sealed?", "1215", "1066", "1415", "1688"],
    ["History", "Who was the first Emperor of Rome?", "Augustus", "Julius Caesar", "Nero", "Caligula"],
    ["History", "In which century did the Black Death reach Europe?", "the 14th century", "the 10th century", "the 18th century", "the 20th century"],
    ["History", "Who won the Battle of Hastings in 1066?", "William of Normandy", "King Harold", "Alfred the Great", "King Canute"],
    ["History", "Which empire was founded by Genghis Khan?", "the Mongol Empire", "the Ottoman Empire", "the Roman Empire", "the Persian Empire"],
    ["History", "In which year did the First World War begin?", "1914", "1918", "1939", "1905"],
    ["History", "In which country did the Industrial Revolution begin?", "Britain", "France", "the USA", "Japan"],
    ["History", "Who was the British Prime Minister for most of the Second World War?", "Winston Churchill", "Neville Chamberlain", "Margaret Thatcher", "Tony Blair"],
    ["History", "Who was the first human to travel into space?", "Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "Alan Shepard"],
    ["History", "In which country did the Renaissance begin?", "Italy", "England", "Spain", "Russia"],
    ["History", "In which year did the Berlin Wall come down?", "1989", "1961", "1945", "1991"],
    ["History", "Who was the main author of the American Declaration of Independence?", "Thomas Jefferson", "George Washington", "Benjamin Franklin", "Abraham Lincoln"],
    ["History", "Which two ancient Greek city-states were famous rivals?", "Athens and Sparta", "Rome and Carthage", "Cairo and Thebes", "Troy and Corinth"],
    ["History", "Which US President was assassinated in 1865?", "Abraham Lincoln", "George Washington", "Thomas Jefferson", "Theodore Roosevelt"],
    ["History", "In which year was the Spanish Armada defeated?", "1588", "1488", "1688", "1788"],
    ["History", "Who built the Taj Mahal in memory of his wife?", "Shah Jahan", "Akbar", "Babur", "Aurangzeb"],
    ["History", "Cleopatra was the last active ruler of which country?", "Egypt", "Greece", "Rome", "Persia"],
    ["History", "In which year did India gain independence from Britain?", "1947", "1919", "1950", "1930"],
    ["History", "Who introduced the printing press with movable type to Europe around 1440?", "Johannes Gutenberg", "William Caxton", "Leonardo da Vinci", "Isaac Newton"],
    ["History", "What was the Silk Road?", "a network of trade routes linking China with the West", "a road made of silk", "a famous railway", "a type of ship"],
    ["History", "Which US President issued the Emancipation Proclamation?", "Abraham Lincoln", "George Washington", "Franklin Roosevelt", "John Kennedy"],
    ["History", "In which year did the French Revolution begin?", "1789", "1689", "1889", "1815"],
    ["History", "The Cold War was mainly a rivalry between which two superpowers?", "the USA and the Soviet Union", "the UK and France", "China and Japan", "Germany and Italy"],
    ["History", "Nelson Mandela became president of which country?", "South Africa", "Kenya", "Nigeria", "Ghana"],
    ["History", "In which year did the Wright brothers make the first powered aeroplane flight?", "1903", "1783", "1927", "1945"],
    ["Maths", "What is 10% of 250?", "25", "50", "225", "19"],
    ["Maths", "What is 25% of 80?", "20", "40", "60", "22"],
    ["Maths", "What is 20% of 150?", "30", "60", "120", "20"],
    ["Maths", "What is 15% of 60?", "9", "18", "51", "14"],
    ["Maths", "What is -3 + 8?", "5", "7", "3", "-5"],
    ["Maths", "What is -7 + 4?", "-3", "-1", "-5", "3"],
    ["Maths", "What is 5 + -9?", "-4", "-2", "-6", "4"],
    ["Maths", "What is the area of a rectangle 12 cm by 7 cm?", "84 cm²", "38 cm²", "96 cm²", "77 cm²"],
    ["Maths", "What is the area of a rectangle 15 cm by 8 cm?", "120 cm²", "46 cm²", "135 cm²", "112 cm²"],
    ["Maths", "What is the area of a rectangle 9 cm by 13 cm?", "117 cm²", "44 cm²", "126 cm²", "104 cm²"],
    ["Maths", "Solve for x: 5x + 2 = 47", "9", "11", "10", "3"],
    ["Maths", "Solve for x: 2x + 8 = 24", "8", "16", "9", "4"],
    ["Maths", "Solve for x: 2x + 2 = 18", "8", "10", "9", "3"],
    ["Maths", "Solve for x: 6x + 13 = 37", "4", "17", "5", "1"],
    ["Maths", "What is the square root of 49?", "7", "8", "6", "14"],
    ["Maths", "What is the square root of 81?", "9", "10", "8", "18"],
    ["Maths", "What is the square root of 144?", "12", "13", "11", "24"],
    ["Maths", "What is the mean of 4, 8, 6, 10 and 12?", "8", "7", "9", "10"],
    ["Maths", "What is the mean of 3, 7, 9 and 5?", "6", "5", "7", "8"],
    ["Maths", "What is the median of 3, 9, 4, 7 and 12?", "7", "4", "9", "6"],
    ["Maths", "Two angles in a triangle are 50° and 60°. What is the third angle?", "70°", "80°", "60°", "90°"],
    ["Maths", "The angles on a straight line add up to what?", "180°", "90°", "360°", "270°"],
    ["Maths", "Which of these is a prime number?", "29", "27", "21", "33"],
    ["Maths", "Share £60 in the ratio 1 : 2. What is the larger share?", "£40", "£30", "£20", "£45"],
    ["Maths", "Simplify the ratio 12 : 18.", "2 : 3", "3 : 4", "4 : 5", "1 : 2"],
];

const AGE_14_TO_17: PuzzleRow[] = [
    ["English", "Which literary device is used in \"Time is a thief\"?", "metaphor", "simile", "irony", "oxymoron"],
    ["English", "\"Deafening silence\" is an example of which device?", "oxymoron", "simile", "pun", "hyperbole"],
    ["English", "Who wrote the novel \"1984\"?", "George Orwell", "Aldous Huxley", "H. G. Wells", "Ray Bradbury"],
    ["English", "Who wrote \"Pride and Prejudice\"?", "Jane Austen", "Charlotte Brontë", "George Eliot", "Emily Brontë"],
    ["English", "In which Shakespeare play is the main character a prince of Denmark?", "Hamlet", "Macbeth", "Othello", "King Lear"],
    ["English", "What do we call a speech in which a character speaks their thoughts aloud, alone on stage?", "a soliloquy", "a prologue", "an epilogue", "a dialogue"],
    ["English", "Which of these is a subordinating conjunction?", "although", "and", "but", "or"],
    ["English", "What is dramatic irony?", "when the audience knows more than the characters", "when someone says the opposite of what they mean", "when something unexpected happens", "when a character lies"],
    ["English", "Who wrote \"To Kill a Mockingbird\"?", "Harper Lee", "Mark Twain", "J. D. Salinger", "F. Scott Fitzgerald"],
    ["English", "Which is correct? \"There are ___ apples in the bowl than yesterday.\"", "fewer", "less", "lesser", "littler"],
    ["English", "How many syllables are in a line of iambic pentameter?", "10", "8", "12", "14"],
    ["English", "What is the repetition of vowel sounds in nearby words called?", "assonance", "consonance", "alliteration", "rhyme"],
    ["English", "Who wrote \"Lord of the Flies\"?", "William Golding", "George Orwell", "John Steinbeck", "Roald Dahl"],
    ["English", "What is a \"foil\" in literature?", "a character who contrasts with another to highlight their traits", "a type of rhyme", "the final chapter", "a narrator"],
    ["English", "Who wrote \"Great Expectations\"?", "Charles Dickens", "Thomas Hardy", "Oscar Wilde", "Robert Louis Stevenson"],
    ["English", "In \"Swimming is fun\", which word is a gerund?", "Swimming", "is", "fun", "none of them"],
    ["English", "What does \"ubiquitous\" mean?", "found everywhere", "very rare", "extremely loud", "ancient"],
    ["English", "What does \"benevolent\" mean?", "kind and well-meaning", "cruel", "lazy", "confused"],
    ["English", "What is a \"bildungsroman\"?", "a novel about growing up", "a war poem", "a type of play", "a news article"],
    ["English", "What is pathetic fallacy?", "weather or nature that reflects the mood of a scene", "a mistake in logic", "a very sad ending", "a character who is a fool"],
    ["English", "Which sentence uses \"whom\" correctly?", "To whom did you speak?", "Whom is going to the shop?", "Whom went home?", "Whom are you?"],
    ["English", "Who wrote \"The Great Gatsby\"?", "F. Scott Fitzgerald", "Ernest Hemingway", "John Steinbeck", "William Faulkner"],
    ["English", "Which of these is a Shakespeare comedy?", "A Midsummer Night's Dream", "Macbeth", "Hamlet", "Othello"],
    ["English", "What is the climax of a story?", "the point of highest tension", "the opening scene", "the final summary", "the title"],
    ["English", "Who wrote \"Frankenstein\"?", "Mary Shelley", "Jane Austen", "Bram Stoker", "Emily Brontë"],
    ["Science", "Which equation represents Newton's second law of motion?", "F = ma", "E = mc²", "V = IR", "P = mv"],
    ["Science", "What is the atomic number of carbon?", "6", "12", "8", "14"],
    ["Science", "What does DNA stand for?", "deoxyribonucleic acid", "dinitrogen acid", "dioxyribose nucleic acid", "deoxyribose nitric acid"],
    ["Science", "What is the approximate speed of light in a vacuum?", "300,000 km per second", "3,000 km per second", "30,000 km per second", "3,000,000 km per second"],
    ["Science", "What is the SI unit of energy?", "the joule", "the watt", "the newton", "the pascal"],
    ["Science", "Which sub-atomic particle has no electric charge?", "the neutron", "the proton", "the electron", "the positron"],
    ["Science", "Which equation is Ohm's law?", "V = IR", "F = ma", "E = mc²", "P = IV"],
    ["Science", "Which organelle is the site of protein synthesis in a cell?", "the ribosome", "the mitochondrion", "the lysosome", "the Golgi apparatus"],
    ["Science", "Which of these is a noble gas?", "helium", "oxygen", "hydrogen", "nitrogen"],
    ["Science", "About what is the pH of the acid in the human stomach?", "2", "7", "9", "12"],
    ["Science", "What type of bond is formed when atoms share electrons?", "a covalent bond", "an ionic bond", "a metallic bond", "a hydrogen bond"],
    ["Science", "Which of these gases is a major greenhouse gas?", "carbon dioxide", "argon", "neon", "helium"],
    ["Science", "Which type of cell division produces two identical cells for growth?", "mitosis", "meiosis", "osmosis", "diffusion"],
    ["Science", "What is the chemical formula of methane?", "CH4", "CO2", "C2H6", "CH3OH"],
    ["Science", "Who proposed the theory of evolution by natural selection?", "Charles Darwin", "Gregor Mendel", "Louis Pasteur", "Isaac Newton"],
    ["Science", "What does the \"half-life\" of a radioactive substance mean?", "the time for half the atoms to decay", "half the time it exists", "the time to double in size", "half its mass at birth"],
    ["Science", "Which blood group is known as the universal donor for red blood cells?", "O negative", "AB positive", "A positive", "B negative"],
    ["Science", "What is the acceleration due to gravity on Earth, approximately?", "9.8 m/s²", "1.6 m/s²", "3.7 m/s²", "24.8 m/s²"],
    ["Science", "What is Avogadro's number, approximately?", "6.02 × 10²³", "6.02 × 10¹²", "3.00 × 10⁸", "9.81 × 10⁻³"],
    ["Science", "Which enzyme in saliva begins the digestion of starch?", "amylase", "pepsin", "lipase", "trypsin"],
    ["Science", "What type of wave is a sound wave?", "longitudinal", "transverse", "electromagnetic", "standing only"],
    ["Science", "Which element has the chemical symbol Fe?", "iron", "fluorine", "lead", "tin"],
    ["Science", "Which part of the brain is mainly responsible for balance and coordination?", "the cerebellum", "the cerebrum", "the medulla", "the hypothalamus"],
    ["Science", "Which gas makes up most of the Sun?", "hydrogen", "helium", "oxygen", "carbon"],
    ["Science", "What is the process of splitting a heavy nucleus into smaller nuclei called?", "nuclear fission", "nuclear fusion", "combustion", "oxidation"],
    ["Geography", "Which line of latitude lies at about 23.5° North?", "the Tropic of Cancer", "the Tropic of Capricorn", "the Equator", "the Arctic Circle"],
    ["Geography", "What is the largest desert in the world?", "the Antarctic Desert", "the Sahara", "the Arabian Desert", "the Gobi"],
    ["Geography", "What type of tectonic plate boundary is it where plates move apart?", "divergent", "convergent", "transform", "subduction"],
    ["Geography", "What is the capital city of Kazakhstan?", "Astana", "Almaty", "Tashkent", "Bishkek"],
    ["Geography", "Which river flows through the city of Baghdad?", "the Tigris", "the Euphrates", "the Nile", "the Jordan"],
    ["Geography", "What do we call the average weather of a place over about 30 years?", "climate", "weather", "a season", "a forecast"],
    ["Geography", "The \"Ring of Fire\", an area of many volcanoes, surrounds which ocean?", "the Pacific Ocean", "the Atlantic Ocean", "the Indian Ocean", "the Arctic Ocean"],
    ["Geography", "Which is the largest island in the world (not counting continents)?", "Greenland", "Borneo", "Madagascar", "New Guinea"],
    ["Geography", "Which mountain range forms the traditional boundary between Europe and Asia?", "the Ural Mountains", "the Alps", "the Andes", "the Pyrenees"],
    ["Geography", "What is the capital city of New Zealand?", "Wellington", "Auckland", "Christchurch", "Hamilton"],
    ["Geography", "Which rivers form a huge delta in Bangladesh?", "the Ganges and Brahmaputra", "the Indus and Jhelum", "the Mekong and Salween", "the Yangtze and Yellow"],
    ["Geography", "Which is the longest river in Asia?", "the Yangtze", "the Ganges", "the Mekong", "the Indus"],
    ["Geography", "A monsoon is a seasonal change in what?", "wind direction", "tides", "volcanic activity", "plate movement"],
    ["Geography", "Which is the deepest lake in the world?", "Lake Baikal", "Lake Superior", "Lake Victoria", "Lake Tanganyika"],
    ["Geography", "Ulaanbaatar is the capital city of which country?", "Mongolia", "Kazakhstan", "Nepal", "Bhutan"],
    ["Geography", "What does the term \"urbanisation\" describe?", "the growth in the share of people living in towns and cities", "the growth of forests", "the spread of deserts", "the decline of rivers"],
    ["Geography", "Which is the smallest country in the world by area?", "Vatican City", "Monaco", "San Marino", "Malta"],
    ["Geography", "Which canal links the Mediterranean Sea with the Red Sea?", "the Suez Canal", "the Panama Canal", "the Kiel Canal", "the Corinth Canal"],
    ["Geography", "Which warm ocean current helps to keep north-west Europe mild?", "the Gulf Stream (North Atlantic Drift)", "the Humboldt Current", "the Canary Current", "the Labrador Current"],
    ["Geography", "What is the highest mountain in North America?", "Denali", "Mount Whitney", "Mount Logan", "Mount Rainier"],
    ["Geography", "In which country is the city of Cape Town?", "South Africa", "Namibia", "Kenya", "Nigeria"],
    ["Geography", "What is the starting point of a river called?", "its source", "its mouth", "a tributary", "a meander"],
    ["Geography", "Fjords are most closely associated with which country?", "Norway", "Egypt", "Brazil", "India"],
    ["Geography", "Which strait separates Asia from North America?", "the Bering Strait", "the Strait of Gibraltar", "the Strait of Malacca", "the Strait of Hormuz"],
    ["Geography", "The Sahel is a semi-arid region on which side of the Sahara?", "the southern side", "the northern side", "the eastern side", "the western edge only"],
    ["History", "The First World War began after the assassination of whom?", "Archduke Franz Ferdinand", "Kaiser Wilhelm II", "Tsar Nicholas II", "Winston Churchill"],
    ["History", "Which treaty officially ended the First World War with Germany?", "the Treaty of Versailles", "the Treaty of Paris", "the Treaty of Vienna", "the Treaty of Rome"],
    ["History", "In which year was the Russian Revolution that brought the Bolsheviks to power?", "1917", "1905", "1939", "1953"],
    ["History", "Who was the first emperor of a unified China?", "Qin Shi Huang", "Kublai Khan", "Sun Yat-sen", "Mao Zedong"],
    ["History", "Whose improvements to the steam engine helped drive the Industrial Revolution?", "James Watt", "Isaac Newton", "Michael Faraday", "Alexander Fleming"],
    ["History", "Which leader of Germany started the Second World War in 1939?", "Adolf Hitler", "Otto von Bismarck", "Kaiser Wilhelm II", "Erich Honecker"],
    ["History", "Where did the D-Day landings of 1944 take place?", "Normandy", "Dunkirk", "Calais", "Berlin"],
    ["History", "In which year was the Cuban Missile Crisis?", "1962", "1945", "1973", "1989"],
    ["History", "Who gave the \"I Have a Dream\" speech in 1963?", "Martin Luther King Jr.", "Malcolm X", "Rosa Parks", "Barack Obama"],
    ["History", "The League of Nations was set up after which event?", "the First World War", "the Second World War", "the Cold War", "the French Revolution"],
    ["History", "What was the capital city of the Ottoman Empire?", "Constantinople (Istanbul)", "Cairo", "Baghdad", "Athens"],
    ["History", "The Meiji Restoration of 1868 took place in which country?", "Japan", "China", "Korea", "Thailand"],
    ["History", "At which battle was Napoleon finally defeated in 1815?", "Waterloo", "Trafalgar", "Austerlitz", "Borodino"],
    ["History", "In which year was the Berlin Wall built?", "1961", "1945", "1989", "1953"],
    ["History", "Which event began the Second World War in Europe in September 1939?", "Germany invading Poland", "the bombing of Pearl Harbor", "the fall of Paris", "the Battle of Britain"],
    ["History", "The Great Depression began with the stock market crash in which year?", "1929", "1914", "1945", "1957"],
    ["History", "In which year were the first multiracial elections held in South Africa, ending apartheid rule?", "1994", "1976", "1961", "2004"],
    ["History", "Which dynasty built most of the Great Wall of China that survives today?", "the Ming dynasty", "the Han dynasty", "the Tang dynasty", "the Qing dynasty"],
    ["History", "Which British Prime Minister was nicknamed the \"Iron Lady\"?", "Margaret Thatcher", "Theresa May", "Winston Churchill", "Clement Attlee"],
    ["History", "Which king of France was executed in 1793?", "Louis XVI", "Louis XIV", "Napoleon III", "Charles X"],
    ["History", "Which Portuguese explorer reached India by sea in 1498?", "Vasco da Gama", "Ferdinand Magellan", "Christopher Columbus", "Bartolomeu Dias"],
    ["History", "In which year did the Soviet Union dissolve?", "1991", "1985", "1979", "2001"],
    ["History", "At which battle in 1805 was Admiral Nelson killed?", "Trafalgar", "Waterloo", "Jutland", "Hastings"],
    ["History", "In which years was the Spanish Civil War fought?", "1936 to 1939", "1914 to 1918", "1939 to 1945", "1950 to 1953"],
    ["History", "Which period of European history is known for a revival of art and learning, beginning in the 14th century?", "the Renaissance", "the Reformation", "the Enlightenment", "the Dark Ages"],
    ["Maths", "Solve x² - 5x + 6 = 0.", "x = 2 or x = 3", "x = -2 or x = -3", "x = 1 or x = 6", "x = 2 or x = -3"],
    ["Maths", "Solve x² - 9 = 0.", "x = 3 or x = -3", "x = 3 only", "x = 9 or x = -9", "x = 0"],
    ["Maths", "Solve x² + 2x - 8 = 0.", "x = 2 or x = -4", "x = -2 or x = 4", "x = 2 or x = 4", "x = 8 or x = -1"],
    ["Maths", "Expand (x + 3)(x + 2).", "x² + 5x + 6", "x² + 6x + 5", "x² + 5x + 5", "x² + x + 6"],
    ["Maths", "Expand (x - 4)(x + 4).", "x² - 16", "x² + 16", "x² - 8x - 16", "x² - 4x + 16"],
    ["Maths", "Factorise x² + 7x + 12.", "(x + 3)(x + 4)", "(x + 2)(x + 6)", "(x + 1)(x + 12)", "(x - 3)(x - 4)"],
    ["Maths", "What is 5⁰?", "1", "0", "5", "undefined"],
    ["Maths", "What is 2³ × 2⁴?", "2⁷", "2¹²", "4⁷", "2¹"],
    ["Maths", "What is 9^(1/2)?", "3", "4.5", "81", "18"],
    ["Maths", "What is 10⁻²?", "0.01", "-100", "0.1", "-0.01"],
    ["Maths", "A right-angled triangle has shorter sides 6 cm and 8 cm. How long is the hypotenuse?", "10 cm", "14 cm", "12 cm", "9 cm"],
    ["Maths", "A right-angled triangle has hypotenuse 13 cm and one side 5 cm. How long is the other side?", "12 cm", "8 cm", "11 cm", "10 cm"],
    ["Maths", "A ladder 5 m long leans against a wall with its foot 3 m from the wall. How high up the wall does it reach?", "4 m", "2 m", "3 m", "5.8 m"],
    ["Maths", "A fair six-sided dice is rolled. What is the probability of rolling a number greater than 4?", "1/3", "1/6", "1/2", "2/3"],
    ["Maths", "Two fair coins are tossed. What is the probability of getting two heads?", "1/4", "1/2", "1/3", "3/4"],
    ["Maths", "What is sin 30°?", "1/2", "√3/2", "1", "√2/2"],
    ["Maths", "What is cos 60°?", "1/2", "√3/2", "0", "1"],
    ["Maths", "What is the gradient of the line y = 3x - 5?", "3", "-5", "5", "0.3333333333333333"],
    ["Maths", "What is the gradient of the line passing through (1, 2) and (3, 8)?", "3", "2", "6", "4"],
    ["Maths", "Write 45,000 in standard form.", "4.5 × 10⁴", "4.5 × 10³", "45 × 10⁴", "4.5 × 10⁵"],
    ["Maths", "Solve the simultaneous equations x + y = 10 and x - y = 4.", "x = 7, y = 3", "x = 6, y = 4", "x = 8, y = 2", "x = 5, y = 5"],
    ["Maths", "Solve the simultaneous equations 2x + y = 11 and x - y = 1.", "x = 4, y = 3", "x = 3, y = 5", "x = 5, y = 1", "x = 4, y = 4"],
    ["Maths", "What is log₁₀ 1000?", "3", "2", "10", "100"],
    ["Maths", "What is the sum of the interior angles of a hexagon?", "720°", "540°", "360°", "900°"],
    ["Maths", "A sum of £1,000 earns 10% compound interest per year. How much is it worth after 2 years?", "£1,210", "£1,200", "£1,100", "£1,220"],
];

export const PUZZLES_BY_AGE_BAND: Record<AgeBand, Puzzle[]> = {
    '5-7': toPuzzles(AGE_5_TO_7),
    '8-10': toPuzzles(AGE_8_TO_10),
    '11-13': toPuzzles(AGE_11_TO_13),
    '14-17': toPuzzles(AGE_14_TO_17),
};
